import Vsa.Sim.ValueSites
import Vsa.Sim.DecodeNF
import Vsa.Sim.RamReadPins
import Vsa.Sim.ExecLoadTotal
import Vsa.Sim.StrcpySites
import Lua.Vm.Code.FixedImage_LuaV_execute
import Lua.Vm.Arms.Text

/-!
Per-site `StepObs` battery GENERATED by scripts/syi/gen_sites.py from
the F1 arms of luaV_execute (driver: scripts/gen_lua_arms.py) against `Lua.Vm.Arms.TextLoaded`.
Do not hand-edit; regenerate instead.
-/

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail ConcurrencyInterfaceV1 Vsa
open Register
open Sail.ConcurrencyInterfaceV1.PreSail
open Vsa.Machine (MState Config Step Steps)
open Vsa.Sim

-- discipline: allow(R5-stepobs-volume) a per-site battery is one `stepObs_` per
-- site BY CONSTRUCTION; this file is machine-emitted from a TSV, not a
-- hand-threaded chain.
-- discipline: allow(R7-conj-tower-def) the existentials are the `∃ σ' i'` of each
-- site's `StepObs` conclusion (the landed shape), not new ∃/∧-tower posts.

namespace Lua.Vm.Arms

/-- 0x8001f804: `xor x14,x26,x10`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f804 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v26 v10 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx26 : σ.regs.get? Register.x26 = some v26)
    (hx10 : σ.regs.get? Register.x10 = some v10)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f804#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x14 (v26 ^^^ v10)) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f804 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_alu σ i u (0x8001f804#64) vminstret (0x00ad4733#32)
    (instruction.RTYPE (regidx.Regidx 0x0a#5, regidx.Regidx 0x1a#5, regidx.Regidx 0x0e#5, rop.XOR))
    Register.x14 (v26 ^^^ v10)
    (0x33#8) (0x47#8) (0xad#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x00ad4733#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_rtype_xor_char (regidx.Regidx 0x0a#5) (regidx.Regidx 0x1a#5) (regidx.Regidx 0x0e#5) v26 v10
      (afterNextPC (afterPrelude σ) (0x8001f804#64))
      (sigma3_alu σ (0x8001f804#64) Register.x14 (v26 ^^^ v10))
      (rX_bits_x26 _ v26
        (by rw [get?_afterNextPC σ (0x8001f804#64) _ (by decide) (by decide)]; exact hx26))
      (rX_bits_x10 _ v10
        (by rw [get?_afterNextPC σ (0x8001f804#64) _ (by decide) (by decide)]; exact hx10))
      (wX_bits_x14 _ (v26 ^^^ v10)))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f808: `blt x14,x0` (NOT taken). -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f808_nottaken (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v14 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx14 : σ.regs.get? Register.x14 = some v14)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f808#64 : BitVec 64))
    (hv : zopz0zI_s v14 (0#64) = false) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_branch_nottaken σ pc vminstret) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f808 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_branch_nottaken σ i u (0x8001f808#64) vminstret (0x036c#13)
    (regidx.Regidx 0x0e#5) (regidx.Regidx 0x00#5) bop.BLT (0x36074663#32)
    (0x63#8) (0x46#8) (0x07#8) (0x36#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x36074663#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_btype_blt_nottaken (0x036c#13) (regidx.Regidx 0x0e#5) (regidx.Regidx 0x00#5)
      v14 (0#64) (afterNextPC (afterPrelude σ) (0x8001f808#64))
      (rX_bits_x14 _ v14
        (by rw [get?_afterNextPC σ (0x8001f808#64) _ (by decide) (by decide)]; exact hx14))
      (rX_bits_zero _)
      hv)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- Branch target of the taken site at 0x8001f808. -/
-- discipline: allow(R1-site-battery) machine-emitted by scripts/gen_sites.py
theorem site_8001f808_taken_tgt :
    (0x8001f808#64 + sign_extend (m := 64) (0x036c#13)) = (0x8001fb74#64 : BitVec 64) := by
  apply BitVec.eq_of_toNat_eq; decide

/-- 0x8001f808: `blt x14,x0 → 0x8001fb74` (TAKEN). -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f808_taken (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v14 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx14 : σ.regs.get? Register.x14 = some v14)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f808#64 : BitVec 64))
    (hv : zopz0zI_s v14 (0#64) = true) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_branch_taken σ pc vminstret (0x036c#13)) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f808 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_branch_taken σ i u (0x8001f808#64) vminstret (0x036c#13)
    (regidx.Regidx 0x0e#5) (regidx.Regidx 0x00#5) bop.BLT (0x36074663#32)
    (0x63#8) (0x46#8) (0x07#8) (0x36#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x36074663#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_btype_blt_taken (0x036c#13) (regidx.Regidx 0x0e#5) (regidx.Regidx 0x00#5)
      v14 (0#64) (0x8001f808#64) initMisa (afterNextPC (afterPrelude σ) (0x8001f808#64))
      (rX_bits_x14 _ v14
        (by rw [get?_afterNextPC σ (0x8001f808#64) _ (by decide) (by decide)]; exact hx14))
      (rX_bits_zero _)
      (by rw [get?_afterNextPC σ (0x8001f808#64) _ (by decide) (by decide)]; exact hpc)
      (by rw [get?_afterNextPC σ (0x8001f808#64) _ (by decide) (by decide)]; exact hG.misa)
      (by rw [site_8001f808_taken_tgt]; decide) hv)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f80c: `sd x15,0x0(x22)`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f80c (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v22 v15 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx22 : σ.regs.get? Register.x22 = some v22)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f80c#64 : BitVec 64))
    (halo : 0x80000000 ≤ (v22 + sign_extend (m := 64) (0x000#12)).toNat)
    (hahiram : (v22 + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ 0x100000000)
    (hahiwin : tohostAddr + 16 ≤ (v22 + sign_extend (m := 64) (0x000#12)).toNat)
    (haalign : (v22 + sign_extend (m := 64) (0x000#12)).toNat % 8 = 0) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = writeMap8 (afterNextPC (afterPrelude σ) (0x8001f80c#64)).mem
        (v22 + sign_extend (m := 64) (0x000#12)).toNat (sdData_val v15) ∧
      ReadsLikePost σ' (sigmaPost_store σ pc vminstret
        (writeMap8 (afterNextPC (afterPrelude σ) (0x8001f80c#64)).mem (v22 + sign_extend (m := 64) (0x000#12)).toNat (sdData_val v15))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f80c (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_store σ i u (0x8001f80c#64) vminstret (0x00fb3023#32)
    (instruction.STORE (0x000#12, regidx.Regidx 0x0f#5, regidx.Regidx 0x16#5, 8))
    (writeMap8 (afterNextPC (afterPrelude σ) (0x8001f80c#64)).mem (v22 + sign_extend (m := 64) (0x000#12)).toNat (sdData_val v15))
    (0x23#8) (0x30#8) (0xfb#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x00fb3023#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (exec_sd_val σ (0x8001f80c#64) (0x000#12) (regidx.Regidx 0x0f#5) (regidx.Regidx 0x16#5)
      v22 v15 hG
      (rX_bits_x22 _ v22
        (by rw [get?_afterNextPC σ (0x8001f80c#64) _ (by decide) (by decide)]; exact hx22))
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x8001f80c#64) _ (by decide) (by decide)]; exact hx15))
      halo hahiram hahiwin haalign)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f810: `addi x15,x0,0x3`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f810 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f810#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x15
        ((0#64) + sign_extend (m := 64) (0x003#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f810 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_alu σ i u (0x8001f810#64) vminstret (0x00300793#32)
    (instruction.ITYPE (0x003#12, regidx.Regidx 0x00#5, regidx.Regidx 0x0f#5, iop.ADDI))
    Register.x15 ((0#64) + sign_extend (m := 64) (0x003#12))
    (0x93#8) (0x07#8) (0x30#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x00300793#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_addi_char (0x003#12) (regidx.Regidx 0x00#5) (regidx.Regidx 0x0f#5) (0#64)
      (afterNextPC (afterPrelude σ) (0x8001f810#64))
      (sigma3_alu σ (0x8001f810#64) Register.x15 ((0#64) + sign_extend (m := 64) (0x003#12)))
      (rX_bits_zero _)
      (wX_bits_x15 _ ((0#64) + sign_extend (m := 64) (0x003#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f814: `addi x27,x27,0x8`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f814 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v27 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx27 : σ.regs.get? Register.x27 = some v27)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f814#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x27
        (v27 + sign_extend (m := 64) (0x008#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f814 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_alu σ i u (0x8001f814#64) vminstret (0x008d8d93#32)
    (instruction.ITYPE (0x008#12, regidx.Regidx 0x1b#5, regidx.Regidx 0x1b#5, iop.ADDI))
    Register.x27 (v27 + sign_extend (m := 64) (0x008#12))
    (0x93#8) (0x8d#8) (0x8d#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x008d8d93#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_addi_char (0x008#12) (regidx.Regidx 0x1b#5) (regidx.Regidx 0x1b#5) v27
      (afterNextPC (afterPrelude σ) (0x8001f814#64))
      (sigma3_alu σ (0x8001f814#64) Register.x27 (v27 + sign_extend (m := 64) (0x008#12)))
      (rX_bits_x27 _ v27
        (by rw [get?_afterNextPC σ (0x8001f814#64) _ (by decide) (by decide)]; exact hx27))
      (wX_bits_x27 _ (v27 + sign_extend (m := 64) (0x008#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f818: `sb x15,0x8(x22)`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f818 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v22 v15 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx22 : σ.regs.get? Register.x22 = some v22)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f818#64 : BitVec 64))
    (hlo : 0x80000000 ≤ (v22 + sign_extend (m := 64) (0x008#12)).toNat)
    (hhiram : (v22 + sign_extend (m := 64) (0x008#12)).toNat + 1 ≤ 0x100000000)
    (hhiwin : tohostAddr + 16 ≤ (v22 + sign_extend (m := 64) (0x008#12)).toNat) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = ((afterNextPC (afterPrelude σ) (0x8001f818#64)).mem.insert
        (v22 + sign_extend (m := 64) (0x008#12)).toNat (stData 1 v15)) ∧
      ReadsLikePost σ' (sigmaPost_store σ pc vminstret
        (((afterNextPC (afterPrelude σ) (0x8001f818#64)).mem.insert (v22 + sign_extend (m := 64) (0x008#12)).toNat (stData 1 v15)))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f818 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_store σ i u (0x8001f818#64) vminstret (0x00fb0423#32)
    (instruction.STORE (0x008#12, regidx.Regidx 0x0f#5, regidx.Regidx 0x16#5, 1))
    (((afterNextPC (afterPrelude σ) (0x8001f818#64)).mem.insert (v22 + sign_extend (m := 64) (0x008#12)).toNat (stData 1 v15)))
    (0x23#8) (0x04#8) (0xfb#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x00fb0423#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (exec_sb σ (0x8001f818#64) (0x008#12) (regidx.Regidx 0x0f#5) (regidx.Regidx 0x16#5)
      v22 v15 hG
      (rX_bits_x22 _ v22
        (by rw [get?_afterNextPC σ (0x8001f818#64) _ (by decide) (by decide)]; exact hx22))
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x8001f818#64) _ (by decide) (by decide)]; exact hx15))
      hlo hhiram hhiwin)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f81c: `j 0x8001bfe4`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f81c (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f81c#64 : BitVec 64))
    (htgt : (pc + sign_extend (m := 64) (0x1fc7c8#21)).toNat % 4 = 0) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_jump_x0 σ pc vminstret (pc + sign_extend (m := 64) (0x1fc7c8#21))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f81c (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_j σ i u (0x8001f81c#64) vminstret (0xfc8fc06f#32) (0x1fc7c8#21)
    (0x6f#8) (0xc0#8) (0x8f#8) (0xfc#8)
    hG hpc hminstret hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) (by decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0xfc8fc06f#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    htgt hi

/-- 0x8001f820: `ld x22,0x0(x23)` — TOTAL (no byte-presence hypothesis). -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f820 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v23 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx23 : σ.regs.get? Register.x23 = some v23)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f820#64 : BitVec 64))
    (hlo : 0x80000000 ≤ (v23 + sign_extend (m := 64) (0x000#12)).toNat)
    (hhiram : (v23 + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ 0x100000000)
    (hhtif : (v23 + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ tohostAddr
      ∨ tohostAddr + 8 ≤ (v23 + sign_extend (m := 64) (0x000#12)).toNat)
    (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x22
        (sign_extend (m := 64)
          (bytesT8 σ.mem (v23 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8)))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f820 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_alu σ i u (0x8001f820#64) vminstret (0x000bbb03#32)
    (instruction.LOAD (0x000#12, regidx.Regidx 0x17#5, regidx.Regidx 0x16#5, false, 8))
    Register.x22 (sign_extend (m := 64) (bytesT8 σ.mem (v23 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8)))
    (0x03#8) (0xbb#8) (0x0b#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x000bbb03#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (exec_ld_ram σ (0x8001f820#64) (0x000#12) (regidx.Regidx 0x17#5) (regidx.Regidx 0x16#5)
      (sigma3_alu σ (0x8001f820#64) Register.x22 (sign_extend (m := 64) (bytesT8 σ.mem (v23 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))))
      v23 hG
      (rX_bits_x23 _ v23
        (by rw [get?_afterNextPC σ (0x8001f820#64) _ (by decide) (by decide)]; exact hx23))
      (wX_bits_x22 _ (sign_extend (m := 64) (bytesT8 σ.mem (v23 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))))
      hlo hhiram hhtif)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f824: `addi x15,x27,0x10`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f824 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v27 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx27 : σ.regs.get? Register.x27 = some v27)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f824#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x15
        (v27 + sign_extend (m := 64) (0x010#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f824 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_alu σ i u (0x8001f824#64) vminstret (0x010d8793#32)
    (instruction.ITYPE (0x010#12, regidx.Regidx 0x1b#5, regidx.Regidx 0x0f#5, iop.ADDI))
    Register.x15 (v27 + sign_extend (m := 64) (0x010#12))
    (0x93#8) (0x87#8) (0x0d#8) (0x01#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x010d8793#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_addi_char (0x010#12) (regidx.Regidx 0x1b#5) (regidx.Regidx 0x0f#5) v27
      (afterNextPC (afterPrelude σ) (0x8001f824#64))
      (sigma3_alu σ (0x8001f824#64) Register.x15 (v27 + sign_extend (m := 64) (0x010#12)))
      (rX_bits_x27 _ v27
        (by rw [get?_afterNextPC σ (0x8001f824#64) _ (by decide) (by decide)]; exact hx27))
      (wX_bits_x15 _ (v27 + sign_extend (m := 64) (0x010#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f828: `add x22,x22,x15`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f828 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v22 v15 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx22 : σ.regs.get? Register.x22 = some v22)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f828#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x22 (v22 + v15)) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f828 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_alu σ i u (0x8001f828#64) vminstret (0x00fb0b33#32)
    (instruction.RTYPE (regidx.Regidx 0x0f#5, regidx.Regidx 0x16#5, regidx.Regidx 0x16#5, rop.ADD))
    Register.x22 (v22 + v15)
    (0x33#8) (0x0b#8) (0xfb#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x00fb0b33#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_rtype_add_char (regidx.Regidx 0x0f#5) (regidx.Regidx 0x16#5) (regidx.Regidx 0x16#5)
      v22 v15 (afterNextPC (afterPrelude σ) (0x8001f828#64))
      (sigma3_alu σ (0x8001f828#64) Register.x22 (v22 + v15))
      (rX_bits_x22 _ v22
        (by rw [get?_afterNextPC σ (0x8001f828#64) _ (by decide) (by decide)]; exact hx22))
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x8001f828#64) _ (by decide) (by decide)]; exact hx15))
      (wX_bits_x22 _ (v22 + v15)))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f82c: `j 0x8001c3dc`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f82c (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f82c#64 : BitVec 64))
    (htgt : (pc + sign_extend (m := 64) (0x1fcbb0#21)).toNat % 4 = 0) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_jump_x0 σ pc vminstret (pc + sign_extend (m := 64) (0x1fcbb0#21))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f82c (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_j σ i u (0x8001f82c#64) vminstret (0xbb1fc06f#32) (0x1fcbb0#21)
    (0x6f#8) (0xc0#8) (0x1f#8) (0xbb#8)
    hG hpc hminstret hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) (by decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0xbb1fc06f#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    htgt hi

/-- 0x8001f830: `lbu x13,0x18(x15)` — TOTAL (no byte-presence hypothesis). -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f830 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v15 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f830#64 : BitVec 64))
    (hlo : 0x80000000 ≤ (v15 + sign_extend (m := 64) (0x018#12)).toNat)
    (hhiram : (v15 + sign_extend (m := 64) (0x018#12)).toNat + 1 ≤ 0x100000000)
    (hhtif : (v15 + sign_extend (m := 64) (0x018#12)).toNat + 1 ≤ tohostAddr
      ∨ tohostAddr + 8 ≤ (v15 + sign_extend (m := 64) (0x018#12)).toNat)
    (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x13 (zero_extend (m := 64) (bytesT1 σ.mem (v15 + sign_extend (m := 64) (0x018#12)).toNat : BitVec (8 * 1)))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f830 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_alu σ i u (0x8001f830#64) vminstret (0x0187c683#32)
    (instruction.LOAD (0x018#12, regidx.Regidx 0x0f#5, regidx.Regidx 0x0d#5, true, 1))
    Register.x13 (zero_extend (m := 64) (bytesT1 σ.mem (v15 + sign_extend (m := 64) (0x018#12)).toNat : BitVec (8 * 1)))
    (0x83#8) (0xc6#8) (0x87#8) (0x01#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x0187c683#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (exec_lbu_tot σ (0x8001f830#64) (0x018#12) (regidx.Regidx 0x0f#5) (regidx.Regidx 0x0d#5)
      (sigma3_alu σ (0x8001f830#64) Register.x13 (zero_extend (m := 64) (bytesT1 σ.mem (v15 + sign_extend (m := 64) (0x018#12)).toNat : BitVec (8 * 1))))
      v15 hG
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x8001f830#64) _ (by decide) (by decide)]; exact hx15))
      (wX_bits_x13 _ (zero_extend (m := 64) (bytesT1 σ.mem (v15 + sign_extend (m := 64) (0x018#12)).toNat : BitVec (8 * 1))))
      hlo hhiram hhtif)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f834: `addi x14,x0,0x13`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f834 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f834#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x14
        ((0#64) + sign_extend (m := 64) (0x013#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f834 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_alu σ i u (0x8001f834#64) vminstret (0x01300713#32)
    (instruction.ITYPE (0x013#12, regidx.Regidx 0x00#5, regidx.Regidx 0x0e#5, iop.ADDI))
    Register.x14 ((0#64) + sign_extend (m := 64) (0x013#12))
    (0x13#8) (0x07#8) (0x30#8) (0x01#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x01300713#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_addi_char (0x013#12) (regidx.Regidx 0x00#5) (regidx.Regidx 0x0e#5) (0#64)
      (afterNextPC (afterPrelude σ) (0x8001f834#64))
      (sigma3_alu σ (0x8001f834#64) Register.x14 ((0#64) + sign_extend (m := 64) (0x013#12)))
      (rX_bits_zero _)
      (wX_bits_x14 _ ((0#64) + sign_extend (m := 64) (0x013#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f838: `bne x13,x14` (NOT taken). -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f838_nottaken (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v13 v14 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx13 : σ.regs.get? Register.x13 = some v13)
    (hx14 : σ.regs.get? Register.x14 = some v14)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f838#64 : BitVec 64))
    (hv : (v13 != v14) = false) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_branch_nottaken σ pc vminstret) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f838 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_branch_nottaken σ i u (0x8001f838#64) vminstret (0x01b8#13)
    (regidx.Regidx 0x0d#5) (regidx.Regidx 0x0e#5) bop.BNE (0x1ae69c63#32)
    (0x63#8) (0x9c#8) (0xe6#8) (0x1a#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x1ae69c63#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_btype_bne_nottaken (0x01b8#13) (regidx.Regidx 0x0d#5) (regidx.Regidx 0x0e#5)
      v13 v14 (afterNextPC (afterPrelude σ) (0x8001f838#64))
      (rX_bits_x13 _ v13
        (by rw [get?_afterNextPC σ (0x8001f838#64) _ (by decide) (by decide)]; exact hx13))
      (rX_bits_x14 _ v14
        (by rw [get?_afterNextPC σ (0x8001f838#64) _ (by decide) (by decide)]; exact hx14))
      hv)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- Branch target of the taken site at 0x8001f838. -/
-- discipline: allow(R1-site-battery) machine-emitted by scripts/gen_sites.py
theorem site_8001f838_taken_tgt :
    (0x8001f838#64 + sign_extend (m := 64) (0x01b8#13)) = (0x8001f9f0#64 : BitVec 64) := by
  apply BitVec.eq_of_toNat_eq; decide

/-- 0x8001f838: `bne x13,x14 → 0x8001f9f0` (TAKEN). -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f838_taken (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v13 v14 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx13 : σ.regs.get? Register.x13 = some v13)
    (hx14 : σ.regs.get? Register.x14 = some v14)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f838#64 : BitVec 64))
    (hv : (v13 != v14) = true) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_branch_taken σ pc vminstret (0x01b8#13)) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f838 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_branch_taken σ i u (0x8001f838#64) vminstret (0x01b8#13)
    (regidx.Regidx 0x0d#5) (regidx.Regidx 0x0e#5) bop.BNE (0x1ae69c63#32)
    (0x63#8) (0x9c#8) (0xe6#8) (0x1a#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x1ae69c63#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_btype_bne_taken (0x01b8#13) (regidx.Regidx 0x0d#5) (regidx.Regidx 0x0e#5)
      v13 v14 (0x8001f838#64) initMisa (afterNextPC (afterPrelude σ) (0x8001f838#64))
      (rX_bits_x13 _ v13
        (by rw [get?_afterNextPC σ (0x8001f838#64) _ (by decide) (by decide)]; exact hx13))
      (rX_bits_x14 _ v14
        (by rw [get?_afterNextPC σ (0x8001f838#64) _ (by decide) (by decide)]; exact hx14))
      (by rw [get?_afterNextPC σ (0x8001f838#64) _ (by decide) (by decide)]; exact hpc)
      (by rw [get?_afterNextPC σ (0x8001f838#64) _ (by decide) (by decide)]; exact hG.misa)
      (by rw [site_8001f838_taken_tgt]; decide) hv)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f83c: `ld x10,0x10(x15)` — TOTAL (no byte-presence hypothesis). -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f83c (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v15 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f83c#64 : BitVec 64))
    (hlo : 0x80000000 ≤ (v15 + sign_extend (m := 64) (0x010#12)).toNat)
    (hhiram : (v15 + sign_extend (m := 64) (0x010#12)).toNat + 8 ≤ 0x100000000)
    (hhtif : (v15 + sign_extend (m := 64) (0x010#12)).toNat + 8 ≤ tohostAddr
      ∨ tohostAddr + 8 ≤ (v15 + sign_extend (m := 64) (0x010#12)).toNat)
    (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x10
        (sign_extend (m := 64)
          (bytesT8 σ.mem (v15 + sign_extend (m := 64) (0x010#12)).toNat : BitVec (8 * 8)))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f83c (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_alu σ i u (0x8001f83c#64) vminstret (0x0107b503#32)
    (instruction.LOAD (0x010#12, regidx.Regidx 0x0f#5, regidx.Regidx 0x0a#5, false, 8))
    Register.x10 (sign_extend (m := 64) (bytesT8 σ.mem (v15 + sign_extend (m := 64) (0x010#12)).toNat : BitVec (8 * 8)))
    (0x03#8) (0xb5#8) (0x07#8) (0x01#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x0107b503#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (exec_ld_ram σ (0x8001f83c#64) (0x010#12) (regidx.Regidx 0x0f#5) (regidx.Regidx 0x0a#5)
      (sigma3_alu σ (0x8001f83c#64) Register.x10 (sign_extend (m := 64) (bytesT8 σ.mem (v15 + sign_extend (m := 64) (0x010#12)).toNat : BitVec (8 * 8))))
      v15 hG
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x8001f83c#64) _ (by decide) (by decide)]; exact hx15))
      (wX_bits_x10 _ (sign_extend (m := 64) (bytesT8 σ.mem (v15 + sign_extend (m := 64) (0x010#12)).toNat : BitVec (8 * 8))))
      hlo hhiram hhtif)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f840: `addi x11,x0,0x0`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f840 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f840#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x11
        ((0#64) + sign_extend (m := 64) (0x000#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f840 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_alu σ i u (0x8001f840#64) vminstret (0x00000593#32)
    (instruction.ITYPE (0x000#12, regidx.Regidx 0x00#5, regidx.Regidx 0x0b#5, iop.ADDI))
    Register.x11 ((0#64) + sign_extend (m := 64) (0x000#12))
    (0x93#8) (0x05#8) (0x00#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x00000593#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_addi_char (0x000#12) (regidx.Regidx 0x00#5) (regidx.Regidx 0x0b#5) (0#64)
      (afterNextPC (afterPrelude σ) (0x8001f840#64))
      (sigma3_alu σ (0x8001f840#64) Register.x11 ((0#64) + sign_extend (m := 64) (0x000#12)))
      (rX_bits_zero _)
      (wX_bits_x11 _ ((0#64) + sign_extend (m := 64) (0x000#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f844: `sd x15,0x10(x2)`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f844 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v2 v15 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx2 : σ.regs.get? Register.x2 = some v2)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f844#64 : BitVec 64))
    (halo : 0x80000000 ≤ (v2 + sign_extend (m := 64) (0x010#12)).toNat)
    (hahiram : (v2 + sign_extend (m := 64) (0x010#12)).toNat + 8 ≤ 0x100000000)
    (hahiwin : tohostAddr + 16 ≤ (v2 + sign_extend (m := 64) (0x010#12)).toNat)
    (haalign : (v2 + sign_extend (m := 64) (0x010#12)).toNat % 8 = 0) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = writeMap8 (afterNextPC (afterPrelude σ) (0x8001f844#64)).mem
        (v2 + sign_extend (m := 64) (0x010#12)).toNat (sdData_val v15) ∧
      ReadsLikePost σ' (sigmaPost_store σ pc vminstret
        (writeMap8 (afterNextPC (afterPrelude σ) (0x8001f844#64)).mem (v2 + sign_extend (m := 64) (0x010#12)).toNat (sdData_val v15))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f844 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_store σ i u (0x8001f844#64) vminstret (0x00f13823#32)
    (instruction.STORE (0x010#12, regidx.Regidx 0x0f#5, regidx.Regidx 0x02#5, 8))
    (writeMap8 (afterNextPC (afterPrelude σ) (0x8001f844#64)).mem (v2 + sign_extend (m := 64) (0x010#12)).toNat (sdData_val v15))
    (0x23#8) (0x38#8) (0xf1#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x00f13823#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (exec_sd_val σ (0x8001f844#64) (0x010#12) (regidx.Regidx 0x0f#5) (regidx.Regidx 0x02#5)
      v2 v15 hG
      (rX_bits_x2 _ v2
        (by rw [get?_afterNextPC σ (0x8001f844#64) _ (by decide) (by decide)]; exact hx2))
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x8001f844#64) _ (by decide) (by decide)]; exact hx15))
      halo hahiram hahiwin haalign)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f848: `jal x1,0x8002e3c0` (link `x1 := 0x8001f84c`). -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f848 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f848#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_jal σ pc vminstret (0x00eb78#21) Register.x1 (BitVec.addInt pc 4)) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f848 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  refine stepObs_jal σ i u (0x8001f848#64) vminstret (0x3790e0ef#32) (0x00eb78#21)
    (regidx.Regidx 0x01#5) Register.x1 (BitVec.addInt (0x8001f848#64) 4)
    (0xef#8) (0xe0#8) (0x90#8) (0x37#8)
    hG hpc hminstret hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide)
    (by apply BitVec.eq_of_toNat_eq; decide) (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x3790e0ef#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (by decide)
    (by decide) (by decide) (by decide) (by decide) (by decide) ?_ hi
  exact wX_bits_x1 _ (BitVec.addInt (0x8001f848#64) 4)

/-- 0x8001f84c: `ld x15,0x10(x2)` — TOTAL (no byte-presence hypothesis). -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f84c (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v2 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx2 : σ.regs.get? Register.x2 = some v2)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f84c#64 : BitVec 64))
    (hlo : 0x80000000 ≤ (v2 + sign_extend (m := 64) (0x010#12)).toNat)
    (hhiram : (v2 + sign_extend (m := 64) (0x010#12)).toNat + 8 ≤ 0x100000000)
    (hhtif : (v2 + sign_extend (m := 64) (0x010#12)).toNat + 8 ≤ tohostAddr
      ∨ tohostAddr + 8 ≤ (v2 + sign_extend (m := 64) (0x010#12)).toNat)
    (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x15
        (sign_extend (m := 64)
          (bytesT8 σ.mem (v2 + sign_extend (m := 64) (0x010#12)).toNat : BitVec (8 * 8)))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f84c (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_alu σ i u (0x8001f84c#64) vminstret (0x01013783#32)
    (instruction.LOAD (0x010#12, regidx.Regidx 0x02#5, regidx.Regidx 0x0f#5, false, 8))
    Register.x15 (sign_extend (m := 64) (bytesT8 σ.mem (v2 + sign_extend (m := 64) (0x010#12)).toNat : BitVec (8 * 8)))
    (0x83#8) (0x37#8) (0x01#8) (0x01#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x01013783#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (exec_ld_ram σ (0x8001f84c#64) (0x010#12) (regidx.Regidx 0x02#5) (regidx.Regidx 0x0f#5)
      (sigma3_alu σ (0x8001f84c#64) Register.x15 (sign_extend (m := 64) (bytesT8 σ.mem (v2 + sign_extend (m := 64) (0x010#12)).toNat : BitVec (8 * 8))))
      v2 hG
      (rX_bits_x2 _ v2
        (by rw [get?_afterNextPC σ (0x8001f84c#64) _ (by decide) (by decide)]; exact hx2))
      (wX_bits_x15 _ (sign_extend (m := 64) (bytesT8 σ.mem (v2 + sign_extend (m := 64) (0x010#12)).toNat : BitVec (8 * 8))))
      hlo hhiram hhtif)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f850: `blt x0,x10` (NOT taken). -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f850_nottaken (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v10 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx10 : σ.regs.get? Register.x10 = some v10)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f850#64 : BitVec 64))
    (hv : zopz0zI_s (0#64) v10 = false) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_branch_nottaken σ pc vminstret) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f850 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_branch_nottaken σ i u (0x8001f850#64) vminstret (0x0008#13)
    (regidx.Regidx 0x00#5) (regidx.Regidx 0x0a#5) bop.BLT (0x00a04463#32)
    (0x63#8) (0x44#8) (0xa0#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x00a04463#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_btype_blt_nottaken (0x0008#13) (regidx.Regidx 0x00#5) (regidx.Regidx 0x0a#5)
      (0#64) v10 (afterNextPC (afterPrelude σ) (0x8001f850#64))
      (rX_bits_zero _)
      (rX_bits_x10 _ v10
        (by rw [get?_afterNextPC σ (0x8001f850#64) _ (by decide) (by decide)]; exact hx10))
      hv)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- Branch target of the taken site at 0x8001f850. -/
-- discipline: allow(R1-site-battery) machine-emitted by scripts/gen_sites.py
theorem site_8001f850_taken_tgt :
    (0x8001f850#64 + sign_extend (m := 64) (0x0008#13)) = (0x8001f858#64 : BitVec 64) := by
  apply BitVec.eq_of_toNat_eq; decide

/-- 0x8001f850: `blt x0,x10 → 0x8001f858` (TAKEN). -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f850_taken (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v10 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx10 : σ.regs.get? Register.x10 = some v10)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f850#64 : BitVec 64))
    (hv : zopz0zI_s (0#64) v10 = true) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_branch_taken σ pc vminstret (0x0008#13)) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f850 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_branch_taken σ i u (0x8001f850#64) vminstret (0x0008#13)
    (regidx.Regidx 0x00#5) (regidx.Regidx 0x0a#5) bop.BLT (0x00a04463#32)
    (0x63#8) (0x44#8) (0xa0#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x00a04463#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_btype_blt_taken (0x0008#13) (regidx.Regidx 0x00#5) (regidx.Regidx 0x0a#5)
      (0#64) v10 (0x8001f850#64) initMisa (afterNextPC (afterPrelude σ) (0x8001f850#64))
      (rX_bits_zero _)
      (rX_bits_x10 _ v10
        (by rw [get?_afterNextPC σ (0x8001f850#64) _ (by decide) (by decide)]; exact hx10))
      (by rw [get?_afterNextPC σ (0x8001f850#64) _ (by decide) (by decide)]; exact hpc)
      (by rw [get?_afterNextPC σ (0x8001f850#64) _ (by decide) (by decide)]; exact hG.misa)
      (by rw [site_8001f850_taken_tgt]; decide) hv)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f854: `j 0x8001e218`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f854 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f854#64 : BitVec 64))
    (htgt : (pc + sign_extend (m := 64) (0x1fe9c4#21)).toNat % 4 = 0) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_jump_x0 σ pc vminstret (pc + sign_extend (m := 64) (0x1fe9c4#21))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f854 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_j σ i u (0x8001f854#64) vminstret (0x9c5fe06f#32) (0x1fe9c4#21)
    (0x6f#8) (0xe0#8) (0x5f#8) (0x9c#8)
    hG hpc hminstret hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) (by decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x9c5fe06f#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    htgt hi

/-- 0x8001f858: `addi x10,x0,0xfff`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f858 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f858#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x10
        ((0#64) + sign_extend (m := 64) (0xfff#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f858 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_alu σ i u (0x8001f858#64) vminstret (0xfff00513#32)
    (instruction.ITYPE (0xfff#12, regidx.Regidx 0x00#5, regidx.Regidx 0x0a#5, iop.ADDI))
    Register.x10 ((0#64) + sign_extend (m := 64) (0xfff#12))
    (0x13#8) (0x05#8) (0xf0#8) (0xff#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0xfff00513#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_addi_char (0xfff#12) (regidx.Regidx 0x00#5) (regidx.Regidx 0x0a#5) (0#64)
      (afterNextPC (afterPrelude σ) (0x8001f858#64))
      (sigma3_alu σ (0x8001f858#64) Register.x10 ((0#64) + sign_extend (m := 64) (0xfff#12)))
      (rX_bits_zero _)
      (wX_bits_x10 _ ((0#64) + sign_extend (m := 64) (0xfff#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f85c: `srli x10,x10,1`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f85c (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v10 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx10 : σ.regs.get? Register.x10 = some v10)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f85c#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x10 (shift_bits_right v10 (Sail.BitVec.extractLsb (0x01#6) 5 0))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f85c (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_alu σ i u (0x8001f85c#64) vminstret (0x00155513#32)
    (instruction.SHIFTIOP (0x01#6, regidx.Regidx 0x0a#5, regidx.Regidx 0x0a#5, sop.SRLI))
    Register.x10 (shift_bits_right v10 (Sail.BitVec.extractLsb (0x01#6) 5 0))
    (0x13#8) (0x55#8) (0x15#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x00155513#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_shiftiop_srli_char (0x01#6) (regidx.Regidx 0x0a#5) (regidx.Regidx 0x0a#5) v10
      (afterNextPC (afterPrelude σ) (0x8001f85c#64))
      (sigma3_alu σ (0x8001f85c#64) Register.x10 (shift_bits_right v10 (Sail.BitVec.extractLsb (0x01#6) 5 0)))
      (rX_bits_x10 _ v10
        (by rw [get?_afterNextPC σ (0x8001f85c#64) _ (by decide) (by decide)]; exact hx10))
      (wX_bits_x10 _ (shift_bits_right v10 (Sail.BitVec.extractLsb (0x01#6) 5 0))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f860: `addi x11,x22,0x0`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f860 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v22 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx22 : σ.regs.get? Register.x22 = some v22)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f860#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x11
        (v22 + sign_extend (m := 64) (0x000#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f860 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_alu σ i u (0x8001f860#64) vminstret (0x000b0593#32)
    (instruction.ITYPE (0x000#12, regidx.Regidx 0x16#5, regidx.Regidx 0x0b#5, iop.ADDI))
    Register.x11 (v22 + sign_extend (m := 64) (0x000#12))
    (0x93#8) (0x05#8) (0x0b#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x000b0593#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_addi_char (0x000#12) (regidx.Regidx 0x16#5) (regidx.Regidx 0x0b#5) v22
      (afterNextPC (afterPrelude σ) (0x8001f860#64))
      (sigma3_alu σ (0x8001f860#64) Register.x11 (v22 + sign_extend (m := 64) (0x000#12)))
      (rX_bits_x22 _ v22
        (by rw [get?_afterNextPC σ (0x8001f860#64) _ (by decide) (by decide)]; exact hx22))
      (wX_bits_x11 _ (v22 + sign_extend (m := 64) (0x000#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f864: `sub x10,x10,x26`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f864 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v10 v26 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx10 : σ.regs.get? Register.x10 = some v10)
    (hx26 : σ.regs.get? Register.x26 = some v26)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f864#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x10 (v10 - v26)) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f864 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_alu σ i u (0x8001f864#64) vminstret (0x41a50533#32)
    (instruction.RTYPE (regidx.Regidx 0x1a#5, regidx.Regidx 0x0a#5, regidx.Regidx 0x0a#5, rop.SUB))
    Register.x10 (v10 - v26)
    (0x33#8) (0x05#8) (0xa5#8) (0x41#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x41a50533#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_rtype_sub_char (regidx.Regidx 0x1a#5) (regidx.Regidx 0x0a#5) (regidx.Regidx 0x0a#5)
      v10 v26 (afterNextPC (afterPrelude σ) (0x8001f864#64))
      (sigma3_alu σ (0x8001f864#64) Register.x10 (v10 - v26))
      (rX_bits_x10 _ v10
        (by rw [get?_afterNextPC σ (0x8001f864#64) _ (by decide) (by decide)]; exact hx10))
      (rX_bits_x26 _ v26
        (by rw [get?_afterNextPC σ (0x8001f864#64) _ (by decide) (by decide)]; exact hx26))
      (wX_bits_x10 _ (v10 - v26)))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f868: `sd x15,0x10(x2)`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f868 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v2 v15 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx2 : σ.regs.get? Register.x2 = some v2)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f868#64 : BitVec 64))
    (halo : 0x80000000 ≤ (v2 + sign_extend (m := 64) (0x010#12)).toNat)
    (hahiram : (v2 + sign_extend (m := 64) (0x010#12)).toNat + 8 ≤ 0x100000000)
    (hahiwin : tohostAddr + 16 ≤ (v2 + sign_extend (m := 64) (0x010#12)).toNat)
    (haalign : (v2 + sign_extend (m := 64) (0x010#12)).toNat % 8 = 0) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = writeMap8 (afterNextPC (afterPrelude σ) (0x8001f868#64)).mem
        (v2 + sign_extend (m := 64) (0x010#12)).toNat (sdData_val v15) ∧
      ReadsLikePost σ' (sigmaPost_store σ pc vminstret
        (writeMap8 (afterNextPC (afterPrelude σ) (0x8001f868#64)).mem (v2 + sign_extend (m := 64) (0x010#12)).toNat (sdData_val v15))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f868 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_store σ i u (0x8001f868#64) vminstret (0x00f13823#32)
    (instruction.STORE (0x010#12, regidx.Regidx 0x0f#5, regidx.Regidx 0x02#5, 8))
    (writeMap8 (afterNextPC (afterPrelude σ) (0x8001f868#64)).mem (v2 + sign_extend (m := 64) (0x010#12)).toNat (sdData_val v15))
    (0x23#8) (0x38#8) (0xf1#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x00f13823#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (exec_sd_val σ (0x8001f868#64) (0x010#12) (regidx.Regidx 0x0f#5) (regidx.Regidx 0x02#5)
      v2 v15 hG
      (rX_bits_x2 _ v2
        (by rw [get?_afterNextPC σ (0x8001f868#64) _ (by decide) (by decide)]; exact hx2))
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x8001f868#64) _ (by decide) (by decide)]; exact hx15))
      halo hahiram hahiwin haalign)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f86c: `jal x1,0x8002f734` (link `x1 := 0x8001f870`). -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f86c (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f86c#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_jal σ pc vminstret (0x00fec8#21) Register.x1 (BitVec.addInt pc 4)) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f86c (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  refine stepObs_jal σ i u (0x8001f86c#64) vminstret (0x6c90f0ef#32) (0x00fec8#21)
    (regidx.Regidx 0x01#5) Register.x1 (BitVec.addInt (0x8001f86c#64) 4)
    (0xef#8) (0xf0#8) (0x90#8) (0x6c#8)
    hG hpc hminstret hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide)
    (by apply BitVec.eq_of_toNat_eq; decide) (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x6c90f0ef#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (by decide)
    (by decide) (by decide) (by decide) (by decide) (by decide) ?_ hi
  exact wX_bits_x1 _ (BitVec.addInt (0x8001f86c#64) 4)

/-- 0x8001f870: `ld x15,0x10(x2)` — TOTAL (no byte-presence hypothesis). -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f870 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v2 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx2 : σ.regs.get? Register.x2 = some v2)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f870#64 : BitVec 64))
    (hlo : 0x80000000 ≤ (v2 + sign_extend (m := 64) (0x010#12)).toNat)
    (hhiram : (v2 + sign_extend (m := 64) (0x010#12)).toNat + 8 ≤ 0x100000000)
    (hhtif : (v2 + sign_extend (m := 64) (0x010#12)).toNat + 8 ≤ tohostAddr
      ∨ tohostAddr + 8 ≤ (v2 + sign_extend (m := 64) (0x010#12)).toNat)
    (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x15
        (sign_extend (m := 64)
          (bytesT8 σ.mem (v2 + sign_extend (m := 64) (0x010#12)).toNat : BitVec (8 * 8)))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f870 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_alu σ i u (0x8001f870#64) vminstret (0x01013783#32)
    (instruction.LOAD (0x010#12, regidx.Regidx 0x02#5, regidx.Regidx 0x0f#5, false, 8))
    Register.x15 (sign_extend (m := 64) (bytesT8 σ.mem (v2 + sign_extend (m := 64) (0x010#12)).toNat : BitVec (8 * 8)))
    (0x83#8) (0x37#8) (0x01#8) (0x01#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x01013783#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (exec_ld_ram σ (0x8001f870#64) (0x010#12) (regidx.Regidx 0x02#5) (regidx.Regidx 0x0f#5)
      (sigma3_alu σ (0x8001f870#64) Register.x15 (sign_extend (m := 64) (bytesT8 σ.mem (v2 + sign_extend (m := 64) (0x010#12)).toNat : BitVec (8 * 8))))
      v2 hG
      (rX_bits_x2 _ v2
        (by rw [get?_afterNextPC σ (0x8001f870#64) _ (by decide) (by decide)]; exact hx2))
      (wX_bits_x15 _ (sign_extend (m := 64) (bytesT8 σ.mem (v2 + sign_extend (m := 64) (0x010#12)).toNat : BitVec (8 * 8))))
      hlo hhiram hhtif)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f874: `addi x14,x10,0x0`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f874 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v10 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx10 : σ.regs.get? Register.x10 = some v10)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f874#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x14
        (v10 + sign_extend (m := 64) (0x000#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f874 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_alu σ i u (0x8001f874#64) vminstret (0x00050713#32)
    (instruction.ITYPE (0x000#12, regidx.Regidx 0x0a#5, regidx.Regidx 0x0e#5, iop.ADDI))
    Register.x14 (v10 + sign_extend (m := 64) (0x000#12))
    (0x13#8) (0x07#8) (0x05#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x00050713#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_addi_char (0x000#12) (regidx.Regidx 0x0a#5) (regidx.Regidx 0x0e#5) v10
      (afterNextPC (afterPrelude σ) (0x8001f874#64))
      (sigma3_alu σ (0x8001f874#64) Register.x14 (v10 + sign_extend (m := 64) (0x000#12)))
      (rX_bits_x10 _ v10
        (by rw [get?_afterNextPC σ (0x8001f874#64) _ (by decide) (by decide)]; exact hx10))
      (wX_bits_x14 _ (v10 + sign_extend (m := 64) (0x000#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f878: `sd x14,0x10(x15)`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f878 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v15 v14 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hx14 : σ.regs.get? Register.x14 = some v14)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f878#64 : BitVec 64))
    (halo : 0x80000000 ≤ (v15 + sign_extend (m := 64) (0x010#12)).toNat)
    (hahiram : (v15 + sign_extend (m := 64) (0x010#12)).toNat + 8 ≤ 0x100000000)
    (hahiwin : tohostAddr + 16 ≤ (v15 + sign_extend (m := 64) (0x010#12)).toNat)
    (haalign : (v15 + sign_extend (m := 64) (0x010#12)).toNat % 8 = 0) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = writeMap8 (afterNextPC (afterPrelude σ) (0x8001f878#64)).mem
        (v15 + sign_extend (m := 64) (0x010#12)).toNat (sdData_val v14) ∧
      ReadsLikePost σ' (sigmaPost_store σ pc vminstret
        (writeMap8 (afterNextPC (afterPrelude σ) (0x8001f878#64)).mem (v15 + sign_extend (m := 64) (0x010#12)).toNat (sdData_val v14))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f878 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_store σ i u (0x8001f878#64) vminstret (0x00e7b823#32)
    (instruction.STORE (0x010#12, regidx.Regidx 0x0e#5, regidx.Regidx 0x0f#5, 8))
    (writeMap8 (afterNextPC (afterPrelude σ) (0x8001f878#64)).mem (v15 + sign_extend (m := 64) (0x010#12)).toNat (sdData_val v14))
    (0x23#8) (0xb8#8) (0xe7#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x00e7b823#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (exec_sd_val σ (0x8001f878#64) (0x010#12) (regidx.Regidx 0x0e#5) (regidx.Regidx 0x0f#5)
      v15 v14 hG
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x8001f878#64) _ (by decide) (by decide)]; exact hx15))
      (rX_bits_x14 _ v14
        (by rw [get?_afterNextPC σ (0x8001f878#64) _ (by decide) (by decide)]; exact hx14))
      halo hahiram hahiwin haalign)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f87c: `addi x14,x0,0x3`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f87c (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f87c#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x14
        ((0#64) + sign_extend (m := 64) (0x003#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f87c (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_alu σ i u (0x8001f87c#64) vminstret (0x00300713#32)
    (instruction.ITYPE (0x003#12, regidx.Regidx 0x00#5, regidx.Regidx 0x0e#5, iop.ADDI))
    Register.x14 ((0#64) + sign_extend (m := 64) (0x003#12))
    (0x13#8) (0x07#8) (0x30#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x00300713#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_addi_char (0x003#12) (regidx.Regidx 0x00#5) (regidx.Regidx 0x0e#5) (0#64)
      (afterNextPC (afterPrelude σ) (0x8001f87c#64))
      (sigma3_alu σ (0x8001f87c#64) Register.x14 ((0#64) + sign_extend (m := 64) (0x003#12)))
      (rX_bits_zero _)
      (wX_bits_x14 _ ((0#64) + sign_extend (m := 64) (0x003#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f880: `sb x14,0x18(x15)`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f880 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v15 v14 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hx14 : σ.regs.get? Register.x14 = some v14)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f880#64 : BitVec 64))
    (hlo : 0x80000000 ≤ (v15 + sign_extend (m := 64) (0x018#12)).toNat)
    (hhiram : (v15 + sign_extend (m := 64) (0x018#12)).toNat + 1 ≤ 0x100000000)
    (hhiwin : tohostAddr + 16 ≤ (v15 + sign_extend (m := 64) (0x018#12)).toNat) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = ((afterNextPC (afterPrelude σ) (0x8001f880#64)).mem.insert
        (v15 + sign_extend (m := 64) (0x018#12)).toNat (stData 1 v14)) ∧
      ReadsLikePost σ' (sigmaPost_store σ pc vminstret
        (((afterNextPC (afterPrelude σ) (0x8001f880#64)).mem.insert (v15 + sign_extend (m := 64) (0x018#12)).toNat (stData 1 v14)))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f880 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_store σ i u (0x8001f880#64) vminstret (0x00e78c23#32)
    (instruction.STORE (0x018#12, regidx.Regidx 0x0e#5, regidx.Regidx 0x0f#5, 1))
    (((afterNextPC (afterPrelude σ) (0x8001f880#64)).mem.insert (v15 + sign_extend (m := 64) (0x018#12)).toNat (stData 1 v14)))
    (0x23#8) (0x8c#8) (0xe7#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x00e78c23#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (exec_sb σ (0x8001f880#64) (0x018#12) (regidx.Regidx 0x0e#5) (regidx.Regidx 0x0f#5)
      v15 v14 hG
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x8001f880#64) _ (by decide) (by decide)]; exact hx15))
      (rX_bits_x14 _ v14
        (by rw [get?_afterNextPC σ (0x8001f880#64) _ (by decide) (by decide)]; exact hx14))
      hlo hhiram hhiwin)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f884: `addi x27,x19,0x0`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f884 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v19 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx19 : σ.regs.get? Register.x19 = some v19)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f884#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x27
        (v19 + sign_extend (m := 64) (0x000#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f884 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_alu σ i u (0x8001f884#64) vminstret (0x00098d93#32)
    (instruction.ITYPE (0x000#12, regidx.Regidx 0x13#5, regidx.Regidx 0x1b#5, iop.ADDI))
    Register.x27 (v19 + sign_extend (m := 64) (0x000#12))
    (0x93#8) (0x8d#8) (0x09#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x00098d93#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_addi_char (0x000#12) (regidx.Regidx 0x13#5) (regidx.Regidx 0x1b#5) v19
      (afterNextPC (afterPrelude σ) (0x8001f884#64))
      (sigma3_alu σ (0x8001f884#64) Register.x27 (v19 + sign_extend (m := 64) (0x000#12)))
      (rX_bits_x19 _ v19
        (by rw [get?_afterNextPC σ (0x8001f884#64) _ (by decide) (by decide)]; exact hx19))
      (wX_bits_x27 _ (v19 + sign_extend (m := 64) (0x000#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f888: `j 0x8001bfe4`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f888 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f888#64 : BitVec 64))
    (htgt : (pc + sign_extend (m := 64) (0x1fc75c#21)).toNat % 4 = 0) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_jump_x0 σ pc vminstret (pc + sign_extend (m := 64) (0x1fc75c#21))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f888 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_j σ i u (0x8001f888#64) vminstret (0xf5cfc06f#32) (0x1fc75c#21)
    (0x6f#8) (0xc0#8) (0xcf#8) (0xf5#8)
    hG hpc hminstret hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) (by decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0xf5cfc06f#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    htgt hi

/-- 0x8001f88c: `addi x10,x26,0x0`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f88c (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v26 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx26 : σ.regs.get? Register.x26 = some v26)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f88c#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x10
        (v26 + sign_extend (m := 64) (0x000#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f88c (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_alu σ i u (0x8001f88c#64) vminstret (0x000d0513#32)
    (instruction.ITYPE (0x000#12, regidx.Regidx 0x1a#5, regidx.Regidx 0x0a#5, iop.ADDI))
    Register.x10 (v26 + sign_extend (m := 64) (0x000#12))
    (0x13#8) (0x05#8) (0x0d#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x000d0513#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_addi_char (0x000#12) (regidx.Regidx 0x1a#5) (regidx.Regidx 0x0a#5) v26
      (afterNextPC (afterPrelude σ) (0x8001f88c#64))
      (sigma3_alu σ (0x8001f88c#64) Register.x10 (v26 + sign_extend (m := 64) (0x000#12)))
      (rX_bits_x26 _ v26
        (by rw [get?_afterNextPC σ (0x8001f88c#64) _ (by decide) (by decide)]; exact hx26))
      (wX_bits_x10 _ (v26 + sign_extend (m := 64) (0x000#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8001f890: `jal x1,0x8002bb14` (link `x1 := 0x8001f894`). -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f890 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f890#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_jal σ pc vminstret (0x00c284#21) Register.x1 (BitVec.addInt pc 4)) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f890 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  refine stepObs_jal σ i u (0x8001f890#64) vminstret (0x2840c0ef#32) (0x00c284#21)
    (regidx.Regidx 0x01#5) Register.x1 (BitVec.addInt (0x8001f890#64) 4)
    (0xef#8) (0xc0#8) (0x40#8) (0x28#8)
    hG hpc hminstret hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide)
    (by apply BitVec.eq_of_toNat_eq; decide) (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x2840c0ef#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (by decide)
    (by decide) (by decide) (by decide) (by decide) (by decide) ?_ hi
  exact wX_bits_x1 _ (BitVec.addInt (0x8001f890#64) 4)

/-- 0x8001f894: `addi x22,x10,0x0`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8001f894 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v10 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx10 : σ.regs.get? Register.x10 = some v10)
    (hmem : Lua.Vm.Arms.TextLoaded σ.mem)
    (hpcv : pc = (0x8001f894#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x22
        (v10 + sign_extend (m := 64) (0x000#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Lua.Vm.Code.luaV_execute_at_8001f894 (Lua.Vm.Code.textLoaded_LuaV_execute_p14Loaded hmem)
  exact stepObs_alu σ i u (0x8001f894#64) vminstret (0x00050b13#32)
    (instruction.ITYPE (0x000#12, regidx.Regidx 0x0a#5, regidx.Regidx 0x16#5, iop.ADDI))
    Register.x22 (v10 + sign_extend (m := 64) (0x000#12))
    (0x13#8) (0x0b#8) (0x05#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.decodeW (w := 0x00050b13#32) (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_addi_char (0x000#12) (regidx.Regidx 0x0a#5) (regidx.Regidx 0x16#5) v10
      (afterNextPC (afterPrelude σ) (0x8001f894#64))
      (sigma3_alu σ (0x8001f894#64) Register.x22 (v10 + sign_extend (m := 64) (0x000#12)))
      (rX_bits_x10 _ v10
        (by rw [get?_afterNextPC σ (0x8001f894#64) _ (by decide) (by decide)]; exact hx10))
      (wX_bits_x22 _ (v10 + sign_extend (m := 64) (0x000#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

end Lua.Vm.Arms
