/-! GENERATED by scripts/gen_lua_layout.py -- do not edit.

C layout of Lua 5.4.7's VM structures in the bare-metal ELF
(`riscv-none-elf-gcc (xPack GNU RISC-V Embedded GCC x86_64) 15.2.0`, rv64i lp64 medany),
read from the cross compiler's own `offsetof`/`sizeof`. -/

namespace Lua.Vm.Layout

/-- `sizeof(TValue)` — `TValue`: 8-byte `Value` union + tag byte, padded -/
def tvalueSize : Nat := 16
/-- `offsetof(TValue, value_)` -/
def tvalueValOff : Nat := 0
/-- `offsetof(TValue, tt_)` — the `tt_` tag byte -/
def tvalueTagOff : Nat := 8
/-- `sizeof(StackValue)` — one stack slot -/
def stackValueSize : Nat := 16
/-- `sizeof(lua_State)` -/
def stateSize : Nat := 200
/-- `offsetof(lua_State, status)` -/
def stateStatusOff : Nat := 10
/-- `offsetof(lua_State, top)` — `L->top` (StkIdRel) -/
def stateTopOff : Nat := 16
/-- `offsetof(lua_State, l_G)` -/
def stateGOff : Nat := 24
/-- `offsetof(lua_State, ci)` — `L->ci`, the current CallInfo -/
def stateCiOff : Nat := 32
/-- `offsetof(lua_State, stack_last)` -/
def stateStackLastOff : Nat := 40
/-- `offsetof(lua_State, stack)` -/
def stateStackOff : Nat := 48
/-- `offsetof(lua_State, openupval)` -/
def stateOpenupvalOff : Nat := 56
/-- `offsetof(lua_State, tbclist)` -/
def stateTbclistOff : Nat := 64
/-- `offsetof(lua_State, errorJmp)` -/
def stateErrorJmpOff : Nat := 88
/-- `offsetof(lua_State, base_ci)` -/
def stateBaseCiOff : Nat := 96
/-- `offsetof(lua_State, hookmask)` -/
def stateHookmaskOff : Nat := 192
/-- `offsetof(lua_State, nCcalls)` -/
def stateNCcallsOff : Nat := 176
/-- `sizeof(CallInfo)` -/
def ciSize : Nat := 64
/-- `offsetof(CallInfo, func)` -/
def ciFuncOff : Nat := 0
/-- `offsetof(CallInfo, top)` -/
def ciTopOff : Nat := 8
/-- `offsetof(CallInfo, previous)` -/
def ciPreviousOff : Nat := 16
/-- `offsetof(CallInfo, next)` -/
def ciNextOff : Nat := 24
/-- `offsetof(CallInfo, u.l.savedpc)` -/
def ciSavedpcOff : Nat := 32
/-- `offsetof(CallInfo, u.l.trap)` -/
def ciTrapOff : Nat := 40
/-- `offsetof(CallInfo, u.l.nextraargs)` -/
def ciNextraargsOff : Nat := 44
/-- `offsetof(CallInfo, nresults)` -/
def ciNresultsOff : Nat := 60
/-- `offsetof(CallInfo, callstatus)` -/
def ciCallstatusOff : Nat := 62
/-- `offsetof(LClosure, p)` -/
def lclosureProtoOff : Nat := 24
/-- `offsetof(LClosure, upvals)` -/
def lclosureUpvalsOff : Nat := 32
/-- `offsetof(LClosure, nupvalues)` -/
def lclosureNupvaluesOff : Nat := 10
/-- `offsetof(CClosure, f)` -/
def cclosureFOff : Nat := 24
/-- `offsetof(UpVal, v.p)` -/
def upvalVOff : Nat := 16
/-- `offsetof(UpVal, u.value)` — closed value -/
def upvalValueOff : Nat := 24
/-- `offsetof(Proto, numparams)` -/
def protoNumparamsOff : Nat := 10
/-- `offsetof(Proto, is_vararg)` -/
def protoIsVarargOff : Nat := 11
/-- `offsetof(Proto, maxstacksize)` -/
def protoMaxstacksizeOff : Nat := 12
/-- `offsetof(Proto, sizeupvalues)` -/
def protoSizeupvaluesOff : Nat := 16
/-- `offsetof(Proto, sizek)` -/
def protoSizekOff : Nat := 20
/-- `offsetof(Proto, sizecode)` -/
def protoSizecodeOff : Nat := 24
/-- `offsetof(Proto, sizep)` -/
def protoSizepOff : Nat := 32
/-- `offsetof(Proto, k)` -/
def protoKOff : Nat := 56
/-- `offsetof(Proto, code)` -/
def protoCodeOff : Nat := 64
/-- `offsetof(Proto, p)` -/
def protoPOff : Nat := 72
/-- `offsetof(Proto, upvalues)` -/
def protoUpvaluesOff : Nat := 80
/-- `sizeof(Upvaldesc)` -/
def upvaldescSize : Nat := 16
/-- `offsetof(Upvaldesc, instack)` -/
def upvaldescInstackOff : Nat := 8
/-- `offsetof(Upvaldesc, idx)` -/
def upvaldescIdxOff : Nat := 9
/-- `offsetof(Upvaldesc, kind)` -/
def upvaldescKindOff : Nat := 10
/-- `offsetof(TString, shrlen)` -/
def tstringShrlenOff : Nat := 11
/-- `offsetof(TString, hash)` -/
def tstringHashOff : Nat := 12
/-- `offsetof(TString, u.lnglen)` -/
def tstringLnglenOff : Nat := 16
/-- `offsetof(TString, contents)` -/
def tstringContentsOff : Nat := 24
/-- `offsetof(Table, flags)` -/
def tableFlagsOff : Nat := 10
/-- `offsetof(Table, lsizenode)` -/
def tableLsizenodeOff : Nat := 11
/-- `offsetof(Table, alimit)` -/
def tableAlimitOff : Nat := 12
/-- `offsetof(Table, array)` -/
def tableArrayOff : Nat := 16
/-- `offsetof(Table, node)` -/
def tableNodeOff : Nat := 24
/-- `offsetof(Table, lastfree)` -/
def tableLastfreeOff : Nat := 32
/-- `offsetof(Table, metatable)` -/
def tableMetatableOff : Nat := 40
/-- `sizeof(Node)` -/
def nodeSize : Nat := 24
/-- `offsetof(Node, u.key_tt)` -/
def nodeKeyTtOff : Nat := 9
/-- `offsetof(Node, u.next)` -/
def nodeNextOff : Nat := 12
/-- `offsetof(Node, u.key_val)` -/
def nodeKeyValOff : Nat := 16
/-- `offsetof(global_State, l_registry)` -/
def gRegistryOff : Nat := 64
/-- `offsetof(global_State, seed)` -/
def gSeedOff : Nat := 96
/-- `offsetof(global_State, gcstp)` — `gcstp`: GCSTPUSR once main.c stops the collector -/
def gGcstpOff : Nat := 106
/-- `offsetof(global_State, strt)` -/
def gStrtOff : Nat := 48
/-- `offsetof(global_State, tmname)` -/
def gTmnameOff : Nat := 280
/-- `offsetof(global_State, mt)` -/
def gMtOff : Nat := 480
/-- `offsetof(GCObject, tt)` — every collectable object's own tag byte -/
def gcTtOff : Nat := 8
/-- `offsetof(GCObject, marked)` -/
def gcMarkedOff : Nat := 9

/-! Type tags as stored in `tt_` (collectable variants carry bit 6, `ctb`). -/
/-- `LUA_VNIL` -/
def vNil : Nat := 0
/-- `LUA_VEMPTY` -/
def vEmpty : Nat := 16
/-- `LUA_VABSTKEY` -/
def vAbstkey : Nat := 32
/-- `LUA_VFALSE` -/
def vFalse : Nat := 1
/-- `LUA_VTRUE` -/
def vTrue : Nat := 17
/-- `LUA_VNUMINT` -/
def vNumInt : Nat := 3
/-- `LUA_VNUMFLT` -/
def vNumFlt : Nat := 19
/-- `ctb(LUA_VSHRSTR)` -/
def vShrStr : Nat := 68
/-- `ctb(LUA_VLNGSTR)` -/
def vLngStr : Nat := 84
/-- `ctb(LUA_VTABLE)` -/
def vTable : Nat := 69
/-- `ctb(LUA_VLCL)` -/
def vLcl : Nat := 70
/-- `LUA_VLCF` -/
def vLcf : Nat := 22
/-- `ctb(LUA_VCCL)` -/
def vCcl : Nat := 102
/-- `LUA_VLIGHTUSERDATA` -/
def vLightUserdata : Nat := 2
/-- `ctb(LUA_VUSERDATA)` -/
def vUserdata : Nat := 71
/-- `ctb(LUA_VTHREAD)` -/
def vThread : Nat := 72
/-- `GCSTPUSR` -/
def gcstpUsr : Nat := 1
/-- `LUAI_MAXSHORTLEN` -/
def maxShortLen : Nat := 40
/-- `NUM_OPCODES` -/
def numOpcodes : Nat := 83

/-! Symbol addresses in `c/lua-riscv-htif.elf` (`nm`). -/
/-- `_start` -/
def symStart : Nat := 0x80000000
/-- `main` -/
def symMain : Nat := 0x800001f0
/-- `_exit` -/
def symExit : Nat := 0x80000180
/-- `luaV_execute` -/
def symLuaVExecute : Nat := 0x8001aa00
/-- `luaD_call` -/
def symLuaDCall : Nat := 0x80009a1c
/-- `luaD_precall` -/
def symLuaDPrecall : Nat := 0x8000954c
/-- `luaD_throw` -/
def symLuaDThrow : Nat := 0x800084d8
/-- `luaD_rawrunprotected` -/
def symLuaDRawrunprotected : Nat := 0x80008680
/-- `lua_pcallk` -/
def symLuaPcallk : Nat := 0x80002b50
/-- `luaL_loadbufferx` -/
def symLuaLLoadbufferx : Nat := 0x800203e8
/-- `luaB_print` -/
def symLuaBPrint : Nat := 0x800219b0
/-- `setjmp` -/
def symSetjmp : Nat := 0x800341f0
/-- `longjmp` -/
def symLongjmp : Nat := 0x80034230
/-- `malloc` -/
def symMalloc : Nat := 0x8002b96c
/-- `realloc` -/
def symRealloc : Nat := 0x8002c254
/-- `free` -/
def symFree : Nat := 0x8002b978
/-- `tohost` -/
def symTohost : Nat := 0x80048400
/-- `_chunk_start` -/
def symChunkStart : Nat := 0x80049870
/-- `_end` -/
def symEnd : Nat := 0x80059870
/-- `__heap_end` -/
def symHeapEnd : Nat := 0x87800000
/-- `__stack_top` -/
def symStackTop : Nat := 0x88000000

end Lua.Vm.Layout
