import Vsa.Sim.DecodeNF

/-! GENERATED by scripts/gen_lua_decode_check.py -- do not edit.

`Vsa.Sim.decodeW` decodes words 15c0106f..37c0006f of `luaV_execute` (part
7/13) to the instruction the Lean evaluator gives. -/

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail ConcurrencyInterfaceV1 Vsa
open Register

namespace Lua.Vm.DecodeCheck

variable (σ : SequentialState RegisterType trivialChoiceSource)
    (hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg))

example : (ext_decode 0x15c0106f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00115c#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1650106f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x001964#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1680f0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00f168#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x16c0106f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00116c#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x16d100ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x01096c#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x16d704e3#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x0968#13, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.bop.BEQ)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x16d70ee3#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x097c#13, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.bop.BEQ)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1740206f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x002174#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1800f0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00f180#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x180512e3#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x0984#13, LeanRV64DExecutable.regidx.Regidx 0x00#5, LeanRV64DExecutable.regidx.Regidx 0x0a#5, LeanRV64DExecutable.bop.BNE)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1810e0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00e980#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1840f0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00f184#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x18a05863#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x0190#13, LeanRV64DExecutable.regidx.Regidx 0x0a#5, LeanRV64DExecutable.regidx.Regidx 0x00#5, LeanRV64DExecutable.bop.BGE)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x18c70ee3#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x099c#13, LeanRV64DExecutable.regidx.Regidx 0x0c#5, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.bop.BEQ)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x18d0006f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00098c#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1900206f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x002190#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x19260ae3#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x0994#13, LeanRV64DExecutable.regidx.Regidx 0x12#5, LeanRV64DExecutable.regidx.Regidx 0x0c#5, LeanRV64DExecutable.bop.BEQ)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1a051ee3#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x09bc#13, LeanRV64DExecutable.regidx.Regidx 0x00#5, LeanRV64DExecutable.regidx.Regidx 0x0a#5, LeanRV64DExecutable.bop.BNE)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1a074e63#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x01bc#13, LeanRV64DExecutable.regidx.Regidx 0x00#5, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.bop.BLT)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1ad0106f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x0019ac#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1ad0e0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00e9ac#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1ae69c63#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x01b8#13, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.bop.BNE)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1b00206f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x0021b0#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1b05b583#32).run σ =
    .ok (LeanRV64DExecutable.instruction.LOAD (0x1b0#12, LeanRV64DExecutable.regidx.Regidx 0x0b#5, LeanRV64DExecutable.regidx.Regidx 0x0b#5, false, 8)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1b271263#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x01a4#13, LeanRV64DExecutable.regidx.Regidx 0x12#5, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.bop.BNE)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1b80106f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x0011b8#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1bd0e0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00e9bc#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1c05b583#32).run σ =
    .ok (LeanRV64DExecutable.instruction.LOAD (0x1c0#12, LeanRV64DExecutable.regidx.Regidx 0x0b#5, LeanRV64DExecutable.regidx.Regidx 0x0b#5, false, 8)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1cc0206f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x0021cc#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1cd70ce3#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x09d8#13, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.bop.BEQ)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1d00106f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x0011d0#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1d4120ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x0121d4#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1d5110ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x0119d4#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1d80106f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x0011d8#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1d80f0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00f1d8#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1dd0106f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x0019dc#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1e00206f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x0021e0#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1e054263#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x01e4#13, LeanRV64DExecutable.regidx.Regidx 0x00#5, LeanRV64DExecutable.regidx.Regidx 0x0a#5, LeanRV64DExecutable.bop.BLT)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1e10106f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x0019e0#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1e40106f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x0011e4#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1e40206f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x0021e4#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1e50c0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00c9e4#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1e80206f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x0021e8#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1ed0e0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00e9ec#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1ee4e863#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x01f0#13, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.regidx.Regidx 0x09#5, LeanRV64DExecutable.bop.BLTU)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1f00f0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00f1f0#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1f50006f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x0009f4#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x1f90e0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00e9f8#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x20074a63#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x0214#13, LeanRV64DExecutable.regidx.Regidx 0x00#5, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.bop.BLT)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x20d702e3#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x0a04#13, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.bop.BEQ)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2100c0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00c210#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2100f0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00f210#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x21c5b583#32).run σ =
    .ok (LeanRV64DExecutable.instruction.LOAD (0x21c#12, LeanRV64DExecutable.regidx.Regidx 0x0b#5, LeanRV64DExecutable.regidx.Regidx 0x0b#5, false, 8)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x21d100ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x010a1c#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x22055863#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x0230#13, LeanRV64DExecutable.regidx.Regidx 0x00#5, LeanRV64DExecutable.regidx.Regidx 0x0a#5, LeanRV64DExecutable.bop.BGE)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x224110ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x011224#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x228120ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x012228#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x22c5b583#32).run σ =
    .ok (LeanRV64DExecutable.instruction.LOAD (0x22c#12, LeanRV64DExecutable.regidx.Regidx 0x0b#5, LeanRV64DExecutable.regidx.Regidx 0x0b#5, false, 8)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x22d702e3#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x0a24#13, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.bop.BEQ)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x234100ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x010234#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x234110ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x011234#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x235110ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x011a34#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x238100ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x010238#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x24054663#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x024c#13, LeanRV64DExecutable.regidx.Regidx 0x00#5, LeanRV64DExecutable.regidx.Regidx 0x0a#5, LeanRV64DExecutable.bop.BLT)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x248100ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x010248#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2490f0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00fa48#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2500106f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x001250#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2600f0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00f260#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2680d0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00d268#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2680f0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00f268#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x26a05ae3#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x0a74#13, LeanRV64DExecutable.regidx.Regidx 0x0a#5, LeanRV64DExecutable.regidx.Regidx 0x00#5, LeanRV64DExecutable.bop.BGE)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x26d706e3#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x0a6c#13, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.bop.BEQ)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x26e780e3#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x0a60#13, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.regidx.Regidx 0x0f#5, LeanRV64DExecutable.bop.BEQ)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2750f0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00fa74#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x280542e3#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x0a84#13, LeanRV64DExecutable.regidx.Regidx 0x00#5, LeanRV64DExecutable.regidx.Regidx 0x0a#5, LeanRV64DExecutable.bop.BLT)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2840c0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00c284#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x28c5b583#32).run σ =
    .ok (LeanRV64DExecutable.instruction.LOAD (0x28c#12, LeanRV64DExecutable.regidx.Regidx 0x0b#5, LeanRV64DExecutable.regidx.Regidx 0x0b#5, false, 8)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2940106f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x001294#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x29c5b583#32).run σ =
    .ok (LeanRV64DExecutable.instruction.LOAD (0x29c#12, LeanRV64DExecutable.regidx.Regidx 0x0b#5, LeanRV64DExecutable.regidx.Regidx 0x0b#5, false, 8)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2ad0e0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00eaac#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2b10e0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00eab0#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2b4120ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x0122b4#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2b80106f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x0012b8#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2c0a9463#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x02c8#13, LeanRV64DExecutable.regidx.Regidx 0x00#5, LeanRV64DExecutable.regidx.Regidx 0x15#5, LeanRV64DExecutable.bop.BNE)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2c50206f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x002ac4#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2cd0e0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00eacc#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2d2704e3#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x0ac8#13, LeanRV64DExecutable.regidx.Regidx 0x12#5, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.bop.BEQ)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2d40306f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x0032d4#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2d90106f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x001ad8#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2e50e0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00eae4#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2e90f0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00fae8#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2f00f0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00f2f0#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2f40206f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x0022f4#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2f4110ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x0112f4#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2f90106f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x001af8#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x2f90e0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00eaf8#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x3040106f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x001304#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x3150106f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x001b14#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x319120ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x012b18#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x31c5b583#32).run σ =
    .ok (LeanRV64DExecutable.instruction.LOAD (0x31c#12, LeanRV64DExecutable.regidx.Regidx 0x0b#5, LeanRV64DExecutable.regidx.Regidx 0x0b#5, false, 8)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x31d0106f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x001b1c#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x3200206f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x002320#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x32055ce3#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x0b38#13, LeanRV64DExecutable.regidx.Regidx 0x00#5, LeanRV64DExecutable.regidx.Regidx 0x0a#5, LeanRV64DExecutable.bop.BGE)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x3210106f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x001b20#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x321110ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x011b20#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x32c0106f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00132c#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x32c5b583#32).run σ =
    .ok (LeanRV64DExecutable.instruction.LOAD (0x32c#12, LeanRV64DExecutable.regidx.Regidx 0x0b#5, LeanRV64DExecutable.regidx.Regidx 0x0b#5, false, 8)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x332702e3#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x0b24#13, LeanRV64DExecutable.regidx.Regidx 0x12#5, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.bop.BEQ)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x33278ee3#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x0b3c#13, LeanRV64DExecutable.regidx.Regidx 0x12#5, LeanRV64DExecutable.regidx.Regidx 0x0f#5, LeanRV64DExecutable.bop.BEQ)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x3340206f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x002334#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x3390c0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00cb38#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x3390e0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00eb38#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x3500106f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x001350#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x3500f0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00f350#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x3510206f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x002b50#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x3540106f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x001354#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x35c100ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x01035c#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x35d0f0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00fb5c#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x36074663#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x036c#13, LeanRV64DExecutable.regidx.Regidx 0x00#5, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.bop.BLT)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x3650106f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x001b64#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x3690006f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x000b68#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x36c100ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x01036c#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x36c70ee3#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x0b7c#13, LeanRV64DExecutable.regidx.Regidx 0x0c#5, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.bop.BEQ)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x37260ce3#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x0b78#13, LeanRV64DExecutable.regidx.Regidx 0x12#5, LeanRV64DExecutable.regidx.Regidx 0x0c#5, LeanRV64DExecutable.bop.BEQ)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x37270ee3#32).run σ =
    .ok (LeanRV64DExecutable.instruction.BTYPE (0x0b7c#13, LeanRV64DExecutable.regidx.Regidx 0x12#5, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.bop.BEQ)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x3790e0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00eb78#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x3790f0ef#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00fb78#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

example : (ext_decode 0x37c0006f#32).run σ =
    .ok (LeanRV64DExecutable.instruction.JAL (0x00037c#21, LeanRV64DExecutable.regidx.Regidx 0x00#5)) σ :=
  Vsa.Sim.decodeW σ hmisa hpriv hsec

end Lua.Vm.DecodeCheck
