import Lua.Vm.Sim.Dispatch
import Lua.Vm.Sim.Close
import Lua.Vm.Arms.Segs.G10
import Lua.Vm.Arms.Segs.G11
import Lua.Vm.Arms.Segs.G56
import Lua.Vm.Arms.Segs.G57

/-! GENERATED by scripts/gen_lua_arm.py -- do not edit.

The A1 simulation lemma of `OP_GTI` (kind `cmpI`). -/

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail ConcurrencyInterfaceV1 Vsa
open Vsa.Sim Vsa.Logic

namespace Lua.Vm.Sim

open Lua.Bytecode Lua.Vm.Layout
open Vsa.Machine (MState Config Steps StepsN)

/-- **GTI** (kind `cmpI`): from the fetch head, the dispatch and, per
exit of the kernel, the arm's segments return to the head in a state related
to the `Step`'s successor. -/
theorem sim_GTI {p : Proto} (hS : Supported p) {c : Config} {s s' : State}
    (hR : VmRel p c s) {ins : Word} (hf : p.fetch s.pc = some ins)
    (hop : ins.op? = some .GTI) (hstep : Step binaryHost p s s') :
    ∃ c' n, 0 < n ∧ StepsN n c c' ∧ VmRel p c' s' := by
  obtain ⟨w, hR⟩ := hR
  refine sim_of_run (w := w) ?_
  have hK0 : kernelAt p s.pc = docondjump p s.pc ins.k [immB ins, .reg ins.a] (δ .lt) := by
    simp [kernelAt, hf, kernel, hop, opKernel]
  cases ht : nextJump p s.pc with
  | none =>
    obtain ⟨hK', -, -, -⟩ := hstep
    simp [hK0, docondjump, ht] at hK'
  | some t =>
  obtain ⟨vs, cv, hvs, hcv, rfl⟩ := step_condjump hstep hK0 ht
  have htop := supported_regTop hS hf
  simp [regTop, kernel, hop, opKernel, docondjump, ht, Kernel.regTop, Opnd.ports, immB] at htop
  simp only [Opnd.ports, immB] at hvs
  obtain ⟨va, hva, rfl⟩ := mapM1 hvs
  simp only [Opnd.fill, immB] at hcv
  simp only [nextJump, Option.bind_eq_some_iff] at ht
  obtain ⟨ni, hni, hjt⟩ := ht
  have hnum : ins.opNum = 64 := opNum_of_op? hop
  obtain ⟨c1, hs1, hlt1, hA⟩ := dispatch hR hf (by rw [hnum]; decide)
  have hc1 := hA.core
  have hr := hc1.ranges
  have hpc1 : c1.σ.regs.get? Register.PC = some (0x8001c5ac#64) := by
    rw [hA.pcAt, hnum]; exact congrArg some (by decide +kernel)
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  have hbl := hr.base_lo
  have hbh := hr.base_hi
  have hba := hr.base_al
  have hcl := hr.ci_lo
  have hch := hr.ci_hi
  have hins := ins.isLt
  simp only [stackValueSize, ciSize] at hbh hch
  have hcode := hr.code_hi
  have hcdl := hr.code_lo
  have hlt := fetch_lt hni
  simp only [Word.a, Word.field] at htop
  have hva' := hc1.stack ins.a va (by simp only [Word.a, Word.field]; omega) hva
  by_cases hTa : slotTag c1.σ.mem (w.slot ins.a) = BitVec.ofNat 8 vNumInt
  · obtain rfl := hva'.int_of_tag hTa
    simp only [δ, Option.some.injEq] at hcv
    subst hcv
    rw [cond_bool]
    by_cases hJ : ins.k = decide ((BitVec.ofInt 64 ins.sb).toInt < (slotVal c1.σ.mem (w.slot ins.a)).toInt)
    · rw [if_pos hJ.symm]
      obtain ⟨c2, hs2, hq1⟩ := Arms.seg_8001c5ac_8001c5d0_n
        (sign_extend (m := 64) ins) (BitVec.ofNat 64 w.base) (BitVec.ofNat 64 vNumInt)
        (BitVec.ofNat 64 w.sp) (BitVec.ofNat 64 symGlobalPointer) (BitVec.ofNat 64 w.L)
        (BitVec.ofNat 64 (Arms.jtEntries - 1)) (BitVec.ofNat 64 (w.code + 4 * (s.pc + 1))) (0#64)
        (BitVec.ofNat 64 w.ci) (BitVec.ofNat 64 Arms.jtBase) (BitVec.ofNat 64 (w.code + 4 * s.pc))
        c1.σ.mem c1.σ.sailOutput
        (by slot_arith) (by slot_arith) (by slot_arith)
        (by refine guard_tag_bne_f (n := w.slot ins.a) ?_ hTa (by decide); slot_arith)
        c1 ⟨hc1.good, hpc1,
          ⟨hA.s4, hc1.pins.base, hc1.pins.intTag, hc1.pins.sp, hc1.pins.gp, hc1.pins.L, hc1.pins.opMax, hA.s3, hc1.pins.trap, hc1.pins.ci, hc1.pins.jt, hc1.pins.pc, trivial⟩,
          hc1.minstret, hc1.tick, ⟨hc1.text, rfl, rfl, hc1.ok⟩⟩
      obtain ⟨c3, hs3, hq2⟩ := Arms.seg_8001c5d0_8001c5d4
        (BitVec.ofNat 64 w.sp) (BitVec.ofNat 64 symGlobalPointer) (BitVec.ofNat 64 w.L)
        (BitVec.ofNat 64 (Arms.jtEntries - 1)) (BitVec.ofNat 64 vNumInt)
        (BitVec.ofNat 64 (w.code + 4 * (s.pc + 1))) (sign_extend (m := 64) ins) (0#64)
        (BitVec.ofNat 64 w.ci) (BitVec.ofNat 64 Arms.jtBase) (BitVec.ofNat 64 w.base)
        (BitVec.ofNat 64 (w.code + 4 * s.pc))
        (sign_extend (m := 64) (Sail.BitVec.extractLsb (((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) ins) 31 0) (0x10#5))) &&& sign_extend (m := 64) (0x0ff#12)) + sign_extend (m := 64) (0xf81#12)) 31 0))
        ((BitVec.ofNat 64 w.base) + (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) ins) 31 0) (0x07#5))) &&& sign_extend (m := 64) (0x0ff#12)) (Sail.BitVec.extractLsb (0x04#6) 5 0)))
        c1.σ.mem c1.σ.sailOutput
        c2 ⟨hq1.good, hq1.pcAt,
          ⟨pinsHold_get hq1.pins 7 (by len_arith), pinsHold_get hq1.pins 8 (by len_arith), pinsHold_get hq1.pins 9 (by len_arith), pinsHold_get hq1.pins 10 (by len_arith), pinsHold_get hq1.pins 6 (by len_arith), pinsHold_get hq1.pins 11 (by len_arith), pinsHold_get hq1.pins 4 (by len_arith), pinsHold_get hq1.pins 12 (by len_arith), pinsHold_get hq1.pins 13 (by len_arith), pinsHold_get hq1.pins 14 (by len_arith), pinsHold_get hq1.pins 5 (by len_arith), pinsHold_get hq1.pins 15 (by len_arith), pinsHold_get hq1.pins 0 (by len_arith), pinsHold_get hq1.pins 3 (by len_arith), trivial⟩,
          hq1.minstret, hq1.tick, ⟨hq1.armText, hq1.armMem, hq1.armOut, hq1.armOk⟩⟩
      obtain ⟨c4, hs4, hq3⟩ := Arms.seg_8001eb7c_8001eb90_t
        ((BitVec.ofNat 64 w.base) + (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) ins) 31 0) (0x07#5))) &&& sign_extend (m := 64) (0x0ff#12)) (Sail.BitVec.extractLsb (0x04#6) 5 0)))
        (sign_extend (m := 64) (Sail.BitVec.extractLsb (((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) ins) 31 0) (0x10#5))) &&& sign_extend (m := 64) (0x0ff#12)) + sign_extend (m := 64) (0xf81#12)) 31 0))
        (sign_extend (m := 64) ins) (BitVec.ofNat 64 w.sp) (BitVec.ofNat 64 symGlobalPointer)
        (BitVec.ofNat 64 w.L) (BitVec.ofNat 64 (Arms.jtEntries - 1)) (BitVec.ofNat 64 vNumInt)
        (BitVec.ofNat 64 (w.code + 4 * (s.pc + 1))) (0#64) (BitVec.ofNat 64 w.ci)
        (BitVec.ofNat 64 Arms.jtBase) (BitVec.ofNat 64 w.base)
        (BitVec.ofNat 64 (w.code + 4 * s.pc))
        c1.σ.mem c1.σ.sailOutput
        (by slot_arith) (by slot_arith) (by slot_arith)
        (by rw [sbraw_eq]; refine guard_kf_t (x := ins) (f := fun X => zopz0zI_s (BitVec.ofInt 64 ins.sb) X) (n := w.slot ins.a) ?_ (by simp only [mb_lt]) hJ; slot_arith)
        c3 ⟨hq2.good, hq2.pcAt,
          ⟨pinsHold_get hq2.pins 13 (by len_arith), pinsHold_get hq2.pins 12 (by len_arith), pinsHold_get hq2.pins 6 (by len_arith), pinsHold_get hq2.pins 0 (by len_arith), pinsHold_get hq2.pins 1 (by len_arith), pinsHold_get hq2.pins 2 (by len_arith), pinsHold_get hq2.pins 3 (by len_arith), pinsHold_get hq2.pins 4 (by len_arith), pinsHold_get hq2.pins 5 (by len_arith), pinsHold_get hq2.pins 7 (by len_arith), pinsHold_get hq2.pins 8 (by len_arith), pinsHold_get hq2.pins 9 (by len_arith), pinsHold_get hq2.pins 10 (by len_arith), pinsHold_get hq2.pins 11 (by len_arith), trivial⟩,
          hq2.minstret, hq2.tick, ⟨hq2.armText, hq2.armMem, hq2.armOut, hq2.armOk⟩⟩
      obtain ⟨c5, hs5, hq4⟩ := Arms.seg_8001eb94_8001ebbc
        (BitVec.ofNat 64 (w.code + 4 * s.pc)) (BitVec.ofNat 64 w.ci)
        (BitVec.ofNat 64 (w.code + 4 * (s.pc + 1))) (BitVec.ofNat 64 w.sp)
        (BitVec.ofNat 64 symGlobalPointer) (BitVec.ofNat 64 w.L)
        (BitVec.ofNat 64 (Arms.jtEntries - 1)) (BitVec.ofNat 64 vNumInt)
        (sign_extend (m := 64) ins) (0#64) (BitVec.ofNat 64 Arms.jtBase) (BitVec.ofNat 64 w.base)
        c1.σ.mem c1.σ.sailOutput
        (by slot_arith) (by slot_arith) (by slot_arith) (by slot_arith) (by slot_arith)
        (by slot_arith)
        c4 ⟨hq3.good, hq3.pcAt,
          ⟨pinsHold_get hq3.pins 14 (by len_arith), pinsHold_get hq3.pins 11 (by len_arith), pinsHold_get hq3.pins 9 (by len_arith), pinsHold_get hq3.pins 4 (by len_arith), pinsHold_get hq3.pins 5 (by len_arith), pinsHold_get hq3.pins 6 (by len_arith), pinsHold_get hq3.pins 7 (by len_arith), pinsHold_get hq3.pins 8 (by len_arith), pinsHold_get hq3.pins 3 (by len_arith), pinsHold_get hq3.pins 10 (by len_arith), pinsHold_get hq3.pins 12 (by len_arith), pinsHold_get hq3.pins 13 (by len_arith), trivial⟩,
          hq3.minstret, hq3.tick, ⟨hq3.armText, hq3.armMem, hq3.armOut, hq3.armOk⟩⟩
      have hmE : c5.σ.mem = c1.σ.mem := hq4.armMem
      have hsteps : Steps c1 c5 := (hs2.trans (hs3.trans (hs4.trans hs5)))
      have hx21 : c5.σ.regs.get? Register.x21 = some (0#64) := by
        have h := pinsHold_get hq4.pins 0 (by len_arith)
        simp only [List.getElem_cons_zero] at h
        rw [bytesT4_at (n := w.ci + ciTrapOff) ?_, hc1.trap] at h
        · exact h.trans (congrArg some trap_zero)
        · slot_arith
      have hx27 : c5.σ.regs.get? Register.x27 = some (BitVec.ofNat 64 (w.code + 4 * t)) := by
        have h := pinsHold_get hq4.pins 1 (by len_arith)
        simp only [List.getElem_cons_succ, List.getElem_cons_zero] at h
        have hj := jumpTo_eq hjt
        have hax : ni.ax < 2 ^ 25 := Nat.mod_lt _ (by decide)
        simp only [Word.sj, Word.offsetSJ] at hj
        refine pin_eq h (nextjump_pc ?_ (hc1.fetch hni) hjt (by omega) (by omega))
        slot_arith
      have hcore := hc1.jump hq4 (pc' := t)
        ⟨pinsHold_get hq4.pins 7 (by len_arith), pinsHold_get hq4.pins 8 (by len_arith), pinsHold_get hq4.pins 9 (by len_arith), pinsHold_get hq4.pins 10 (by len_arith), pinsHold_get hq4.pins 11 (by len_arith), hx21, pinsHold_get hq4.pins 5 (by len_arith), pinsHold_get hq4.pins 13 (by len_arith), pinsHold_get hq4.pins 14 (by len_arith), hx27⟩
        hmE
      exact ⟨c5, hs1.trans hsteps, by have := hsteps.steps_le; omega, ⟨hcore, hq4.pcAt⟩⟩
    · rw [if_neg (fun h => hJ h.symm)]
      obtain ⟨c2, hs2, hq1⟩ := Arms.seg_8001c5ac_8001c5d0_n
        (sign_extend (m := 64) ins) (BitVec.ofNat 64 w.base) (BitVec.ofNat 64 vNumInt)
        (BitVec.ofNat 64 w.sp) (BitVec.ofNat 64 symGlobalPointer) (BitVec.ofNat 64 w.L)
        (BitVec.ofNat 64 (Arms.jtEntries - 1)) (BitVec.ofNat 64 (w.code + 4 * (s.pc + 1))) (0#64)
        (BitVec.ofNat 64 w.ci) (BitVec.ofNat 64 Arms.jtBase) (BitVec.ofNat 64 (w.code + 4 * s.pc))
        c1.σ.mem c1.σ.sailOutput
        (by slot_arith) (by slot_arith) (by slot_arith)
        (by refine guard_tag_bne_f (n := w.slot ins.a) ?_ hTa (by decide); slot_arith)
        c1 ⟨hc1.good, hpc1,
          ⟨hA.s4, hc1.pins.base, hc1.pins.intTag, hc1.pins.sp, hc1.pins.gp, hc1.pins.L, hc1.pins.opMax, hA.s3, hc1.pins.trap, hc1.pins.ci, hc1.pins.jt, hc1.pins.pc, trivial⟩,
          hc1.minstret, hc1.tick, ⟨hc1.text, rfl, rfl, hc1.ok⟩⟩
      obtain ⟨c3, hs3, hq2⟩ := Arms.seg_8001c5d0_8001c5d4
        (BitVec.ofNat 64 w.sp) (BitVec.ofNat 64 symGlobalPointer) (BitVec.ofNat 64 w.L)
        (BitVec.ofNat 64 (Arms.jtEntries - 1)) (BitVec.ofNat 64 vNumInt)
        (BitVec.ofNat 64 (w.code + 4 * (s.pc + 1))) (sign_extend (m := 64) ins) (0#64)
        (BitVec.ofNat 64 w.ci) (BitVec.ofNat 64 Arms.jtBase) (BitVec.ofNat 64 w.base)
        (BitVec.ofNat 64 (w.code + 4 * s.pc))
        (sign_extend (m := 64) (Sail.BitVec.extractLsb (((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) ins) 31 0) (0x10#5))) &&& sign_extend (m := 64) (0x0ff#12)) + sign_extend (m := 64) (0xf81#12)) 31 0))
        ((BitVec.ofNat 64 w.base) + (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) ins) 31 0) (0x07#5))) &&& sign_extend (m := 64) (0x0ff#12)) (Sail.BitVec.extractLsb (0x04#6) 5 0)))
        c1.σ.mem c1.σ.sailOutput
        c2 ⟨hq1.good, hq1.pcAt,
          ⟨pinsHold_get hq1.pins 7 (by len_arith), pinsHold_get hq1.pins 8 (by len_arith), pinsHold_get hq1.pins 9 (by len_arith), pinsHold_get hq1.pins 10 (by len_arith), pinsHold_get hq1.pins 6 (by len_arith), pinsHold_get hq1.pins 11 (by len_arith), pinsHold_get hq1.pins 4 (by len_arith), pinsHold_get hq1.pins 12 (by len_arith), pinsHold_get hq1.pins 13 (by len_arith), pinsHold_get hq1.pins 14 (by len_arith), pinsHold_get hq1.pins 5 (by len_arith), pinsHold_get hq1.pins 15 (by len_arith), pinsHold_get hq1.pins 0 (by len_arith), pinsHold_get hq1.pins 3 (by len_arith), trivial⟩,
          hq1.minstret, hq1.tick, ⟨hq1.armText, hq1.armMem, hq1.armOut, hq1.armOk⟩⟩
      obtain ⟨c4, hs4, hq3⟩ := Arms.seg_8001eb7c_8001eb90_n
        ((BitVec.ofNat 64 w.base) + (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) ins) 31 0) (0x07#5))) &&& sign_extend (m := 64) (0x0ff#12)) (Sail.BitVec.extractLsb (0x04#6) 5 0)))
        (sign_extend (m := 64) (Sail.BitVec.extractLsb (((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) ins) 31 0) (0x10#5))) &&& sign_extend (m := 64) (0x0ff#12)) + sign_extend (m := 64) (0xf81#12)) 31 0))
        (sign_extend (m := 64) ins) (BitVec.ofNat 64 w.sp) (BitVec.ofNat 64 symGlobalPointer)
        (BitVec.ofNat 64 w.L) (BitVec.ofNat 64 (Arms.jtEntries - 1)) (BitVec.ofNat 64 vNumInt)
        (BitVec.ofNat 64 (w.code + 4 * (s.pc + 1))) (0#64) (BitVec.ofNat 64 w.ci)
        (BitVec.ofNat 64 Arms.jtBase) (BitVec.ofNat 64 w.base)
        (BitVec.ofNat 64 (w.code + 4 * s.pc))
        c1.σ.mem c1.σ.sailOutput
        (by slot_arith) (by slot_arith) (by slot_arith)
        (by rw [sbraw_eq]; refine guard_kf_f (x := ins) (f := fun X => zopz0zI_s (BitVec.ofInt 64 ins.sb) X) (n := w.slot ins.a) ?_ (by simp only [mb_lt]) hJ; slot_arith)
        c3 ⟨hq2.good, hq2.pcAt,
          ⟨pinsHold_get hq2.pins 13 (by len_arith), pinsHold_get hq2.pins 12 (by len_arith), pinsHold_get hq2.pins 6 (by len_arith), pinsHold_get hq2.pins 0 (by len_arith), pinsHold_get hq2.pins 1 (by len_arith), pinsHold_get hq2.pins 2 (by len_arith), pinsHold_get hq2.pins 3 (by len_arith), pinsHold_get hq2.pins 4 (by len_arith), pinsHold_get hq2.pins 5 (by len_arith), pinsHold_get hq2.pins 7 (by len_arith), pinsHold_get hq2.pins 8 (by len_arith), pinsHold_get hq2.pins 9 (by len_arith), pinsHold_get hq2.pins 10 (by len_arith), pinsHold_get hq2.pins 11 (by len_arith), trivial⟩,
          hq2.minstret, hq2.tick, ⟨hq2.armText, hq2.armMem, hq2.armOut, hq2.armOk⟩⟩
      obtain ⟨c5, hs5, hq4⟩ := Arms.seg_8001eb90_8001eb94
        (BitVec.ofNat 64 w.sp) (BitVec.ofNat 64 symGlobalPointer) (BitVec.ofNat 64 w.L)
        (BitVec.ofNat 64 (Arms.jtEntries - 1)) (BitVec.ofNat 64 vNumInt)
        (BitVec.ofNat 64 (w.code + 4 * (s.pc + 1))) (sign_extend (m := 64) ins) (0#64)
        (BitVec.ofNat 64 w.ci) (BitVec.ofNat 64 Arms.jtBase) (BitVec.ofNat 64 w.base)
        (BitVec.ofNat 64 (w.code + 4 * s.pc))
        c1.σ.mem c1.σ.sailOutput
        c4 ⟨hq3.good, hq3.pcAt,
          ⟨pinsHold_get hq3.pins 4 (by len_arith), pinsHold_get hq3.pins 5 (by len_arith), pinsHold_get hq3.pins 6 (by len_arith), pinsHold_get hq3.pins 7 (by len_arith), pinsHold_get hq3.pins 8 (by len_arith), pinsHold_get hq3.pins 9 (by len_arith), pinsHold_get hq3.pins 3 (by len_arith), pinsHold_get hq3.pins 10 (by len_arith), pinsHold_get hq3.pins 11 (by len_arith), pinsHold_get hq3.pins 12 (by len_arith), pinsHold_get hq3.pins 13 (by len_arith), pinsHold_get hq3.pins 14 (by len_arith), trivial⟩,
          hq3.minstret, hq3.tick, ⟨hq3.armText, hq3.armMem, hq3.armOut, hq3.armOk⟩⟩
      obtain ⟨c6, hs6, hq5⟩ := Arms.seg_8001c604_8001c60c
        (BitVec.ofNat 64 (w.code + 4 * s.pc)) (BitVec.ofNat 64 w.sp)
        (BitVec.ofNat 64 symGlobalPointer) (BitVec.ofNat 64 w.L)
        (BitVec.ofNat 64 (Arms.jtEntries - 1)) (BitVec.ofNat 64 vNumInt)
        (BitVec.ofNat 64 (w.code + 4 * (s.pc + 1))) (sign_extend (m := 64) ins) (0#64)
        (BitVec.ofNat 64 w.ci) (BitVec.ofNat 64 Arms.jtBase) (BitVec.ofNat 64 w.base)
        c1.σ.mem c1.σ.sailOutput
        c5 ⟨hq4.good, hq4.pcAt,
          ⟨pinsHold_get hq4.pins 11 (by len_arith), pinsHold_get hq4.pins 0 (by len_arith), pinsHold_get hq4.pins 1 (by len_arith), pinsHold_get hq4.pins 2 (by len_arith), pinsHold_get hq4.pins 3 (by len_arith), pinsHold_get hq4.pins 4 (by len_arith), pinsHold_get hq4.pins 5 (by len_arith), pinsHold_get hq4.pins 6 (by len_arith), pinsHold_get hq4.pins 7 (by len_arith), pinsHold_get hq4.pins 8 (by len_arith), pinsHold_get hq4.pins 9 (by len_arith), pinsHold_get hq4.pins 10 (by len_arith), trivial⟩,
          hq4.minstret, hq4.tick, ⟨hq4.armText, hq4.armMem, hq4.armOut, hq4.armOk⟩⟩
      have hmE : c6.σ.mem = c1.σ.mem := hq5.armMem
      have hsteps : Steps c1 c6 := (hs2.trans (hs3.trans (hs4.trans (hs5.trans hs6))))
      have hx27 : c6.σ.regs.get? Register.x27 = some (BitVec.ofNat 64 (w.code + 4 * (s.pc + 2))) := by
        have h := pinsHold_get hq5.pins 0 (by len_arith)
        simp only [List.getElem_cons_zero] at h
        refine pin_eq h ?_
        apply BitVec.eq_of_toNat_eq
        all_goals slot_arith
      have hcore := hc1.jump hq5 (pc' := (s.pc + 2))
        ⟨pinsHold_get hq5.pins 1 (by len_arith), pinsHold_get hq5.pins 2 (by len_arith), pinsHold_get hq5.pins 3 (by len_arith), pinsHold_get hq5.pins 4 (by len_arith), pinsHold_get hq5.pins 5 (by len_arith), pinsHold_get hq5.pins 8 (by len_arith), pinsHold_get hq5.pins 9 (by len_arith), pinsHold_get hq5.pins 10 (by len_arith), pinsHold_get hq5.pins 11 (by len_arith), hx27⟩
        hmE
      exact ⟨c6, hs1.trans hsteps, by have := hsteps.steps_le; omega, ⟨hcore, hq5.pcAt⟩⟩
  · exfalso
    cases va <;> simp [δ] at hcv
    exact hva'.not_int hTa _ rfl

end Lua.Vm.Sim
