-- GENERATED by c/tests/float/gen_pow.py. `x ^ y` vectors 1561..1570 of pow.vec.
local function B(x) return (string.unpack("<i8", string.pack("<d", x))) end
local function F(i) return (string.unpack("<d", string.pack("<i8", i))) end
local V = {
  {0x7119f88497f4f62c, 0x3fdac6315929d9f0},
  {0x13f96b324abfbbe4, 0xc0066f61a493ecf4},
  {0x280b6cad1545fc4e, 0x400482c42cc49a7c},
  {0x34027e0bc5fb3eb4, 0xbfd0b29c2d0fb670},
  {0x348e790aa4983771, 0x3fe1361cd3714d64},
  {0x5e771d37f147c57a, 0x40013215c5b6fc2c},
  {0x28f671f8715c1a8d, 0x3fde248223b4cc40},
  {0xbe38ee143e9dac4, 0xc00586760fc7c8ff},
  {0x51eb27e82bd8e727, 0xbfbe25a3cec36a80},
  {0x45b8ddaffa684434, 0xbffccd297f5a9ec2},
}
for _, v in ipairs(V) do print(B(F(v[1]) ^ F(v[2]))) end
