local zero = 0.0 local nan = zero / zero local big = 1e308 local ten = 10 local inf = big * ten local mi = -9223372036854775807 - 1
local a, b, s, t = 0, 0, 0, 0
s = "1e999" t = -7 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -7 t = "1e999" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e999" t = 9223372036854775807 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 9223372036854775807 t = "1e999" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e999" t = 0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.0 t = "1e999" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e999" t = -0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -0.0 t = "1e999" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e999" t = 0.5 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.5 t = "1e999" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e999" t = -2.25 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -2.25 t = "1e999" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e999" t = inf print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = inf t = "1e999" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e999" t = nan print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = nan t = "1e999" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e999" t = 3.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3.0 t = "1e999" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e999" t = 1e+308 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1e+308 t = "1e999" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xA.8p0" t = 0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0 t = "0xA.8p0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xA.8p0" t = 1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1 t = "0xA.8p0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xA.8p0" t = -1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -1 t = "0xA.8p0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xA.8p0" t = 3 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3 t = "0xA.8p0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xA.8p0" t = -7 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -7 t = "0xA.8p0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xA.8p0" t = 9223372036854775807 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 9223372036854775807 t = "0xA.8p0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xA.8p0" t = 0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.0 t = "0xA.8p0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xA.8p0" t = -0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -0.0 t = "0xA.8p0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xA.8p0" t = 0.5 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.5 t = "0xA.8p0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xA.8p0" t = -2.25 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -2.25 t = "0xA.8p0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xA.8p0" t = inf print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = inf t = "0xA.8p0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xA.8p0" t = nan print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = nan t = "0xA.8p0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xA.8p0" t = 3.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3.0 t = "0xA.8p0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xA.8p0" t = 1e+308 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1e+308 t = "0xA.8p0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-0.0" t = 0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0 t = "-0.0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-0.0" t = 1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1 t = "-0.0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-0.0" t = -1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -1 t = "-0.0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-0.0" t = 3 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3 t = "-0.0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-0.0" t = -7 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -7 t = "-0.0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-0.0" t = 9223372036854775807 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 9223372036854775807 t = "-0.0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-0.0" t = 0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.0 t = "-0.0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-0.0" t = -0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -0.0 t = "-0.0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-0.0" t = 0.5 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.5 t = "-0.0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-0.0" t = -2.25 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -2.25 t = "-0.0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-0.0" t = inf print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = inf t = "-0.0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-0.0" t = nan print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = nan t = "-0.0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-0.0" t = 3.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3.0 t = "-0.0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-0.0" t = 1e+308 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1e+308 t = "-0.0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9007199254740993" t = 0 print(s + t, s - t, s * t, s / t, s ^ t)
s = 0 t = "9007199254740993" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9007199254740993" t = 1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1 t = "9007199254740993" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9007199254740993" t = -1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -1 t = "9007199254740993" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9007199254740993" t = 3 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3 t = "9007199254740993" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9007199254740993" t = -7 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -7 t = "9007199254740993" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9007199254740993" t = 9223372036854775807 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 9223372036854775807 t = "9007199254740993" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9007199254740993" t = 0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.0 t = "9007199254740993" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9007199254740993" t = -0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -0.0 t = "9007199254740993" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9007199254740993" t = 0.5 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.5 t = "9007199254740993" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9007199254740993" t = -2.25 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -2.25 t = "9007199254740993" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9007199254740993" t = inf print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = inf t = "9007199254740993" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9007199254740993" t = nan print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = nan t = "9007199254740993" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9007199254740993" t = 3.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3.0 t = "9007199254740993" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9007199254740993" t = 1e+308 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1e+308 t = "9007199254740993" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "\t5\n" t = 0 print(s + t, s - t, s * t, s / t, s ^ t)
s = 0 t = "\t5\n" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "\t5\n" t = 1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1 t = "\t5\n" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "\t5\n" t = -1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -1 t = "\t5\n" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "\t5\n" t = 3 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3 t = "\t5\n" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "\t5\n" t = -7 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -7 t = "\t5\n" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "\t5\n" t = 9223372036854775807 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 9223372036854775807 t = "\t5\n" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "\t5\n" t = 0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.0 t = "\t5\n" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "\t5\n" t = -0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -0.0 t = "\t5\n" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "\t5\n" t = 0.5 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.5 t = "\t5\n" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "\t5\n" t = -2.25 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -2.25 t = "\t5\n" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "\t5\n" t = inf print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = inf t = "\t5\n" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "\t5\n" t = nan print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = nan t = "\t5\n" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "\t5\n" t = 3.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3.0 t = "\t5\n" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "\t5\n" t = 1e+308 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1e+308 t = "\t5\n" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0" t = 0 print(s + t, s - t, s * t, s / t, s ^ t)
s = 0 t = "0" print(s + t, s - t, s * t, s / t, s ^ t)
s = "0" t = 1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1 t = "0" print(s + t, s - t, s * t, s / t, s ^ t)
s = "0" t = -1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -1 t = "0" print(s + t, s - t, s * t, s / t, s ^ t)
s = "0" t = 3 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3 t = "0" print(s + t, s - t, s * t, s / t, s ^ t)
s = "0" t = -7 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -7 t = "0" print(s + t, s - t, s * t, s / t, s ^ t)
s = "0" t = 9223372036854775807 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 9223372036854775807 t = "0" print(s + t, s - t, s * t, s / t, s ^ t)
s = "0" t = 0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.0 t = "0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0" t = -0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -0.0 t = "0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0" t = 0.5 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.5 t = "0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0" t = -2.25 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -2.25 t = "0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0" t = inf print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = inf t = "0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0" t = nan print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = nan t = "0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0" t = 3.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3.0 t = "0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0" t = 1e+308 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1e+308 t = "0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" print(s + 1, s * 2, s - 0.5, s // 3, s % 3, s ^ 2, s / 4)
s = "1.5" t = "2" print(s * t, s + t, s // t, s % t)
s = "0x1p4" print(s + 0, s * 1, s // 1)
s = "1e2" print(s // 3, s % 3)
s = " 7 " t = "3" print(s % t, s // t)
s = "2" t = "0.5" print(s ^ t)
s = "3" print(s / 2, 2 / s, 1 - s, 0.5 + s, s + 0.0)
