local zero = 0.0 local nan = zero / zero local big = 1e308 local ten = 10 local inf = big * ten local mi = -9223372036854775807 - 1
local a, b, s, t = 0, 0, 0, 0
s = " 7 " t = 0.5 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.5 t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 7 " t = -2.25 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -2.25 t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 7 " t = inf print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = inf t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 7 " t = nan print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = nan t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 7 " t = 3.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3.0 t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 7 " t = 1e+308 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1e+308 t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = 0 print(s + t, s - t, s * t, s / t, s ^ t)
s = 0 t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = 1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1 t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = -1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -1 t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = 3 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3 t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = -7 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -7 t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = 9223372036854775807 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 9223372036854775807 t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = 0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.0 t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = -0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -0.0 t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = 0.5 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.5 t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = -2.25 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -2.25 t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = inf print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = inf t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = nan print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = nan t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = 3.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3.0 t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = 1e+308 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1e+308 t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = 0 print(s + t, s - t, s * t, s / t, s ^ t)
s = 0 t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = 1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1 t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = -1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -1 t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = 3 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3 t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = -7 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -7 t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = 9223372036854775807 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 9223372036854775807 t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = 0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.0 t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = -0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -0.0 t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = 0.5 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.5 t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = -2.25 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -2.25 t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = inf print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = inf t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = nan print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = nan t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = 3.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3.0 t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = 1e+308 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1e+308 t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = 0 print(s + t, s - t, s * t, s / t, s ^ t)
s = 0 t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = 1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1 t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = -1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -1 t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = 3 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3 t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = -7 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -7 t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = 9223372036854775807 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 9223372036854775807 t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = 0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.0 t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = -0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -0.0 t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = 0.5 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.5 t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = -2.25 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -2.25 t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = inf print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = inf t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = nan print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = nan t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = 3.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3.0 t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = 1e+308 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1e+308 t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = 0 print(s + t, s - t, s * t, s / t, s ^ t)
s = 0 t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = 1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1 t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = -1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -1 t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = 3 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3 t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = -7 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -7 t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = 9223372036854775807 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 9223372036854775807 t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = 0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.0 t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = -0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -0.0 t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = 0.5 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.5 t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = -2.25 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -2.25 t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = inf print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = inf t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = nan print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = nan t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = 3.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3.0 t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = 1e+308 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1e+308 t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = 0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0 t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = 1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1 t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = -1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -1 t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = 3 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3 t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = -7 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -7 t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = 9223372036854775807 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 9223372036854775807 t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = 0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.0 t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = -0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -0.0 t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = 0.5 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.5 t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = -2.25 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -2.25 t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = inf print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = inf t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = nan print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = nan t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = 3.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3.0 t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = 1e+308 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1e+308 t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = 0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0 t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = 1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1 t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = -1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -1 t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = 3 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3 t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = -7 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -7 t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = 9223372036854775807 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 9223372036854775807 t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = 0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.0 t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = -0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -0.0 t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = 0.5 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.5 t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = -2.25 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -2.25 t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = inf print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = inf t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = nan print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = nan t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = 3.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3.0 t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = 1e+308 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1e+308 t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0.1" t = 0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0 t = "0.1" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0.1" t = 1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1 t = "0.1" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0.1" t = -1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -1 t = "0.1" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0.1" t = 3 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3 t = "0.1" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0.1" t = -7 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -7 t = "0.1" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0.1" t = 9223372036854775807 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 9223372036854775807 t = "0.1" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0.1" t = 0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.0 t = "0.1" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0.1" t = -0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -0.0 t = "0.1" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0.1" t = 0.5 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.5 t = "0.1" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0.1" t = -2.25 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -2.25 t = "0.1" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0.1" t = inf print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = inf t = "0.1" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0.1" t = nan print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = nan t = "0.1" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0.1" t = 3.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3.0 t = "0.1" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0.1" t = 1e+308 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1e+308 t = "0.1" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-0" t = 0 print(s + t, s - t, s * t, s / t, s ^ t)
s = 0 t = "-0" print(s + t, s - t, s * t, s / t, s ^ t)
s = "-0" t = 1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1 t = "-0" print(s + t, s - t, s * t, s / t, s ^ t)
s = "-0" t = -1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -1 t = "-0" print(s + t, s - t, s * t, s / t, s ^ t)
s = "-0" t = 3 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3 t = "-0" print(s + t, s - t, s * t, s / t, s ^ t)
s = "-0" t = -7 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -7 t = "-0" print(s + t, s - t, s * t, s / t, s ^ t)
s = "-0" t = 9223372036854775807 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 9223372036854775807 t = "-0" print(s + t, s - t, s * t, s / t, s ^ t)
s = "-0" t = 0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.0 t = "-0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-0" t = -0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -0.0 t = "-0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-0" t = 0.5 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.5 t = "-0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-0" t = -2.25 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -2.25 t = "-0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-0" t = inf print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = inf t = "-0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-0" t = nan print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = nan t = "-0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-0" t = 3.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3.0 t = "-0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-0" t = 1e+308 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1e+308 t = "-0" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "2" t = 0 print(s + t, s - t, s * t, s / t, s ^ t)
s = 0 t = "2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "2" t = 1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1 t = "2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "2" t = -1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -1 t = "2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "2" t = 3 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3 t = "2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "2" t = -7 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -7 t = "2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "2" t = 9223372036854775807 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 9223372036854775807 t = "2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "2" t = 0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.0 t = "2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "2" t = -0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -0.0 t = "2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "2" t = 0.5 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.5 t = "2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "2" t = -2.25 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -2.25 t = "2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "2" t = inf print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = inf t = "2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "2" t = nan print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = nan t = "2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "2" t = 3.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3.0 t = "2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "2" t = 1e+308 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1e+308 t = "2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "3" t = 0 print(s + t, s - t, s * t, s / t, s ^ t)
s = 0 t = "3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "3" t = 1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1 t = "3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "3" t = -1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -1 t = "3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "3" t = 3 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3 t = "3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "3" t = -7 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -7 t = "3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "3" t = 9223372036854775807 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 9223372036854775807 t = "3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "3" t = 0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.0 t = "3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "3" t = -0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -0.0 t = "3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "3" t = 0.5 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.5 t = "3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "3" t = -2.25 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -2.25 t = "3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "3" t = inf print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = inf t = "3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "3" t = nan print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = nan t = "3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "3" t = 3.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3.0 t = "3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "3" t = 1e+308 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1e+308 t = "3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e999" t = 0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0 t = "1e999" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e999" t = 1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1 t = "1e999" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e999" t = -1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -1 t = "1e999" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e999" t = 3 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3 t = "1e999" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
