local zero = 0.0 local nan = zero / zero local big = 1e308 local ten = 10 local inf = big * ten local mi = -9223372036854775807 - 1
local a, b, s, t = 0, 0, 0, 0
s = "10" t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 7 " t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 7 " t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 7 " t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 7 " t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 7 " t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 7 " t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 7 " t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 7 " t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 7 " t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 7 " t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 7 " t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 7 " t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 2 " t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "-3" t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x7fffffffffffffff" t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0xffffffffffffffff" t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "9223372036854775808" t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = " 2 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = "-3" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = "0x7fffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = "0xffffffffffffffff" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = "9223372036854775808" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "  0x1P-2  " t = "  0x1P-2  " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" t = 0 print(s + t, s - t, s * t, s / t, s ^ t)
s = 0 t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" t = 1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1 t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" t = -1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -1 t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" t = 3 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3 t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" t = -7 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -7 t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" t = 9223372036854775807 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 9223372036854775807 t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" t = 0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.0 t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" t = -0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -0.0 t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" t = 0.5 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.5 t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" t = -2.25 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -2.25 t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" t = inf print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = inf t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" t = nan print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = nan t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" t = 3.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3.0 t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "10" t = 1e+308 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1e+308 t = "10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = 0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0 t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = 1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1 t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = -1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -1 t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = 3 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3 t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = -7 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -7 t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = 9223372036854775807 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 9223372036854775807 t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = 0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.0 t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = -0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -0.0 t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = 0.5 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.5 t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = -2.25 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -2.25 t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = inf print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = inf t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = nan print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = nan t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = 3.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3.0 t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1.5" t = 1e+308 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1e+308 t = "1.5" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = 0 print(s + t, s - t, s * t, s / t, s ^ t)
s = 0 t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = 1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1 t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = -1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -1 t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = 3 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3 t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = -7 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -7 t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = 9223372036854775807 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 9223372036854775807 t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = 0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.0 t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = -0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -0.0 t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = 0.5 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.5 t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = -2.25 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -2.25 t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = inf print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = inf t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = nan print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = nan t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = 3.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3.0 t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x10" t = 1e+308 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1e+308 t = "0x10" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = 0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0 t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = 1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1 t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = -1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -1 t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = 3 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3 t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = -7 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -7 t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = 9223372036854775807 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 9223372036854775807 t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = 0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.0 t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = -0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -0.0 t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = 0.5 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.5 t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = -2.25 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -2.25 t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = inf print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = inf t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = nan print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = nan t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = 3.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3.0 t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "0x1p4" t = 1e+308 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1e+308 t = "0x1p4" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = 0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0 t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = 1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1 t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = -1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -1 t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = 3 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3 t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = -7 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -7 t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = 9223372036854775807 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 9223372036854775807 t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = 0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.0 t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = -0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -0.0 t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = 0.5 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.5 t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = -2.25 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -2.25 t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = inf print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = inf t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = nan print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = nan t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = 3.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3.0 t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = "1e2" t = 1e+308 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1e+308 t = "1e2" print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 7 " t = 0 print(s + t, s - t, s * t, s / t, s ^ t)
s = 0 t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 7 " t = 1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 1 t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 7 " t = -1 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -1 t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 7 " t = 3 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 3 t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 7 " t = -7 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -7 t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 7 " t = 9223372036854775807 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 9223372036854775807 t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 7 " t = 0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = 0.0 t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = " 7 " t = -0.0 print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
s = -0.0 t = " 7 " print(s + t, s - t, s * t, s / t, s // t, s % t, s ^ t)
