import Lua.Vm.Arms.RegsOk
import Lua.Vm.Arms.Sites.S43
import Lua.Vm.Arms.Sites.S44
import Lua.Vm.Arms.Text
import Vsa.Sim.SegState

/-! GENERATED by scripts/gen_lua_arms.py -- do not edit.

Segment theorems of the F1 arms of `luaV_execute`, `SegSt` to `SegSt`
(scripts/syi/gen_segment.py, `"boundary": "segst"`). -/

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail ConcurrencyInterfaceV1 Vsa
open Register
open Sail.ConcurrencyInterfaceV1.PreSail
open Vsa.Machine (MState Config Step Steps)
open Vsa.Logic
open Vsa.Sim

namespace Lua.Vm.Arms

/-- `0x8001e934`–`0x8001e95c` (10 instructions), from `SegSt` to `SegSt`; side conditions are the `h*_<step>` hypotheses. -/
theorem seg_8001e934_8001e95c
    (v27 v23 v19 v2 v3 v8 v9 v18 v20 v21 v24 v25 : BitVec 64)
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    (o0 : Array String)
    (hlo_1 : 0x80000000 ≤ (v27 + sign_extend (m := 64) (0x004#12)).toNat)
    (hhi_1 : (v27 + sign_extend (m := 64) (0x004#12)).toNat + 4 ≤ 0x100000000)
    (hht_1 : (v27 + sign_extend (m := 64) (0x004#12)).toNat + 4 ≤ tohostAddr ∨ tohostAddr + 8 ≤ (v27 + sign_extend (m := 64) (0x004#12)).toNat)
    (hlo_3 : 0x80000000 ≤ (v23 + sign_extend (m := 64) (0x028#12)).toNat)
    (hhi_3 : (v23 + sign_extend (m := 64) (0x028#12)).toNat + 4 ≤ 0x100000000)
    (hht_3 : (v23 + sign_extend (m := 64) (0x028#12)).toNat + 4 ≤ tohostAddr ∨ tohostAddr + 8 ≤ (v23 + sign_extend (m := 64) (0x028#12)).toNat)
    : Triple (SegSt (0x8001e934#64) [⟨Register.x27, v27⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x20, v20⟩, ⟨Register.x21, v21⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0 ∧ σ.sailOutput = o0 ∧ Lua.Vm.RegsOk σ)) (SegSt (0x8001bfe4#64) [⟨Register.x21, (sign_extend (m := 64) (Sail.BitVec.extractLsb ((sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4))) + sign_extend (m := 64) (0x000#12)) 31 0))⟩, ⟨Register.x27, (v19 + (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0)))⟩, ⟨Register.x17, (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0))⟩, ⟨Register.x15, ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))⟩, ⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x20, v20⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0 ∧ σ.sailOutput = o0 ∧ Lua.Vm.RegsOk σ)) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq, hout, hok⟩⟩ := hPre
  -- === step 1: 0x8001e934 `site_8001e934` (alu) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_8001e934 c.σ c.tick (c.steps) (0x8001e934#64)
      vmi v27 hgood hpc hmi hp0.1 hloaded rfl hlo_1 hhi_1 hht_1 htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x8001e938#64 : BitVec 64) := by
    have := obs_alu_pc hobs1
    rwa [show BitVec.addInt (0x8001e934#64) 4 = (0x8001e938#64 : BitVec 64) from by decide] at this
  have hrd1 : σ1.regs.get? Register.x17 = some (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) := by
    have := obs_alu_rd hobs1 (by decide) (by decide) (by decide) (by decide) (by decide)
    rwa [hmemeq] at this
  have hp1 : PinsHold σ1 [⟨Register.x17, (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x27, v27⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x20, v20⟩, ⟨Register.x21, v21⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩] :=
    ⟨hrd1, pins_alu hobs1 (by rfl) hp0⟩
  obtain ⟨vmi1, hmi1⟩ := obs_alu_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Lua.Vm.Arms.TextLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  have hout1 : σ1.sailOutput = o0 :=
    (ReadsLikePost.out hobs1).trans hout
  have hok1 : Lua.Vm.RegsOk σ1 :=
    Lua.Vm.RegsOk.alu hobs1 (by decide) hok
  -- === step 2: 0x8001e938 `site_8001e938` (alu) ===
  obtain ⟨σ2, i2, hs2, hi2, hG2, hmem2, hobs2⟩ :=
    site_8001e938 σ1 i1 (c.steps + 1) (0x8001e938#64)
      vmi1 hG1 hpc1 hmi1 hload1 rfl hi1
  have hpc2 : σ2.regs.get? Register.PC = some (0x8001e93c#64 : BitVec 64) := by
    have := obs_alu_pc hobs2
    rwa [show BitVec.addInt (0x8001e938#64) 4 = (0x8001e93c#64 : BitVec 64) from by decide] at this
  have hrd2 : σ2.regs.get? Register.x15 = some (sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) :=
    obs_alu_rd hobs2 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hp2 : PinsHold σ2 [⟨Register.x15, (sign_extend (m := 64) ((0xff000#20) +++ 0x000#12))⟩, ⟨Register.x17, (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x27, v27⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x20, v20⟩, ⟨Register.x21, v21⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩] :=
    ⟨hrd2, pins_alu hobs2 (by rfl) hp1⟩
  obtain ⟨vmi2, hmi2⟩ := obs_alu_minstret hobs2
  have hmemE2 : σ2.mem = m0 := by
    rw [hmem2]; exact hmemE1
  have hload2 : Lua.Vm.Arms.TextLoaded σ2.mem := by
    rw [hmem2]; exact hload1
  have hout2 : σ2.sailOutput = o0 :=
    (ReadsLikePost.out hobs2).trans hout1
  have hok2 : Lua.Vm.RegsOk σ2 :=
    Lua.Vm.RegsOk.alu hobs2 (by decide) hok1
  -- === step 3: 0x8001e93c `site_8001e93c` (alu) ===
  obtain ⟨σ3, i3, hs3, hi3, hG3, hmem3, hobs3⟩ :=
    site_8001e93c σ2 i2 (c.steps + 1 + 1) (0x8001e93c#64)
      vmi2 v23 hG2 hpc2 hmi2 hp2.2.2.2.1 hload2 rfl hlo_3 hhi_3 hht_3 hi2
  have hpc3 : σ3.regs.get? Register.PC = some (0x8001e940#64 : BitVec 64) := by
    have := obs_alu_pc hobs3
    rwa [show BitVec.addInt (0x8001e93c#64) 4 = (0x8001e940#64 : BitVec 64) from by decide] at this
  have hrd3 : σ3.regs.get? Register.x31 = some (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4))) := by
    have := obs_alu_rd hobs3 (by decide) (by decide) (by decide) (by decide) (by decide)
    rwa [hmemE2] at this
  have hp3 : PinsHold σ3 [⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x15, (sign_extend (m := 64) ((0xff000#20) +++ 0x000#12))⟩, ⟨Register.x17, (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x27, v27⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x20, v20⟩, ⟨Register.x21, v21⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩] :=
    ⟨hrd3, pins_alu hobs3 (by rfl) hp2⟩
  obtain ⟨vmi3, hmi3⟩ := obs_alu_minstret hobs3
  have hmemE3 : σ3.mem = m0 := by
    rw [hmem3]; exact hmemE2
  have hload3 : Lua.Vm.Arms.TextLoaded σ3.mem := by
    rw [hmem3]; exact hload2
  have hout3 : σ3.sailOutput = o0 :=
    (ReadsLikePost.out hobs3).trans hout2
  have hok3 : Lua.Vm.RegsOk σ3 :=
    Lua.Vm.RegsOk.alu hobs3 (by decide) hok2
  -- === step 4: 0x8001e940 `site_8001e940` (alu) ===
  obtain ⟨σ4, i4, hs4, hi4, hG4, hmem4, hobs4⟩ :=
    site_8001e940 σ3 i3 (c.steps + 1 + 1 + 1) (0x8001e940#64)
      vmi3 (sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) hG3 hpc3 hmi3 hp3.2.1 hload3 rfl hi3
  have hpc4 : σ4.regs.get? Register.PC = some (0x8001e944#64 : BitVec 64) := by
    have := obs_alu_pc hobs4
    rwa [show BitVec.addInt (0x8001e940#64) 4 = (0x8001e944#64 : BitVec 64) from by decide] at this
  have hrd4 : σ4.regs.get? Register.x15 = some ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12)) :=
    obs_alu_rd hobs4 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hq4 : PinsHold σ3 [⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x17, (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x27, v27⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x20, v20⟩, ⟨Register.x21, v21⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩] :=
    -- discipline: allow(R6-anon-projection-tower) pin-bundle projection emitted by gen_segment.py (the bundle is a PinsHold list)
    ⟨hp3.1, hp3.2.2.1, hp3.2.2.2.1, hp3.2.2.2.2.1, hp3.2.2.2.2.2.1, hp3.2.2.2.2.2.2.1, hp3.2.2.2.2.2.2.2.1, hp3.2.2.2.2.2.2.2.2.1, hp3.2.2.2.2.2.2.2.2.2.1, hp3.2.2.2.2.2.2.2.2.2.2.1, hp3.2.2.2.2.2.2.2.2.2.2.2.1, hp3.2.2.2.2.2.2.2.2.2.2.2.2.1, hp3.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hp3.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, trivial⟩
  have hp4 : PinsHold σ4 [⟨Register.x15, ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))⟩, ⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x17, (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x27, v27⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x20, v20⟩, ⟨Register.x21, v21⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩] :=
    ⟨hrd4, pins_alu hobs4 (by rfl) hq4⟩
  obtain ⟨vmi4, hmi4⟩ := obs_alu_minstret hobs4
  have hmemE4 : σ4.mem = m0 := by
    rw [hmem4]; exact hmemE3
  have hload4 : Lua.Vm.Arms.TextLoaded σ4.mem := by
    rw [hmem4]; exact hload3
  have hout4 : σ4.sailOutput = o0 :=
    (ReadsLikePost.out hobs4).trans hout3
  have hok4 : Lua.Vm.RegsOk σ4 :=
    Lua.Vm.RegsOk.alu hobs4 (by decide) hok3
  -- === step 5: 0x8001e944 `site_8001e944` (alu) ===
  obtain ⟨σ5, i5, hs5, hi5, hG5, hmem5, hobs5⟩ :=
    site_8001e944 σ4 i4 (c.steps + 1 + 1 + 1 + 1) (0x8001e944#64)
      vmi4 (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) hG4 hpc4 hmi4 hp4.2.2.1 hload4 rfl hi4
  have hpc5 : σ5.regs.get? Register.PC = some (0x8001e948#64 : BitVec 64) := by
    have := obs_alu_pc hobs5
    rwa [show BitVec.addInt (0x8001e944#64) 4 = (0x8001e948#64 : BitVec 64) from by decide] at this
  have hrd5 : σ5.regs.get? Register.x17 = some (sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) :=
    obs_alu_rd hobs5 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hq5 : PinsHold σ4 [⟨Register.x15, ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))⟩, ⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x27, v27⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x20, v20⟩, ⟨Register.x21, v21⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩] :=
    -- discipline: allow(R6-anon-projection-tower) pin-bundle projection emitted by gen_segment.py (the bundle is a PinsHold list)
    ⟨hp4.1, hp4.2.1, hp4.2.2.2.1, hp4.2.2.2.2.1, hp4.2.2.2.2.2.1, hp4.2.2.2.2.2.2.1, hp4.2.2.2.2.2.2.2.1, hp4.2.2.2.2.2.2.2.2.1, hp4.2.2.2.2.2.2.2.2.2.1, hp4.2.2.2.2.2.2.2.2.2.2.1, hp4.2.2.2.2.2.2.2.2.2.2.2.1, hp4.2.2.2.2.2.2.2.2.2.2.2.2.1, hp4.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hp4.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, trivial⟩
  have hp5 : PinsHold σ5 [⟨Register.x17, (sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5)))⟩, ⟨Register.x15, ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))⟩, ⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x27, v27⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x20, v20⟩, ⟨Register.x21, v21⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩] :=
    ⟨hrd5, pins_alu hobs5 (by rfl) hq5⟩
  obtain ⟨vmi5, hmi5⟩ := obs_alu_minstret hobs5
  have hmemE5 : σ5.mem = m0 := by
    rw [hmem5]; exact hmemE4
  have hload5 : Lua.Vm.Arms.TextLoaded σ5.mem := by
    rw [hmem5]; exact hload4
  have hout5 : σ5.sailOutput = o0 :=
    (ReadsLikePost.out hobs5).trans hout4
  have hok5 : Lua.Vm.RegsOk σ5 :=
    Lua.Vm.RegsOk.alu hobs5 (by decide) hok4
  -- === step 6: 0x8001e948 `site_8001e948` (alu) ===
  obtain ⟨σ6, i6, hs6, hi6, hG6, hmem6, hobs6⟩ :=
    site_8001e948 σ5 i5 (c.steps + 1 + 1 + 1 + 1 + 1) (0x8001e948#64)
      vmi5 (sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12)) hG5 hpc5 hmi5 hp5.1 hp5.2.1 hload5 rfl hi5
  have hpc6 : σ6.regs.get? Register.PC = some (0x8001e94c#64 : BitVec 64) := by
    have := obs_alu_pc hobs6
    rwa [show BitVec.addInt (0x8001e948#64) 4 = (0x8001e94c#64 : BitVec 64) from by decide] at this
  have hrd6 : σ6.regs.get? Register.x17 = some ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) :=
    obs_alu_rd hobs6 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hq6 : PinsHold σ5 [⟨Register.x15, ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))⟩, ⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x27, v27⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x20, v20⟩, ⟨Register.x21, v21⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩] :=
    -- discipline: allow(R6-anon-projection-tower) pin-bundle projection emitted by gen_segment.py (the bundle is a PinsHold list)
    ⟨hp5.2.1, hp5.2.2.1, hp5.2.2.2.1, hp5.2.2.2.2.1, hp5.2.2.2.2.2.1, hp5.2.2.2.2.2.2.1, hp5.2.2.2.2.2.2.2.1, hp5.2.2.2.2.2.2.2.2.1, hp5.2.2.2.2.2.2.2.2.2.1, hp5.2.2.2.2.2.2.2.2.2.2.1, hp5.2.2.2.2.2.2.2.2.2.2.2.1, hp5.2.2.2.2.2.2.2.2.2.2.2.2.1, hp5.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hp5.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, trivial⟩
  have hp6 : PinsHold σ6 [⟨Register.x17, ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12)))⟩, ⟨Register.x15, ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))⟩, ⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x27, v27⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x20, v20⟩, ⟨Register.x21, v21⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩] :=
    ⟨hrd6, pins_alu hobs6 (by rfl) hq6⟩
  obtain ⟨vmi6, hmi6⟩ := obs_alu_minstret hobs6
  have hmemE6 : σ6.mem = m0 := by
    rw [hmem6]; exact hmemE5
  have hload6 : Lua.Vm.Arms.TextLoaded σ6.mem := by
    rw [hmem6]; exact hload5
  have hout6 : σ6.sailOutput = o0 :=
    (ReadsLikePost.out hobs6).trans hout5
  have hok6 : Lua.Vm.RegsOk σ6 :=
    Lua.Vm.RegsOk.alu hobs6 (by decide) hok5
  -- === step 7: 0x8001e94c `site_8001e94c` (alu) ===
  obtain ⟨σ7, i7, hs7, hi7, hG7, hmem7, hobs7⟩ :=
    site_8001e94c σ6 i6 (c.steps + 1 + 1 + 1 + 1 + 1 + 1) (0x8001e94c#64)
      vmi6 ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) hG6 hpc6 hmi6 hp6.1 hload6 rfl hi6
  have hpc7 : σ7.regs.get? Register.PC = some (0x8001e950#64 : BitVec 64) := by
    have := obs_alu_pc hobs7
    rwa [show BitVec.addInt (0x8001e94c#64) 4 = (0x8001e950#64 : BitVec 64) from by decide] at this
  have hrd7 : σ7.regs.get? Register.x17 = some (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0)) :=
    obs_alu_rd hobs7 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hq7 : PinsHold σ6 [⟨Register.x15, ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))⟩, ⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x27, v27⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x20, v20⟩, ⟨Register.x21, v21⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩] :=
    -- discipline: allow(R6-anon-projection-tower) pin-bundle projection emitted by gen_segment.py (the bundle is a PinsHold list)
    ⟨hp6.2.1, hp6.2.2.1, hp6.2.2.2.1, hp6.2.2.2.2.1, hp6.2.2.2.2.2.1, hp6.2.2.2.2.2.2.1, hp6.2.2.2.2.2.2.2.1, hp6.2.2.2.2.2.2.2.2.1, hp6.2.2.2.2.2.2.2.2.2.1, hp6.2.2.2.2.2.2.2.2.2.2.1, hp6.2.2.2.2.2.2.2.2.2.2.2.1, hp6.2.2.2.2.2.2.2.2.2.2.2.2.1, hp6.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hp6.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, trivial⟩
  have hp7 : PinsHold σ7 [⟨Register.x17, (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0))⟩, ⟨Register.x15, ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))⟩, ⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x27, v27⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x20, v20⟩, ⟨Register.x21, v21⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩] :=
    ⟨hrd7, pins_alu hobs7 (by rfl) hq7⟩
  obtain ⟨vmi7, hmi7⟩ := obs_alu_minstret hobs7
  have hmemE7 : σ7.mem = m0 := by
    rw [hmem7]; exact hmemE6
  have hload7 : Lua.Vm.Arms.TextLoaded σ7.mem := by
    rw [hmem7]; exact hload6
  have hout7 : σ7.sailOutput = o0 :=
    (ReadsLikePost.out hobs7).trans hout6
  have hok7 : Lua.Vm.RegsOk σ7 :=
    Lua.Vm.RegsOk.alu hobs7 (by decide) hok6
  -- === step 8: 0x8001e950 `site_8001e950` (alu) ===
  obtain ⟨σ8, i8, hs8, hi8, hG8, hmem8, hobs8⟩ :=
    site_8001e950 σ7 i7 (c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1) (0x8001e950#64)
      -- discipline: allow(R6-anon-projection-tower) pin-bundle projection emitted by gen_segment.py (the bundle is a PinsHold list)
      vmi7 v19 (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0)) hG7 hpc7 hmi7 hp7.2.2.2.2.2.1 hp7.1 hload7 rfl hi7
  have hpc8 : σ8.regs.get? Register.PC = some (0x8001e954#64 : BitVec 64) := by
    have := obs_alu_pc hobs8
    rwa [show BitVec.addInt (0x8001e950#64) 4 = (0x8001e954#64 : BitVec 64) from by decide] at this
  have hrd8 : σ8.regs.get? Register.x27 = some (v19 + (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0))) :=
    obs_alu_rd hobs8 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hq8 : PinsHold σ7 [⟨Register.x17, (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0))⟩, ⟨Register.x15, ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))⟩, ⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x20, v20⟩, ⟨Register.x21, v21⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩] :=
    -- discipline: allow(R6-anon-projection-tower) pin-bundle projection emitted by gen_segment.py (the bundle is a PinsHold list)
    ⟨hp7.1, hp7.2.1, hp7.2.2.1, hp7.2.2.2.2.1, hp7.2.2.2.2.2.1, hp7.2.2.2.2.2.2.1, hp7.2.2.2.2.2.2.2.1, hp7.2.2.2.2.2.2.2.2.1, hp7.2.2.2.2.2.2.2.2.2.1, hp7.2.2.2.2.2.2.2.2.2.2.1, hp7.2.2.2.2.2.2.2.2.2.2.2.1, hp7.2.2.2.2.2.2.2.2.2.2.2.2.1, hp7.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hp7.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, trivial⟩
  have hp8 : PinsHold σ8 [⟨Register.x27, (v19 + (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0)))⟩, ⟨Register.x17, (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0))⟩, ⟨Register.x15, ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))⟩, ⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x20, v20⟩, ⟨Register.x21, v21⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩] :=
    ⟨hrd8, pins_alu hobs8 (by rfl) hq8⟩
  obtain ⟨vmi8, hmi8⟩ := obs_alu_minstret hobs8
  have hmemE8 : σ8.mem = m0 := by
    rw [hmem8]; exact hmemE7
  have hload8 : Lua.Vm.Arms.TextLoaded σ8.mem := by
    rw [hmem8]; exact hload7
  have hout8 : σ8.sailOutput = o0 :=
    (ReadsLikePost.out hobs8).trans hout7
  have hok8 : Lua.Vm.RegsOk σ8 :=
    Lua.Vm.RegsOk.alu hobs8 (by decide) hok7
  -- === step 9: 0x8001e954 `site_8001e954` (alu) ===
  obtain ⟨σ9, i9, hs9, hi9, hG9, hmem9, hobs9⟩ :=
    site_8001e954 σ8 i8 (c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1) (0x8001e954#64)
      vmi8 (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4))) hG8 hpc8 hmi8 hp8.2.2.2.1 hload8 rfl hi8
  have hpc9 : σ9.regs.get? Register.PC = some (0x8001e958#64 : BitVec 64) := by
    have := obs_alu_pc hobs9
    rwa [show BitVec.addInt (0x8001e954#64) 4 = (0x8001e958#64 : BitVec 64) from by decide] at this
  have hrd9 : σ9.regs.get? Register.x21 = some (sign_extend (m := 64) (Sail.BitVec.extractLsb ((sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4))) + sign_extend (m := 64) (0x000#12)) 31 0)) :=
    obs_alu_rd hobs9 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hq9 : PinsHold σ8 [⟨Register.x27, (v19 + (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0)))⟩, ⟨Register.x17, (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0))⟩, ⟨Register.x15, ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))⟩, ⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x20, v20⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩] :=
    -- discipline: allow(R6-anon-projection-tower) pin-bundle projection emitted by gen_segment.py (the bundle is a PinsHold list)
    ⟨hp8.1, hp8.2.1, hp8.2.2.1, hp8.2.2.2.1, hp8.2.2.2.2.1, hp8.2.2.2.2.2.1, hp8.2.2.2.2.2.2.1, hp8.2.2.2.2.2.2.2.1, hp8.2.2.2.2.2.2.2.2.1, hp8.2.2.2.2.2.2.2.2.2.1, hp8.2.2.2.2.2.2.2.2.2.2.1, hp8.2.2.2.2.2.2.2.2.2.2.2.1, hp8.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hp8.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, trivial⟩
  have hp9 : PinsHold σ9 [⟨Register.x21, (sign_extend (m := 64) (Sail.BitVec.extractLsb ((sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4))) + sign_extend (m := 64) (0x000#12)) 31 0))⟩, ⟨Register.x27, (v19 + (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0)))⟩, ⟨Register.x17, (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0))⟩, ⟨Register.x15, ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))⟩, ⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x20, v20⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩] :=
    ⟨hrd9, pins_alu hobs9 (by rfl) hq9⟩
  obtain ⟨vmi9, hmi9⟩ := obs_alu_minstret hobs9
  have hmemE9 : σ9.mem = m0 := by
    rw [hmem9]; exact hmemE8
  have hload9 : Lua.Vm.Arms.TextLoaded σ9.mem := by
    rw [hmem9]; exact hload8
  have hout9 : σ9.sailOutput = o0 :=
    (ReadsLikePost.out hobs9).trans hout8
  have hok9 : Lua.Vm.RegsOk σ9 :=
    Lua.Vm.RegsOk.alu hobs9 (by decide) hok8
  -- === step 10: 0x8001e958 `site_8001e958` (j) ===
  obtain ⟨σ10, i10, hs10, hi10, hG10, hmem10, hobs10⟩ :=
    site_8001e958 σ9 i9 (c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1) (0x8001e958#64)
      vmi9 hG9 hpc9 hmi9 hload9 rfl (by decide) hi9
  have hpc10 : σ10.regs.get? Register.PC = some (0x8001bfe4#64 : BitVec 64) := by
    rw [obs_jr_pc hobs10,
      show (0x8001e958#64 : BitVec 64) + sign_extend (m := 64) (0x1fd68c#21) = (0x8001bfe4#64 : BitVec 64) from by apply BitVec.eq_of_toNat_eq; decide]
  have hp10 : PinsHold σ10 [⟨Register.x21, (sign_extend (m := 64) (Sail.BitVec.extractLsb ((sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4))) + sign_extend (m := 64) (0x000#12)) 31 0))⟩, ⟨Register.x27, (v19 + (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0)))⟩, ⟨Register.x17, (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0))⟩, ⟨Register.x15, ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))⟩, ⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x20, v20⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩] :=
    pins_jr hobs10 (by rfl) hp9
  obtain ⟨vmi10, hmi10⟩ := obs_jr_minstret hobs10
  have hmemE10 : σ10.mem = m0 := by
    rw [hmem10]; exact hmemE9
  have hload10 : Lua.Vm.Arms.TextLoaded σ10.mem := by
    rw [hmem10]; exact hload9
  have hout10 : σ10.sailOutput = o0 :=
    (ReadsLikePost.out hobs10).trans hout9
  have hok10 : Lua.Vm.RegsOk σ10 :=
    Lua.Vm.RegsOk.jr hobs10 hok9
  have hsteps10 : Steps c ⟨σ10, i10, c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1⟩ :=
    (((((((((Steps.single hs1).trans (Steps.single hs2)).trans (Steps.single hs3)).trans (Steps.single hs4)).trans (Steps.single hs5)).trans (Steps.single hs6)).trans (Steps.single hs7)).trans (Steps.single hs8)).trans (Steps.single hs9)).trans (Steps.single hs10)
  exact ⟨⟨σ10, i10, c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1⟩, hsteps10,
    ⟨hG10, hpc10, hp10, ⟨vmi10, hmi10⟩, hi10, ⟨hload10, hmemE10, hout10, hok10⟩⟩⟩

/-- `0x8001e95c`–`0x8001e96c` (4 instructions), from `SegSt` to `SegSt`; side conditions are the `h*_<step>` hypotheses. -/
theorem seg_8001e95c_8001e96c
    (v22 v10 v2 v3 v8 v9 v18 v19 v20 v21 v23 v24 v25 v27 : BitVec 64)
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    (o0 : Array String)
    (hlo_1 : 0x80000000 ≤ (v22 + sign_extend (m := 64) (0x000#12)).toNat)
    (hhi_1 : (v22 + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ 0x100000000)
    (hht_1 : (v22 + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ tohostAddr ∨ tohostAddr + 8 ≤ (v22 + sign_extend (m := 64) (0x000#12)).toNat)
    : Triple (SegSt (0x8001e95c#64) [⟨Register.x22, v22⟩, ⟨Register.x10, v10⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x19, v19⟩, ⟨Register.x20, v20⟩, ⟨Register.x21, v21⟩, ⟨Register.x23, v23⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩, ⟨Register.x27, v27⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0 ∧ σ.sailOutput = o0 ∧ Lua.Vm.RegsOk σ)) (SegSt (0x8001c594#64) [⟨Register.x10, (zero_extend (m := 64) (bool_to_bit (zopz0zI_u (zero_extend (m := 64) (bool_to_bit (zopz0zI_s (sign_extend (m := 64) (bytesT8 (m0) (v22 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))) v10))) (sign_extend (m := 64) (0x001#12)))))⟩, ⟨Register.x15, (zero_extend (m := 64) (bool_to_bit (zopz0zI_s (sign_extend (m := 64) (bytesT8 (m0) (v22 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))) v10)))⟩, ⟨Register.x22, v22⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x19, v19⟩, ⟨Register.x20, v20⟩, ⟨Register.x21, v21⟩, ⟨Register.x23, v23⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩, ⟨Register.x27, v27⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0 ∧ σ.sailOutput = o0 ∧ Lua.Vm.RegsOk σ)) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq, hout, hok⟩⟩ := hPre
  -- === step 1: 0x8001e95c `site_8001e95c` (alu) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_8001e95c c.σ c.tick (c.steps) (0x8001e95c#64)
      vmi v22 hgood hpc hmi hp0.1 hloaded rfl hlo_1 hhi_1 hht_1 htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x8001e960#64 : BitVec 64) := by
    have := obs_alu_pc hobs1
    rwa [show BitVec.addInt (0x8001e95c#64) 4 = (0x8001e960#64 : BitVec 64) from by decide] at this
  have hrd1 : σ1.regs.get? Register.x15 = some (sign_extend (m := 64) (bytesT8 (m0) (v22 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))) := by
    have := obs_alu_rd hobs1 (by decide) (by decide) (by decide) (by decide) (by decide)
    rwa [hmemeq] at this
  have hp1 : PinsHold σ1 [⟨Register.x15, (sign_extend (m := 64) (bytesT8 (m0) (v22 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8)))⟩, ⟨Register.x22, v22⟩, ⟨Register.x10, v10⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x19, v19⟩, ⟨Register.x20, v20⟩, ⟨Register.x21, v21⟩, ⟨Register.x23, v23⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩, ⟨Register.x27, v27⟩] :=
    ⟨hrd1, pins_alu hobs1 (by rfl) hp0⟩
  obtain ⟨vmi1, hmi1⟩ := obs_alu_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Lua.Vm.Arms.TextLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  have hout1 : σ1.sailOutput = o0 :=
    (ReadsLikePost.out hobs1).trans hout
  have hok1 : Lua.Vm.RegsOk σ1 :=
    Lua.Vm.RegsOk.alu hobs1 (by decide) hok
  -- === step 2: 0x8001e960 `site_8001e960` (alu) ===
  obtain ⟨σ2, i2, hs2, hi2, hG2, hmem2, hobs2⟩ :=
    site_8001e960 σ1 i1 (c.steps + 1) (0x8001e960#64)
      vmi1 (sign_extend (m := 64) (bytesT8 (m0) (v22 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))) v10 hG1 hpc1 hmi1 hp1.1 hp1.2.2.1 hload1 rfl hi1
  have hpc2 : σ2.regs.get? Register.PC = some (0x8001e964#64 : BitVec 64) := by
    have := obs_alu_pc hobs2
    rwa [show BitVec.addInt (0x8001e960#64) 4 = (0x8001e964#64 : BitVec 64) from by decide] at this
  have hrd2 : σ2.regs.get? Register.x15 = some (zero_extend (m := 64) (bool_to_bit (zopz0zI_s (sign_extend (m := 64) (bytesT8 (m0) (v22 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))) v10))) :=
    obs_alu_rd hobs2 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hq2 : PinsHold σ1 [⟨Register.x22, v22⟩, ⟨Register.x10, v10⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x19, v19⟩, ⟨Register.x20, v20⟩, ⟨Register.x21, v21⟩, ⟨Register.x23, v23⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩, ⟨Register.x27, v27⟩] :=
    -- discipline: allow(R6-anon-projection-tower) pin-bundle projection emitted by gen_segment.py (the bundle is a PinsHold list)
    ⟨hp1.2.1, hp1.2.2.1, hp1.2.2.2.1, hp1.2.2.2.2.1, hp1.2.2.2.2.2.1, hp1.2.2.2.2.2.2.1, hp1.2.2.2.2.2.2.2.1, hp1.2.2.2.2.2.2.2.2.1, hp1.2.2.2.2.2.2.2.2.2.1, hp1.2.2.2.2.2.2.2.2.2.2.1, hp1.2.2.2.2.2.2.2.2.2.2.2.1, hp1.2.2.2.2.2.2.2.2.2.2.2.2.1, hp1.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hp1.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, trivial⟩
  have hp2 : PinsHold σ2 [⟨Register.x15, (zero_extend (m := 64) (bool_to_bit (zopz0zI_s (sign_extend (m := 64) (bytesT8 (m0) (v22 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))) v10)))⟩, ⟨Register.x22, v22⟩, ⟨Register.x10, v10⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x19, v19⟩, ⟨Register.x20, v20⟩, ⟨Register.x21, v21⟩, ⟨Register.x23, v23⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩, ⟨Register.x27, v27⟩] :=
    ⟨hrd2, pins_alu hobs2 (by rfl) hq2⟩
  obtain ⟨vmi2, hmi2⟩ := obs_alu_minstret hobs2
  have hmemE2 : σ2.mem = m0 := by
    rw [hmem2]; exact hmemE1
  have hload2 : Lua.Vm.Arms.TextLoaded σ2.mem := by
    rw [hmem2]; exact hload1
  have hout2 : σ2.sailOutput = o0 :=
    (ReadsLikePost.out hobs2).trans hout1
  have hok2 : Lua.Vm.RegsOk σ2 :=
    Lua.Vm.RegsOk.alu hobs2 (by decide) hok1
  -- === step 3: 0x8001e964 `site_8001e964` (alu) ===
  obtain ⟨σ3, i3, hs3, hi3, hG3, hmem3, hobs3⟩ :=
    site_8001e964 σ2 i2 (c.steps + 1 + 1) (0x8001e964#64)
      vmi2 (zero_extend (m := 64) (bool_to_bit (zopz0zI_s (sign_extend (m := 64) (bytesT8 (m0) (v22 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))) v10))) hG2 hpc2 hmi2 hp2.1 hload2 rfl hi2
  have hpc3 : σ3.regs.get? Register.PC = some (0x8001e968#64 : BitVec 64) := by
    have := obs_alu_pc hobs3
    rwa [show BitVec.addInt (0x8001e964#64) 4 = (0x8001e968#64 : BitVec 64) from by decide] at this
  have hrd3 : σ3.regs.get? Register.x10 = some (zero_extend (m := 64) (bool_to_bit (zopz0zI_u (zero_extend (m := 64) (bool_to_bit (zopz0zI_s (sign_extend (m := 64) (bytesT8 (m0) (v22 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))) v10))) (sign_extend (m := 64) (0x001#12))))) :=
    obs_alu_rd hobs3 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hq3 : PinsHold σ2 [⟨Register.x15, (zero_extend (m := 64) (bool_to_bit (zopz0zI_s (sign_extend (m := 64) (bytesT8 (m0) (v22 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))) v10)))⟩, ⟨Register.x22, v22⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x19, v19⟩, ⟨Register.x20, v20⟩, ⟨Register.x21, v21⟩, ⟨Register.x23, v23⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩, ⟨Register.x27, v27⟩] :=
    -- discipline: allow(R6-anon-projection-tower) pin-bundle projection emitted by gen_segment.py (the bundle is a PinsHold list)
    ⟨hp2.1, hp2.2.1, hp2.2.2.2.1, hp2.2.2.2.2.1, hp2.2.2.2.2.2.1, hp2.2.2.2.2.2.2.1, hp2.2.2.2.2.2.2.2.1, hp2.2.2.2.2.2.2.2.2.1, hp2.2.2.2.2.2.2.2.2.2.1, hp2.2.2.2.2.2.2.2.2.2.2.1, hp2.2.2.2.2.2.2.2.2.2.2.2.1, hp2.2.2.2.2.2.2.2.2.2.2.2.2.1, hp2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hp2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, trivial⟩
  have hp3 : PinsHold σ3 [⟨Register.x10, (zero_extend (m := 64) (bool_to_bit (zopz0zI_u (zero_extend (m := 64) (bool_to_bit (zopz0zI_s (sign_extend (m := 64) (bytesT8 (m0) (v22 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))) v10))) (sign_extend (m := 64) (0x001#12)))))⟩, ⟨Register.x15, (zero_extend (m := 64) (bool_to_bit (zopz0zI_s (sign_extend (m := 64) (bytesT8 (m0) (v22 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))) v10)))⟩, ⟨Register.x22, v22⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x19, v19⟩, ⟨Register.x20, v20⟩, ⟨Register.x21, v21⟩, ⟨Register.x23, v23⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩, ⟨Register.x27, v27⟩] :=
    ⟨hrd3, pins_alu hobs3 (by rfl) hq3⟩
  obtain ⟨vmi3, hmi3⟩ := obs_alu_minstret hobs3
  have hmemE3 : σ3.mem = m0 := by
    rw [hmem3]; exact hmemE2
  have hload3 : Lua.Vm.Arms.TextLoaded σ3.mem := by
    rw [hmem3]; exact hload2
  have hout3 : σ3.sailOutput = o0 :=
    (ReadsLikePost.out hobs3).trans hout2
  have hok3 : Lua.Vm.RegsOk σ3 :=
    Lua.Vm.RegsOk.alu hobs3 (by decide) hok2
  -- === step 4: 0x8001e968 `site_8001e968` (j) ===
  obtain ⟨σ4, i4, hs4, hi4, hG4, hmem4, hobs4⟩ :=
    site_8001e968 σ3 i3 (c.steps + 1 + 1 + 1) (0x8001e968#64)
      vmi3 hG3 hpc3 hmi3 hload3 rfl (by decide) hi3
  have hpc4 : σ4.regs.get? Register.PC = some (0x8001c594#64 : BitVec 64) := by
    rw [obs_jr_pc hobs4,
      show (0x8001e968#64 : BitVec 64) + sign_extend (m := 64) (0x1fdc2c#21) = (0x8001c594#64 : BitVec 64) from by apply BitVec.eq_of_toNat_eq; decide]
  have hp4 : PinsHold σ4 [⟨Register.x10, (zero_extend (m := 64) (bool_to_bit (zopz0zI_u (zero_extend (m := 64) (bool_to_bit (zopz0zI_s (sign_extend (m := 64) (bytesT8 (m0) (v22 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))) v10))) (sign_extend (m := 64) (0x001#12)))))⟩, ⟨Register.x15, (zero_extend (m := 64) (bool_to_bit (zopz0zI_s (sign_extend (m := 64) (bytesT8 (m0) (v22 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))) v10)))⟩, ⟨Register.x22, v22⟩, ⟨Register.x2, v2⟩, ⟨Register.x3, v3⟩, ⟨Register.x8, v8⟩, ⟨Register.x9, v9⟩, ⟨Register.x18, v18⟩, ⟨Register.x19, v19⟩, ⟨Register.x20, v20⟩, ⟨Register.x21, v21⟩, ⟨Register.x23, v23⟩, ⟨Register.x24, v24⟩, ⟨Register.x25, v25⟩, ⟨Register.x27, v27⟩] :=
    pins_jr hobs4 (by rfl) hp3
  obtain ⟨vmi4, hmi4⟩ := obs_jr_minstret hobs4
  have hmemE4 : σ4.mem = m0 := by
    rw [hmem4]; exact hmemE3
  have hload4 : Lua.Vm.Arms.TextLoaded σ4.mem := by
    rw [hmem4]; exact hload3
  have hout4 : σ4.sailOutput = o0 :=
    (ReadsLikePost.out hobs4).trans hout3
  have hok4 : Lua.Vm.RegsOk σ4 :=
    Lua.Vm.RegsOk.jr hobs4 hok3
  have hsteps4 : Steps c ⟨σ4, i4, c.steps + 1 + 1 + 1 + 1⟩ :=
    (((Steps.single hs1).trans (Steps.single hs2)).trans (Steps.single hs3)).trans (Steps.single hs4)
  exact ⟨⟨σ4, i4, c.steps + 1 + 1 + 1 + 1⟩, hsteps4,
    ⟨hG4, hpc4, hp4, ⟨vmi4, hmi4⟩, hi4, ⟨hload4, hmemE4, hout4, hok4⟩⟩⟩

/-- `0x8001e96c`–`0x8001e974` (2 instructions), from `SegSt` to `SegSt`; side conditions are the `h*_<step>` hypotheses. -/
theorem seg_8001e96c_8001e974_n
    (v26 v18 : BitVec 64)
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    (hlo_1 : 0x80000000 ≤ (v26 + sign_extend (m := 64) (0x008#12)).toNat)
    (hhi_1 : (v26 + sign_extend (m := 64) (0x008#12)).toNat + 1 ≤ 0x100000000)
    (hht_1 : (v26 + sign_extend (m := 64) (0x008#12)).toNat + 1 ≤ tohostAddr ∨ tohostAddr + 8 ≤ (v26 + sign_extend (m := 64) (0x008#12)).toNat)
    (hg_2 : ((zero_extend (m := 64) (bytesT1 (m0) (v26 + sign_extend (m := 64) (0x008#12)).toNat : BitVec (8 * 1))) == v18) = false)
    : Triple (SegSt (0x8001e96c#64) [⟨Register.x26, v26⟩, ⟨Register.x18, v18⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) (SegSt (0x8001e974#64) [⟨Register.x15, (zero_extend (m := 64) (bytesT1 (m0) (v26 + sign_extend (m := 64) (0x008#12)).toNat : BitVec (8 * 1)))⟩, ⟨Register.x26, v26⟩, ⟨Register.x18, v18⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq⟩⟩ := hPre
  -- === step 1: 0x8001e96c `site_8001e96c` (alu) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_8001e96c c.σ c.tick (c.steps) (0x8001e96c#64)
      vmi v26 hgood hpc hmi hp0.1 hloaded rfl hlo_1 hhi_1 hht_1 htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x8001e970#64 : BitVec 64) := by
    have := obs_alu_pc hobs1
    rwa [show BitVec.addInt (0x8001e96c#64) 4 = (0x8001e970#64 : BitVec 64) from by decide] at this
  have hrd1 : σ1.regs.get? Register.x15 = some (zero_extend (m := 64) (bytesT1 (m0) (v26 + sign_extend (m := 64) (0x008#12)).toNat : BitVec (8 * 1))) := by
    have := obs_alu_rd hobs1 (by decide) (by decide) (by decide) (by decide) (by decide)
    rwa [hmemeq] at this
  have hp1 : PinsHold σ1 [⟨Register.x15, (zero_extend (m := 64) (bytesT1 (m0) (v26 + sign_extend (m := 64) (0x008#12)).toNat : BitVec (8 * 1)))⟩, ⟨Register.x26, v26⟩, ⟨Register.x18, v18⟩] :=
    ⟨hrd1, pins_alu hobs1 (by rfl) hp0⟩
  obtain ⟨vmi1, hmi1⟩ := obs_alu_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Lua.Vm.Arms.TextLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  -- === step 2: 0x8001e970 `site_8001e970_nottaken` (bnottaken) ===
  obtain ⟨σ2, i2, hs2, hi2, hG2, hmem2, hobs2⟩ :=
    site_8001e970_nottaken σ1 i1 (c.steps + 1) (0x8001e970#64)
      vmi1 (zero_extend (m := 64) (bytesT1 (m0) (v26 + sign_extend (m := 64) (0x008#12)).toNat : BitVec (8 * 1))) v18 hG1 hpc1 hmi1 hp1.1 hp1.2.2.1 hload1 rfl hg_2 hi1
  have hpc2 : σ2.regs.get? Register.PC = some (0x8001e974#64 : BitVec 64) := by
    have := obs_bnottaken_pc hobs2
    rwa [show BitVec.addInt (0x8001e970#64) 4 = (0x8001e974#64 : BitVec 64) from by decide] at this
  have hp2 : PinsHold σ2 [⟨Register.x15, (zero_extend (m := 64) (bytesT1 (m0) (v26 + sign_extend (m := 64) (0x008#12)).toNat : BitVec (8 * 1)))⟩, ⟨Register.x26, v26⟩, ⟨Register.x18, v18⟩] :=
    pins_bnottaken hobs2 (by rfl) hp1
  obtain ⟨vmi2, hmi2⟩ := obs_bnottaken_minstret hobs2
  have hmemE2 : σ2.mem = m0 := by
    rw [hmem2]; exact hmemE1
  have hload2 : Lua.Vm.Arms.TextLoaded σ2.mem := by
    rw [hmem2]; exact hload1
  have hsteps2 : Steps c ⟨σ2, i2, c.steps + 1 + 1⟩ :=
    (Steps.single hs1).trans (Steps.single hs2)
  exact ⟨⟨σ2, i2, c.steps + 1 + 1⟩, hsteps2,
    ⟨hG2, hpc2, hp2, ⟨vmi2, hmi2⟩, hi2, ⟨hload2, hmemE2⟩⟩⟩

/-- `0x8001e96c`–`0x8001e974` (2 instructions), from `SegSt` to `SegSt`; side conditions are the `h*_<step>` hypotheses. -/
theorem seg_8001e96c_8001e974_t
    (v26 v18 : BitVec 64)
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    (hlo_1 : 0x80000000 ≤ (v26 + sign_extend (m := 64) (0x008#12)).toNat)
    (hhi_1 : (v26 + sign_extend (m := 64) (0x008#12)).toNat + 1 ≤ 0x100000000)
    (hht_1 : (v26 + sign_extend (m := 64) (0x008#12)).toNat + 1 ≤ tohostAddr ∨ tohostAddr + 8 ≤ (v26 + sign_extend (m := 64) (0x008#12)).toNat)
    (hg_2 : ((zero_extend (m := 64) (bytesT1 (m0) (v26 + sign_extend (m := 64) (0x008#12)).toNat : BitVec (8 * 1))) == v18) = true)
    : Triple (SegSt (0x8001e96c#64) [⟨Register.x26, v26⟩, ⟨Register.x18, v18⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) (SegSt (0x8001effc#64) [⟨Register.x15, (zero_extend (m := 64) (bytesT1 (m0) (v26 + sign_extend (m := 64) (0x008#12)).toNat : BitVec (8 * 1)))⟩, ⟨Register.x26, v26⟩, ⟨Register.x18, v18⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq⟩⟩ := hPre
  -- === step 1: 0x8001e96c `site_8001e96c` (alu) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_8001e96c c.σ c.tick (c.steps) (0x8001e96c#64)
      vmi v26 hgood hpc hmi hp0.1 hloaded rfl hlo_1 hhi_1 hht_1 htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x8001e970#64 : BitVec 64) := by
    have := obs_alu_pc hobs1
    rwa [show BitVec.addInt (0x8001e96c#64) 4 = (0x8001e970#64 : BitVec 64) from by decide] at this
  have hrd1 : σ1.regs.get? Register.x15 = some (zero_extend (m := 64) (bytesT1 (m0) (v26 + sign_extend (m := 64) (0x008#12)).toNat : BitVec (8 * 1))) := by
    have := obs_alu_rd hobs1 (by decide) (by decide) (by decide) (by decide) (by decide)
    rwa [hmemeq] at this
  have hp1 : PinsHold σ1 [⟨Register.x15, (zero_extend (m := 64) (bytesT1 (m0) (v26 + sign_extend (m := 64) (0x008#12)).toNat : BitVec (8 * 1)))⟩, ⟨Register.x26, v26⟩, ⟨Register.x18, v18⟩] :=
    ⟨hrd1, pins_alu hobs1 (by rfl) hp0⟩
  obtain ⟨vmi1, hmi1⟩ := obs_alu_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Lua.Vm.Arms.TextLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  -- === step 2: 0x8001e970 `site_8001e970_taken` (btaken) ===
  obtain ⟨σ2, i2, hs2, hi2, hG2, hmem2, hobs2⟩ :=
    site_8001e970_taken σ1 i1 (c.steps + 1) (0x8001e970#64)
      vmi1 (zero_extend (m := 64) (bytesT1 (m0) (v26 + sign_extend (m := 64) (0x008#12)).toNat : BitVec (8 * 1))) v18 hG1 hpc1 hmi1 hp1.1 hp1.2.2.1 hload1 rfl hg_2 hi1
  have hpc2 : σ2.regs.get? Register.PC = some (0x8001effc#64 : BitVec 64) := by
    rw [obs_btaken_pc hobs2,
      show (0x8001e970#64 : BitVec 64) + sign_extend (m := 64) (0x068c#13) = (0x8001effc#64 : BitVec 64) from by apply BitVec.eq_of_toNat_eq; decide]
  have hp2 : PinsHold σ2 [⟨Register.x15, (zero_extend (m := 64) (bytesT1 (m0) (v26 + sign_extend (m := 64) (0x008#12)).toNat : BitVec (8 * 1)))⟩, ⟨Register.x26, v26⟩, ⟨Register.x18, v18⟩] :=
    pins_btaken hobs2 (by rfl) hp1
  obtain ⟨vmi2, hmi2⟩ := obs_btaken_minstret hobs2
  have hmemE2 : σ2.mem = m0 := by
    rw [hmem2]; exact hmemE1
  have hload2 : Lua.Vm.Arms.TextLoaded σ2.mem := by
    rw [hmem2]; exact hload1
  have hsteps2 : Steps c ⟨σ2, i2, c.steps + 1 + 1⟩ :=
    (Steps.single hs1).trans (Steps.single hs2)
  exact ⟨⟨σ2, i2, c.steps + 1 + 1⟩, hsteps2,
    ⟨hG2, hpc2, hp2, ⟨vmi2, hmi2⟩, hi2, ⟨hload2, hmemE2⟩⟩⟩

/-- `0x8001e974`–`0x8001e97c` (2 instructions), from `SegSt` to `SegSt`; side conditions are the `h*_<step>` hypotheses. -/
theorem seg_8001e974_8001e97c_n
    (v15 : BitVec 64)
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    (hg_2 : (v15 != ((0#64) + sign_extend (m := 64) (0x013#12))) = false)
    : Triple (SegSt (0x8001e974#64) [⟨Register.x15, v15⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) (SegSt (0x8001e97c#64) [⟨Register.x13, ((0#64) + sign_extend (m := 64) (0x013#12))⟩, ⟨Register.x15, v15⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq⟩⟩ := hPre
  -- === step 1: 0x8001e974 `site_8001e974` (alu) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_8001e974 c.σ c.tick (c.steps) (0x8001e974#64)
      vmi hgood hpc hmi hloaded rfl htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x8001e978#64 : BitVec 64) := by
    have := obs_alu_pc hobs1
    rwa [show BitVec.addInt (0x8001e974#64) 4 = (0x8001e978#64 : BitVec 64) from by decide] at this
  have hrd1 : σ1.regs.get? Register.x13 = some ((0#64) + sign_extend (m := 64) (0x013#12)) :=
    obs_alu_rd hobs1 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hp1 : PinsHold σ1 [⟨Register.x13, ((0#64) + sign_extend (m := 64) (0x013#12))⟩, ⟨Register.x15, v15⟩] :=
    ⟨hrd1, pins_alu hobs1 (by rfl) hp0⟩
  obtain ⟨vmi1, hmi1⟩ := obs_alu_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Lua.Vm.Arms.TextLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  -- === step 2: 0x8001e978 `site_8001e978_nottaken` (bnottaken) ===
  obtain ⟨σ2, i2, hs2, hi2, hG2, hmem2, hobs2⟩ :=
    site_8001e978_nottaken σ1 i1 (c.steps + 1) (0x8001e978#64)
      vmi1 v15 ((0#64) + sign_extend (m := 64) (0x013#12)) hG1 hpc1 hmi1 hp1.2.1 hp1.1 hload1 rfl hg_2 hi1
  have hpc2 : σ2.regs.get? Register.PC = some (0x8001e97c#64 : BitVec 64) := by
    have := obs_bnottaken_pc hobs2
    rwa [show BitVec.addInt (0x8001e978#64) 4 = (0x8001e97c#64 : BitVec 64) from by decide] at this
  have hp2 : PinsHold σ2 [⟨Register.x13, ((0#64) + sign_extend (m := 64) (0x013#12))⟩, ⟨Register.x15, v15⟩] :=
    pins_bnottaken hobs2 (by rfl) hp1
  obtain ⟨vmi2, hmi2⟩ := obs_bnottaken_minstret hobs2
  have hmemE2 : σ2.mem = m0 := by
    rw [hmem2]; exact hmemE1
  have hload2 : Lua.Vm.Arms.TextLoaded σ2.mem := by
    rw [hmem2]; exact hload1
  have hsteps2 : Steps c ⟨σ2, i2, c.steps + 1 + 1⟩ :=
    (Steps.single hs1).trans (Steps.single hs2)
  exact ⟨⟨σ2, i2, c.steps + 1 + 1⟩, hsteps2,
    ⟨hG2, hpc2, hp2, ⟨vmi2, hmi2⟩, hi2, ⟨hload2, hmemE2⟩⟩⟩

/-- `0x8001e974`–`0x8001e97c` (2 instructions), from `SegSt` to `SegSt`; side conditions are the `h*_<step>` hypotheses. -/
theorem seg_8001e974_8001e97c_t
    (v15 : BitVec 64)
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    (hg_2 : (v15 != ((0#64) + sign_extend (m := 64) (0x013#12))) = true)
    : Triple (SegSt (0x8001e974#64) [⟨Register.x15, v15⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) (SegSt (0x8001e43c#64) [⟨Register.x13, ((0#64) + sign_extend (m := 64) (0x013#12))⟩, ⟨Register.x15, v15⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq⟩⟩ := hPre
  -- === step 1: 0x8001e974 `site_8001e974` (alu) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_8001e974 c.σ c.tick (c.steps) (0x8001e974#64)
      vmi hgood hpc hmi hloaded rfl htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x8001e978#64 : BitVec 64) := by
    have := obs_alu_pc hobs1
    rwa [show BitVec.addInt (0x8001e974#64) 4 = (0x8001e978#64 : BitVec 64) from by decide] at this
  have hrd1 : σ1.regs.get? Register.x13 = some ((0#64) + sign_extend (m := 64) (0x013#12)) :=
    obs_alu_rd hobs1 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hp1 : PinsHold σ1 [⟨Register.x13, ((0#64) + sign_extend (m := 64) (0x013#12))⟩, ⟨Register.x15, v15⟩] :=
    ⟨hrd1, pins_alu hobs1 (by rfl) hp0⟩
  obtain ⟨vmi1, hmi1⟩ := obs_alu_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Lua.Vm.Arms.TextLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  -- === step 2: 0x8001e978 `site_8001e978_taken` (btaken) ===
  obtain ⟨σ2, i2, hs2, hi2, hG2, hmem2, hobs2⟩ :=
    site_8001e978_taken σ1 i1 (c.steps + 1) (0x8001e978#64)
      vmi1 v15 ((0#64) + sign_extend (m := 64) (0x013#12)) hG1 hpc1 hmi1 hp1.2.1 hp1.1 hload1 rfl hg_2 hi1
  have hpc2 : σ2.regs.get? Register.PC = some (0x8001e43c#64 : BitVec 64) := by
    rw [obs_btaken_pc hobs2,
      show (0x8001e978#64 : BitVec 64) + sign_extend (m := 64) (0x1ac4#13) = (0x8001e43c#64 : BitVec 64) from by apply BitVec.eq_of_toNat_eq; decide]
  have hp2 : PinsHold σ2 [⟨Register.x13, ((0#64) + sign_extend (m := 64) (0x013#12))⟩, ⟨Register.x15, v15⟩] :=
    pins_btaken hobs2 (by rfl) hp1
  obtain ⟨vmi2, hmi2⟩ := obs_btaken_minstret hobs2
  have hmemE2 : σ2.mem = m0 := by
    rw [hmem2]; exact hmemE1
  have hload2 : Lua.Vm.Arms.TextLoaded σ2.mem := by
    rw [hmem2]; exact hload1
  have hsteps2 : Steps c ⟨σ2, i2, c.steps + 1 + 1⟩ :=
    (Steps.single hs1).trans (Steps.single hs2)
  exact ⟨⟨σ2, i2, c.steps + 1 + 1⟩, hsteps2,
    ⟨hG2, hpc2, hp2, ⟨vmi2, hmi2⟩, hi2, ⟨hload2, hmemE2⟩⟩⟩

/-- `0x8001e97c`–`0x8001e984` (2 instructions), from `SegSt` to `SegSt`; side conditions are the `h*_<step>` hypotheses. -/
theorem seg_8001e97c_8001e984
    (v14 : BitVec 64)
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    (hlo_1 : 0x80000000 ≤ (v14 + sign_extend (m := 64) (0x000#12)).toNat)
    (hhi_1 : (v14 + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ 0x100000000)
    (hht_1 : (v14 + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ tohostAddr ∨ tohostAddr + 8 ≤ (v14 + sign_extend (m := 64) (0x000#12)).toNat)
    : Triple (SegSt (0x8001e97c#64) [⟨Register.x14, v14⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) (SegSt (0x8002f200#64) [⟨Register.x1, (0x8001e984#64 : BitVec 64)⟩, ⟨Register.x10, (sign_extend (m := 64) (bytesT8 (m0) (v14 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8)))⟩, ⟨Register.x14, v14⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq⟩⟩ := hPre
  -- === step 1: 0x8001e97c `site_8001e97c` (alu) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_8001e97c c.σ c.tick (c.steps) (0x8001e97c#64)
      vmi v14 hgood hpc hmi hp0.1 hloaded rfl hlo_1 hhi_1 hht_1 htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x8001e980#64 : BitVec 64) := by
    have := obs_alu_pc hobs1
    rwa [show BitVec.addInt (0x8001e97c#64) 4 = (0x8001e980#64 : BitVec 64) from by decide] at this
  have hrd1 : σ1.regs.get? Register.x10 = some (sign_extend (m := 64) (bytesT8 (m0) (v14 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))) := by
    have := obs_alu_rd hobs1 (by decide) (by decide) (by decide) (by decide) (by decide)
    rwa [hmemeq] at this
  have hp1 : PinsHold σ1 [⟨Register.x10, (sign_extend (m := 64) (bytesT8 (m0) (v14 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8)))⟩, ⟨Register.x14, v14⟩] :=
    ⟨hrd1, pins_alu hobs1 (by rfl) hp0⟩
  obtain ⟨vmi1, hmi1⟩ := obs_alu_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Lua.Vm.Arms.TextLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  -- === step 2: 0x8001e980 `site_8001e980` (jal) ===
  obtain ⟨σ2, i2, hs2, hi2, hG2, hmem2, hobs2⟩ :=
    site_8001e980 σ1 i1 (c.steps + 1) (0x8001e980#64)
      vmi1 hG1 hpc1 hmi1 hload1 rfl hi1
  have hpc2 : σ2.regs.get? Register.PC = some (0x8002f200#64 : BitVec 64) := by
    rw [obs_jal_pc hobs2,
      show (0x8001e980#64 : BitVec 64) + sign_extend (m := 64) (0x010880#21) = (0x8002f200#64 : BitVec 64) from by apply BitVec.eq_of_toNat_eq; decide]
  have hrd2 : σ2.regs.get? Register.x1 = some (0x8001e984#64 : BitVec 64) := by
    have := obs_jal_rd hobs2 (by decide) (by decide) (by decide) (by decide) (by decide)
    rwa [show BitVec.addInt (0x8001e980#64) 4 = (0x8001e984#64 : BitVec 64) from by decide] at this
  have hp2 : PinsHold σ2 [⟨Register.x1, (0x8001e984#64 : BitVec 64)⟩, ⟨Register.x10, (sign_extend (m := 64) (bytesT8 (m0) (v14 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8)))⟩, ⟨Register.x14, v14⟩] :=
    ⟨hrd2, pins_jal hobs2 (by rfl) hp1⟩
  obtain ⟨vmi2, hmi2⟩ := obs_jal_minstret hobs2
  have hmemE2 : σ2.mem = m0 := by
    rw [hmem2]; exact hmemE1
  have hload2 : Lua.Vm.Arms.TextLoaded σ2.mem := by
    rw [hmem2]; exact hload1
  have hsteps2 : Steps c ⟨σ2, i2, c.steps + 1 + 1⟩ :=
    (Steps.single hs1).trans (Steps.single hs2)
  exact ⟨⟨σ2, i2, c.steps + 1 + 1⟩, hsteps2,
    ⟨hG2, hpc2, hp2, ⟨vmi2, hmi2⟩, hi2, ⟨hload2, hmemE2⟩⟩⟩

/-- `0x8001e984`–`0x8001e988` (1 instruction), from `SegSt` to `SegSt`; side conditions are the `h*_<step>` hypotheses. -/
theorem seg_8001e984_8001e988
    (v10 : BitVec 64)
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    : Triple (SegSt (0x8001e984#64) [⟨Register.x10, v10⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) (SegSt (0x8001e988#64) [⟨Register.x11, (v10 + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x10, v10⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq⟩⟩ := hPre
  -- === step 1: 0x8001e984 `site_8001e984` (alu) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_8001e984 c.σ c.tick (c.steps) (0x8001e984#64)
      vmi v10 hgood hpc hmi hp0.1 hloaded rfl htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x8001e988#64 : BitVec 64) := by
    have := obs_alu_pc hobs1
    rwa [show BitVec.addInt (0x8001e984#64) 4 = (0x8001e988#64 : BitVec 64) from by decide] at this
  have hrd1 : σ1.regs.get? Register.x11 = some (v10 + sign_extend (m := 64) (0x000#12)) :=
    obs_alu_rd hobs1 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hp1 : PinsHold σ1 [⟨Register.x11, (v10 + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x10, v10⟩] :=
    ⟨hrd1, pins_alu hobs1 (by rfl) hp0⟩
  obtain ⟨vmi1, hmi1⟩ := obs_alu_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Lua.Vm.Arms.TextLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  have hsteps1 : Steps c ⟨σ1, i1, c.steps + 1⟩ :=
    Steps.single hs1
  exact ⟨⟨σ1, i1, c.steps + 1⟩, hsteps1,
    ⟨hG1, hpc1, hp1, ⟨vmi1, hmi1⟩, hi1, ⟨hload1, hmemE1⟩⟩⟩

/-- `0x8001e988`–`0x8001e98c` (1 instruction), from `SegSt` to `SegSt`; side conditions are the `h*_<step>` hypotheses. -/
theorem seg_8001e988_8001e98c
    (v26 : BitVec 64)
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    (hlo_1 : 0x80000000 ≤ (v26 + sign_extend (m := 64) (0x000#12)).toNat)
    (hhi_1 : (v26 + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ 0x100000000)
    (hht_1 : (v26 + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ tohostAddr ∨ tohostAddr + 8 ≤ (v26 + sign_extend (m := 64) (0x000#12)).toNat)
    : Triple (SegSt (0x8001e988#64) [⟨Register.x26, v26⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) (SegSt (0x8001e98c#64) [⟨Register.x10, (sign_extend (m := 64) (bytesT8 (m0) (v26 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8)))⟩, ⟨Register.x26, v26⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq⟩⟩ := hPre
  -- === step 1: 0x8001e988 `site_8001e988` (alu) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_8001e988 c.σ c.tick (c.steps) (0x8001e988#64)
      vmi v26 hgood hpc hmi hp0.1 hloaded rfl hlo_1 hhi_1 hht_1 htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x8001e98c#64 : BitVec 64) := by
    have := obs_alu_pc hobs1
    rwa [show BitVec.addInt (0x8001e988#64) 4 = (0x8001e98c#64 : BitVec 64) from by decide] at this
  have hrd1 : σ1.regs.get? Register.x10 = some (sign_extend (m := 64) (bytesT8 (m0) (v26 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))) := by
    have := obs_alu_rd hobs1 (by decide) (by decide) (by decide) (by decide) (by decide)
    rwa [hmemeq] at this
  have hp1 : PinsHold σ1 [⟨Register.x10, (sign_extend (m := 64) (bytesT8 (m0) (v26 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8)))⟩, ⟨Register.x26, v26⟩] :=
    ⟨hrd1, pins_alu hobs1 (by rfl) hp0⟩
  obtain ⟨vmi1, hmi1⟩ := obs_alu_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Lua.Vm.Arms.TextLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  have hsteps1 : Steps c ⟨σ1, i1, c.steps + 1⟩ :=
    Steps.single hs1
  exact ⟨⟨σ1, i1, c.steps + 1⟩, hsteps1,
    ⟨hG1, hpc1, hp1, ⟨vmi1, hmi1⟩, hi1, ⟨hload1, hmemE1⟩⟩⟩

/-- `0x8001e98c`–`0x8001e990` (1 instruction), from `SegSt` to `SegSt`; side conditions are the `h*_<step>` hypotheses. -/
theorem seg_8001e98c_8001e990
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    : Triple (SegSt (0x8001e98c#64) []
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) (SegSt (0x8002e504#64) [⟨Register.x1, (0x8001e990#64 : BitVec 64)⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq⟩⟩ := hPre
  -- === step 1: 0x8001e98c `site_8001e98c` (jal) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_8001e98c c.σ c.tick (c.steps) (0x8001e98c#64)
      vmi hgood hpc hmi hloaded rfl htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x8002e504#64 : BitVec 64) := by
    rw [obs_jal_pc hobs1,
      show (0x8001e98c#64 : BitVec 64) + sign_extend (m := 64) (0x00fb78#21) = (0x8002e504#64 : BitVec 64) from by apply BitVec.eq_of_toNat_eq; decide]
  have hrd1 : σ1.regs.get? Register.x1 = some (0x8001e990#64 : BitVec 64) := by
    have := obs_jal_rd hobs1 (by decide) (by decide) (by decide) (by decide) (by decide)
    rwa [show BitVec.addInt (0x8001e98c#64) 4 = (0x8001e990#64 : BitVec 64) from by decide] at this
  have hp1 : PinsHold σ1 [⟨Register.x1, (0x8001e990#64 : BitVec 64)⟩] :=
    ⟨hrd1, pins_jal hobs1 (by rfl) hp0⟩
  obtain ⟨vmi1, hmi1⟩ := obs_jal_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Lua.Vm.Arms.TextLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  have hsteps1 : Steps c ⟨σ1, i1, c.steps + 1⟩ :=
    Steps.single hs1
  exact ⟨⟨σ1, i1, c.steps + 1⟩, hsteps1,
    ⟨hG1, hpc1, hp1, ⟨vmi1, hmi1⟩, hi1, ⟨hload1, hmemE1⟩⟩⟩

/-- `0x8001e990`–`0x8001e9a4` (5 instructions), from `SegSt` to `SegSt`; side conditions are the `h*_<step>` hypotheses. -/
theorem seg_8001e990_8001e9a4
    (v27 v22 v10 : BitVec 64)
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    (hlo_3 : 0x80000000 ≤ (v22 + sign_extend (m := 64) (0x008#12)).toNat)
    (hhi_3 : (v22 + sign_extend (m := 64) (0x008#12)).toNat + 1 ≤ 0x100000000)
    (hwin_3 : tohostAddr + 16 ≤ (v22 + sign_extend (m := 64) (0x008#12)).toNat)
    (hlo_4 : 0x80000000 ≤ (v22 + sign_extend (m := 64) (0x000#12)).toNat)
    (hhi_4 : (v22 + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ 0x100000000)
    (hwin_4 : tohostAddr + 16 ≤ (v22 + sign_extend (m := 64) (0x000#12)).toNat)
    (hal_4 : (v22 + sign_extend (m := 64) (0x000#12)).toNat % 8 = 0)
    : Triple (SegSt (0x8001e990#64) [⟨Register.x27, v27⟩, ⟨Register.x22, v22⟩, ⟨Register.x10, v10⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) (SegSt (0x8001bfe4#64) [⟨Register.x27, (v27 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x15, ((0#64) + sign_extend (m := 64) (0x013#12))⟩, ⟨Register.x22, v22⟩, ⟨Register.x10, v10⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = writeMap8 (((m0).insert ((v22 + sign_extend (m := 64) (0x008#12)).toNat) ((stData 1 ((0#64) + sign_extend (m := 64) (0x013#12)))))) ((v22 + sign_extend (m := 64) (0x000#12)).toNat) (sdData_val v10))) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq⟩⟩ := hPre
  -- === step 1: 0x8001e990 `site_8001e990` (alu) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_8001e990 c.σ c.tick (c.steps) (0x8001e990#64)
      vmi hgood hpc hmi hloaded rfl htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x8001e994#64 : BitVec 64) := by
    have := obs_alu_pc hobs1
    rwa [show BitVec.addInt (0x8001e990#64) 4 = (0x8001e994#64 : BitVec 64) from by decide] at this
  have hrd1 : σ1.regs.get? Register.x15 = some ((0#64) + sign_extend (m := 64) (0x013#12)) :=
    obs_alu_rd hobs1 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hp1 : PinsHold σ1 [⟨Register.x15, ((0#64) + sign_extend (m := 64) (0x013#12))⟩, ⟨Register.x27, v27⟩, ⟨Register.x22, v22⟩, ⟨Register.x10, v10⟩] :=
    ⟨hrd1, pins_alu hobs1 (by rfl) hp0⟩
  obtain ⟨vmi1, hmi1⟩ := obs_alu_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Lua.Vm.Arms.TextLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  -- === step 2: 0x8001e994 `site_8001e994` (alu) ===
  obtain ⟨σ2, i2, hs2, hi2, hG2, hmem2, hobs2⟩ :=
    site_8001e994 σ1 i1 (c.steps + 1) (0x8001e994#64)
      vmi1 v27 hG1 hpc1 hmi1 hp1.2.1 hload1 rfl hi1
  have hpc2 : σ2.regs.get? Register.PC = some (0x8001e998#64 : BitVec 64) := by
    have := obs_alu_pc hobs2
    rwa [show BitVec.addInt (0x8001e994#64) 4 = (0x8001e998#64 : BitVec 64) from by decide] at this
  have hrd2 : σ2.regs.get? Register.x27 = some (v27 + sign_extend (m := 64) (0x008#12)) :=
    obs_alu_rd hobs2 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hq2 : PinsHold σ1 [⟨Register.x15, ((0#64) + sign_extend (m := 64) (0x013#12))⟩, ⟨Register.x22, v22⟩, ⟨Register.x10, v10⟩] :=
    ⟨hp1.1, hp1.2.2.1, hp1.2.2.2.1, trivial⟩
  have hp2 : PinsHold σ2 [⟨Register.x27, (v27 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x15, ((0#64) + sign_extend (m := 64) (0x013#12))⟩, ⟨Register.x22, v22⟩, ⟨Register.x10, v10⟩] :=
    ⟨hrd2, pins_alu hobs2 (by rfl) hq2⟩
  obtain ⟨vmi2, hmi2⟩ := obs_alu_minstret hobs2
  have hmemE2 : σ2.mem = m0 := by
    rw [hmem2]; exact hmemE1
  have hload2 : Lua.Vm.Arms.TextLoaded σ2.mem := by
    rw [hmem2]; exact hload1
  -- === step 3: 0x8001e998 `site_8001e998` (sb) ===
  obtain ⟨σ3, i3, hs3, hi3, hG3, hmem3, hobs3⟩ :=
    site_8001e998 σ2 i2 (c.steps + 1 + 1) (0x8001e998#64)
      vmi2 v22 ((0#64) + sign_extend (m := 64) (0x013#12)) hG2 hpc2 hmi2 hp2.2.2.1 hp2.2.1 hload2 rfl hlo_3 hhi_3 hwin_3 hi2
  have hpc3 : σ3.regs.get? Register.PC = some (0x8001e99c#64 : BitVec 64) := by
    have := obs_store_pc hobs3
    rwa [show BitVec.addInt (0x8001e998#64) 4 = (0x8001e99c#64 : BitVec 64) from by decide] at this
  have hp3 : PinsHold σ3 [⟨Register.x27, (v27 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x15, ((0#64) + sign_extend (m := 64) (0x013#12))⟩, ⟨Register.x22, v22⟩, ⟨Register.x10, v10⟩] :=
    pins_store hobs3 (by rfl) hp2
  obtain ⟨vmi3, hmi3⟩ := obs_store_minstret hobs3
  have hmemE3 : σ3.mem = ((m0).insert ((v22 + sign_extend (m := 64) (0x008#12)).toNat) ((stData 1 ((0#64) + sign_extend (m := 64) (0x013#12))))) := by
    rw [hmem3, mem_afterNextPC, hmemE2]
  have hload3 : Lua.Vm.Arms.TextLoaded σ3.mem := by
    rw [hmemE3]
    exact Lua.Vm.Arms.TextLoaded.insert (hmemE2 ▸ hload2) _ hwin_3
  -- === step 4: 0x8001e99c `site_8001e99c` (sd) ===
  obtain ⟨σ4, i4, hs4, hi4, hG4, hmem4, hobs4⟩ :=
    site_8001e99c σ3 i3 (c.steps + 1 + 1 + 1) (0x8001e99c#64)
      vmi3 v22 v10 hG3 hpc3 hmi3 hp3.2.2.1 hp3.2.2.2.1 hload3 rfl hlo_4 hhi_4 hwin_4 hal_4 hi3
  have hpc4 : σ4.regs.get? Register.PC = some (0x8001e9a0#64 : BitVec 64) := by
    have := obs_store_pc hobs4
    rwa [show BitVec.addInt (0x8001e99c#64) 4 = (0x8001e9a0#64 : BitVec 64) from by decide] at this
  have hp4 : PinsHold σ4 [⟨Register.x27, (v27 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x15, ((0#64) + sign_extend (m := 64) (0x013#12))⟩, ⟨Register.x22, v22⟩, ⟨Register.x10, v10⟩] :=
    pins_store hobs4 (by rfl) hp3
  obtain ⟨vmi4, hmi4⟩ := obs_store_minstret hobs4
  have hmemE4 : σ4.mem = writeMap8 (((m0).insert ((v22 + sign_extend (m := 64) (0x008#12)).toNat) ((stData 1 ((0#64) + sign_extend (m := 64) (0x013#12)))))) ((v22 + sign_extend (m := 64) (0x000#12)).toNat) (sdData_val v10) := by
    rw [hmem4, mem_afterNextPC, hmemE3]
  have hload4 : Lua.Vm.Arms.TextLoaded σ4.mem := by
    rw [hmemE4]
    exact Lua.Vm.Arms.TextLoaded.writeMap8 (hmemE3 ▸ hload3) _ hwin_4
  -- === step 5: 0x8001e9a0 `site_8001e9a0` (j) ===
  obtain ⟨σ5, i5, hs5, hi5, hG5, hmem5, hobs5⟩ :=
    site_8001e9a0 σ4 i4 (c.steps + 1 + 1 + 1 + 1) (0x8001e9a0#64)
      vmi4 hG4 hpc4 hmi4 hload4 rfl (by decide) hi4
  have hpc5 : σ5.regs.get? Register.PC = some (0x8001bfe4#64 : BitVec 64) := by
    rw [obs_jr_pc hobs5,
      show (0x8001e9a0#64 : BitVec 64) + sign_extend (m := 64) (0x1fd644#21) = (0x8001bfe4#64 : BitVec 64) from by apply BitVec.eq_of_toNat_eq; decide]
  have hp5 : PinsHold σ5 [⟨Register.x27, (v27 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x15, ((0#64) + sign_extend (m := 64) (0x013#12))⟩, ⟨Register.x22, v22⟩, ⟨Register.x10, v10⟩] :=
    pins_jr hobs5 (by rfl) hp4
  obtain ⟨vmi5, hmi5⟩ := obs_jr_minstret hobs5
  have hmemE5 : σ5.mem = writeMap8 (((m0).insert ((v22 + sign_extend (m := 64) (0x008#12)).toNat) ((stData 1 ((0#64) + sign_extend (m := 64) (0x013#12)))))) ((v22 + sign_extend (m := 64) (0x000#12)).toNat) (sdData_val v10) := by
    rw [hmem5]; exact hmemE4
  have hload5 : Lua.Vm.Arms.TextLoaded σ5.mem := by
    rw [hmem5]; exact hload4
  have hsteps5 : Steps c ⟨σ5, i5, c.steps + 1 + 1 + 1 + 1 + 1⟩ :=
    ((((Steps.single hs1).trans (Steps.single hs2)).trans (Steps.single hs3)).trans (Steps.single hs4)).trans (Steps.single hs5)
  exact ⟨⟨σ5, i5, c.steps + 1 + 1 + 1 + 1 + 1⟩, hsteps5,
    ⟨hG5, hpc5, hp5, ⟨vmi5, hmi5⟩, hi5, ⟨hload5, hmemE5⟩⟩⟩

/-- `0x8001e9a4`–`0x8001e9cc` (10 instructions), from `SegSt` to `SegSt`; side conditions are the `h*_<step>` hypotheses. -/
theorem seg_8001e9a4_8001e9cc
    (v27 v23 v19 : BitVec 64)
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    (hlo_1 : 0x80000000 ≤ (v27 + sign_extend (m := 64) (0x004#12)).toNat)
    (hhi_1 : (v27 + sign_extend (m := 64) (0x004#12)).toNat + 4 ≤ 0x100000000)
    (hht_1 : (v27 + sign_extend (m := 64) (0x004#12)).toNat + 4 ≤ tohostAddr ∨ tohostAddr + 8 ≤ (v27 + sign_extend (m := 64) (0x004#12)).toNat)
    (hlo_3 : 0x80000000 ≤ (v23 + sign_extend (m := 64) (0x028#12)).toNat)
    (hhi_3 : (v23 + sign_extend (m := 64) (0x028#12)).toNat + 4 ≤ 0x100000000)
    (hht_3 : (v23 + sign_extend (m := 64) (0x028#12)).toNat + 4 ≤ tohostAddr ∨ tohostAddr + 8 ≤ (v23 + sign_extend (m := 64) (0x028#12)).toNat)
    : Triple (SegSt (0x8001e9a4#64) [⟨Register.x27, v27⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) (SegSt (0x8001bfe4#64) [⟨Register.x21, (sign_extend (m := 64) (Sail.BitVec.extractLsb ((sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4))) + sign_extend (m := 64) (0x000#12)) 31 0))⟩, ⟨Register.x27, (v19 + (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0)))⟩, ⟨Register.x17, (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0))⟩, ⟨Register.x15, ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))⟩, ⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq⟩⟩ := hPre
  -- === step 1: 0x8001e9a4 `site_8001e9a4` (alu) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_8001e9a4 c.σ c.tick (c.steps) (0x8001e9a4#64)
      vmi v27 hgood hpc hmi hp0.1 hloaded rfl hlo_1 hhi_1 hht_1 htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x8001e9a8#64 : BitVec 64) := by
    have := obs_alu_pc hobs1
    rwa [show BitVec.addInt (0x8001e9a4#64) 4 = (0x8001e9a8#64 : BitVec 64) from by decide] at this
  have hrd1 : σ1.regs.get? Register.x17 = some (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) := by
    have := obs_alu_rd hobs1 (by decide) (by decide) (by decide) (by decide) (by decide)
    rwa [hmemeq] at this
  have hp1 : PinsHold σ1 [⟨Register.x17, (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x27, v27⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩] :=
    ⟨hrd1, pins_alu hobs1 (by rfl) hp0⟩
  obtain ⟨vmi1, hmi1⟩ := obs_alu_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Lua.Vm.Arms.TextLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  -- === step 2: 0x8001e9a8 `site_8001e9a8` (alu) ===
  obtain ⟨σ2, i2, hs2, hi2, hG2, hmem2, hobs2⟩ :=
    site_8001e9a8 σ1 i1 (c.steps + 1) (0x8001e9a8#64)
      vmi1 hG1 hpc1 hmi1 hload1 rfl hi1
  have hpc2 : σ2.regs.get? Register.PC = some (0x8001e9ac#64 : BitVec 64) := by
    have := obs_alu_pc hobs2
    rwa [show BitVec.addInt (0x8001e9a8#64) 4 = (0x8001e9ac#64 : BitVec 64) from by decide] at this
  have hrd2 : σ2.regs.get? Register.x15 = some (sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) :=
    obs_alu_rd hobs2 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hp2 : PinsHold σ2 [⟨Register.x15, (sign_extend (m := 64) ((0xff000#20) +++ 0x000#12))⟩, ⟨Register.x17, (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x27, v27⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩] :=
    ⟨hrd2, pins_alu hobs2 (by rfl) hp1⟩
  obtain ⟨vmi2, hmi2⟩ := obs_alu_minstret hobs2
  have hmemE2 : σ2.mem = m0 := by
    rw [hmem2]; exact hmemE1
  have hload2 : Lua.Vm.Arms.TextLoaded σ2.mem := by
    rw [hmem2]; exact hload1
  -- === step 3: 0x8001e9ac `site_8001e9ac` (alu) ===
  obtain ⟨σ3, i3, hs3, hi3, hG3, hmem3, hobs3⟩ :=
    site_8001e9ac σ2 i2 (c.steps + 1 + 1) (0x8001e9ac#64)
      vmi2 v23 hG2 hpc2 hmi2 hp2.2.2.2.1 hload2 rfl hlo_3 hhi_3 hht_3 hi2
  have hpc3 : σ3.regs.get? Register.PC = some (0x8001e9b0#64 : BitVec 64) := by
    have := obs_alu_pc hobs3
    rwa [show BitVec.addInt (0x8001e9ac#64) 4 = (0x8001e9b0#64 : BitVec 64) from by decide] at this
  have hrd3 : σ3.regs.get? Register.x31 = some (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4))) := by
    have := obs_alu_rd hobs3 (by decide) (by decide) (by decide) (by decide) (by decide)
    rwa [hmemE2] at this
  have hp3 : PinsHold σ3 [⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x15, (sign_extend (m := 64) ((0xff000#20) +++ 0x000#12))⟩, ⟨Register.x17, (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x27, v27⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩] :=
    ⟨hrd3, pins_alu hobs3 (by rfl) hp2⟩
  obtain ⟨vmi3, hmi3⟩ := obs_alu_minstret hobs3
  have hmemE3 : σ3.mem = m0 := by
    rw [hmem3]; exact hmemE2
  have hload3 : Lua.Vm.Arms.TextLoaded σ3.mem := by
    rw [hmem3]; exact hload2
  -- === step 4: 0x8001e9b0 `site_8001e9b0` (alu) ===
  obtain ⟨σ4, i4, hs4, hi4, hG4, hmem4, hobs4⟩ :=
    site_8001e9b0 σ3 i3 (c.steps + 1 + 1 + 1) (0x8001e9b0#64)
      vmi3 (sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) hG3 hpc3 hmi3 hp3.2.1 hload3 rfl hi3
  have hpc4 : σ4.regs.get? Register.PC = some (0x8001e9b4#64 : BitVec 64) := by
    have := obs_alu_pc hobs4
    rwa [show BitVec.addInt (0x8001e9b0#64) 4 = (0x8001e9b4#64 : BitVec 64) from by decide] at this
  have hrd4 : σ4.regs.get? Register.x15 = some ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12)) :=
    obs_alu_rd hobs4 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hq4 : PinsHold σ3 [⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x17, (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x27, v27⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩] :=
    -- discipline: allow(R6-anon-projection-tower) pin-bundle projection emitted by gen_segment.py (the bundle is a PinsHold list)
    ⟨hp3.1, hp3.2.2.1, hp3.2.2.2.1, hp3.2.2.2.2.1, hp3.2.2.2.2.2.1, trivial⟩
  have hp4 : PinsHold σ4 [⟨Register.x15, ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))⟩, ⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x17, (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x27, v27⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩] :=
    ⟨hrd4, pins_alu hobs4 (by rfl) hq4⟩
  obtain ⟨vmi4, hmi4⟩ := obs_alu_minstret hobs4
  have hmemE4 : σ4.mem = m0 := by
    rw [hmem4]; exact hmemE3
  have hload4 : Lua.Vm.Arms.TextLoaded σ4.mem := by
    rw [hmem4]; exact hload3
  -- === step 5: 0x8001e9b4 `site_8001e9b4` (alu) ===
  obtain ⟨σ5, i5, hs5, hi5, hG5, hmem5, hobs5⟩ :=
    site_8001e9b4 σ4 i4 (c.steps + 1 + 1 + 1 + 1) (0x8001e9b4#64)
      vmi4 (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) hG4 hpc4 hmi4 hp4.2.2.1 hload4 rfl hi4
  have hpc5 : σ5.regs.get? Register.PC = some (0x8001e9b8#64 : BitVec 64) := by
    have := obs_alu_pc hobs5
    rwa [show BitVec.addInt (0x8001e9b4#64) 4 = (0x8001e9b8#64 : BitVec 64) from by decide] at this
  have hrd5 : σ5.regs.get? Register.x17 = some (sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) :=
    obs_alu_rd hobs5 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hq5 : PinsHold σ4 [⟨Register.x15, ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))⟩, ⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x27, v27⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩] :=
    -- discipline: allow(R6-anon-projection-tower) pin-bundle projection emitted by gen_segment.py (the bundle is a PinsHold list)
    ⟨hp4.1, hp4.2.1, hp4.2.2.2.1, hp4.2.2.2.2.1, hp4.2.2.2.2.2.1, trivial⟩
  have hp5 : PinsHold σ5 [⟨Register.x17, (sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5)))⟩, ⟨Register.x15, ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))⟩, ⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x27, v27⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩] :=
    ⟨hrd5, pins_alu hobs5 (by rfl) hq5⟩
  obtain ⟨vmi5, hmi5⟩ := obs_alu_minstret hobs5
  have hmemE5 : σ5.mem = m0 := by
    rw [hmem5]; exact hmemE4
  have hload5 : Lua.Vm.Arms.TextLoaded σ5.mem := by
    rw [hmem5]; exact hload4
  -- === step 6: 0x8001e9b8 `site_8001e9b8` (alu) ===
  obtain ⟨σ6, i6, hs6, hi6, hG6, hmem6, hobs6⟩ :=
    site_8001e9b8 σ5 i5 (c.steps + 1 + 1 + 1 + 1 + 1) (0x8001e9b8#64)
      vmi5 (sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12)) hG5 hpc5 hmi5 hp5.1 hp5.2.1 hload5 rfl hi5
  have hpc6 : σ6.regs.get? Register.PC = some (0x8001e9bc#64 : BitVec 64) := by
    have := obs_alu_pc hobs6
    rwa [show BitVec.addInt (0x8001e9b8#64) 4 = (0x8001e9bc#64 : BitVec 64) from by decide] at this
  have hrd6 : σ6.regs.get? Register.x17 = some ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) :=
    obs_alu_rd hobs6 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hq6 : PinsHold σ5 [⟨Register.x15, ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))⟩, ⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x27, v27⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩] :=
    -- discipline: allow(R6-anon-projection-tower) pin-bundle projection emitted by gen_segment.py (the bundle is a PinsHold list)
    ⟨hp5.2.1, hp5.2.2.1, hp5.2.2.2.1, hp5.2.2.2.2.1, hp5.2.2.2.2.2.1, trivial⟩
  have hp6 : PinsHold σ6 [⟨Register.x17, ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12)))⟩, ⟨Register.x15, ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))⟩, ⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x27, v27⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩] :=
    ⟨hrd6, pins_alu hobs6 (by rfl) hq6⟩
  obtain ⟨vmi6, hmi6⟩ := obs_alu_minstret hobs6
  have hmemE6 : σ6.mem = m0 := by
    rw [hmem6]; exact hmemE5
  have hload6 : Lua.Vm.Arms.TextLoaded σ6.mem := by
    rw [hmem6]; exact hload5
  -- === step 7: 0x8001e9bc `site_8001e9bc` (alu) ===
  obtain ⟨σ7, i7, hs7, hi7, hG7, hmem7, hobs7⟩ :=
    site_8001e9bc σ6 i6 (c.steps + 1 + 1 + 1 + 1 + 1 + 1) (0x8001e9bc#64)
      vmi6 ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) hG6 hpc6 hmi6 hp6.1 hload6 rfl hi6
  have hpc7 : σ7.regs.get? Register.PC = some (0x8001e9c0#64 : BitVec 64) := by
    have := obs_alu_pc hobs7
    rwa [show BitVec.addInt (0x8001e9bc#64) 4 = (0x8001e9c0#64 : BitVec 64) from by decide] at this
  have hrd7 : σ7.regs.get? Register.x17 = some (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0)) :=
    obs_alu_rd hobs7 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hq7 : PinsHold σ6 [⟨Register.x15, ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))⟩, ⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x27, v27⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩] :=
    -- discipline: allow(R6-anon-projection-tower) pin-bundle projection emitted by gen_segment.py (the bundle is a PinsHold list)
    ⟨hp6.2.1, hp6.2.2.1, hp6.2.2.2.1, hp6.2.2.2.2.1, hp6.2.2.2.2.2.1, trivial⟩
  have hp7 : PinsHold σ7 [⟨Register.x17, (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0))⟩, ⟨Register.x15, ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))⟩, ⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x27, v27⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩] :=
    ⟨hrd7, pins_alu hobs7 (by rfl) hq7⟩
  obtain ⟨vmi7, hmi7⟩ := obs_alu_minstret hobs7
  have hmemE7 : σ7.mem = m0 := by
    rw [hmem7]; exact hmemE6
  have hload7 : Lua.Vm.Arms.TextLoaded σ7.mem := by
    rw [hmem7]; exact hload6
  -- === step 8: 0x8001e9c0 `site_8001e9c0` (alu) ===
  obtain ⟨σ8, i8, hs8, hi8, hG8, hmem8, hobs8⟩ :=
    site_8001e9c0 σ7 i7 (c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1) (0x8001e9c0#64)
      -- discipline: allow(R6-anon-projection-tower) pin-bundle projection emitted by gen_segment.py (the bundle is a PinsHold list)
      vmi7 v19 (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0)) hG7 hpc7 hmi7 hp7.2.2.2.2.2.1 hp7.1 hload7 rfl hi7
  have hpc8 : σ8.regs.get? Register.PC = some (0x8001e9c4#64 : BitVec 64) := by
    have := obs_alu_pc hobs8
    rwa [show BitVec.addInt (0x8001e9c0#64) 4 = (0x8001e9c4#64 : BitVec 64) from by decide] at this
  have hrd8 : σ8.regs.get? Register.x27 = some (v19 + (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0))) :=
    obs_alu_rd hobs8 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hq8 : PinsHold σ7 [⟨Register.x17, (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0))⟩, ⟨Register.x15, ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))⟩, ⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩] :=
    -- discipline: allow(R6-anon-projection-tower) pin-bundle projection emitted by gen_segment.py (the bundle is a PinsHold list)
    ⟨hp7.1, hp7.2.1, hp7.2.2.1, hp7.2.2.2.2.1, hp7.2.2.2.2.2.1, trivial⟩
  have hp8 : PinsHold σ8 [⟨Register.x27, (v19 + (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0)))⟩, ⟨Register.x17, (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0))⟩, ⟨Register.x15, ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))⟩, ⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩] :=
    ⟨hrd8, pins_alu hobs8 (by rfl) hq8⟩
  obtain ⟨vmi8, hmi8⟩ := obs_alu_minstret hobs8
  have hmemE8 : σ8.mem = m0 := by
    rw [hmem8]; exact hmemE7
  have hload8 : Lua.Vm.Arms.TextLoaded σ8.mem := by
    rw [hmem8]; exact hload7
  -- === step 9: 0x8001e9c4 `site_8001e9c4` (alu) ===
  obtain ⟨σ9, i9, hs9, hi9, hG9, hmem9, hobs9⟩ :=
    site_8001e9c4 σ8 i8 (c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1) (0x8001e9c4#64)
      vmi8 (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4))) hG8 hpc8 hmi8 hp8.2.2.2.1 hload8 rfl hi8
  have hpc9 : σ9.regs.get? Register.PC = some (0x8001e9c8#64 : BitVec 64) := by
    have := obs_alu_pc hobs9
    rwa [show BitVec.addInt (0x8001e9c4#64) 4 = (0x8001e9c8#64 : BitVec 64) from by decide] at this
  have hrd9 : σ9.regs.get? Register.x21 = some (sign_extend (m := 64) (Sail.BitVec.extractLsb ((sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4))) + sign_extend (m := 64) (0x000#12)) 31 0)) :=
    obs_alu_rd hobs9 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hp9 : PinsHold σ9 [⟨Register.x21, (sign_extend (m := 64) (Sail.BitVec.extractLsb ((sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4))) + sign_extend (m := 64) (0x000#12)) 31 0))⟩, ⟨Register.x27, (v19 + (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0)))⟩, ⟨Register.x17, (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0))⟩, ⟨Register.x15, ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))⟩, ⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩] :=
    ⟨hrd9, pins_alu hobs9 (by rfl) hp8⟩
  obtain ⟨vmi9, hmi9⟩ := obs_alu_minstret hobs9
  have hmemE9 : σ9.mem = m0 := by
    rw [hmem9]; exact hmemE8
  have hload9 : Lua.Vm.Arms.TextLoaded σ9.mem := by
    rw [hmem9]; exact hload8
  -- === step 10: 0x8001e9c8 `site_8001e9c8` (j) ===
  obtain ⟨σ10, i10, hs10, hi10, hG10, hmem10, hobs10⟩ :=
    site_8001e9c8 σ9 i9 (c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1) (0x8001e9c8#64)
      vmi9 hG9 hpc9 hmi9 hload9 rfl (by decide) hi9
  have hpc10 : σ10.regs.get? Register.PC = some (0x8001bfe4#64 : BitVec 64) := by
    rw [obs_jr_pc hobs10,
      show (0x8001e9c8#64 : BitVec 64) + sign_extend (m := 64) (0x1fd61c#21) = (0x8001bfe4#64 : BitVec 64) from by apply BitVec.eq_of_toNat_eq; decide]
  have hp10 : PinsHold σ10 [⟨Register.x21, (sign_extend (m := 64) (Sail.BitVec.extractLsb ((sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4))) + sign_extend (m := 64) (0x000#12)) 31 0))⟩, ⟨Register.x27, (v19 + (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0)))⟩, ⟨Register.x17, (shift_bits_left ((sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb (sign_extend (m := 64) (bytesT4 (m0) (v27 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))) 31 0) (0x07#5))) + ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))) (Sail.BitVec.extractLsb (0x02#6) 5 0))⟩, ⟨Register.x15, ((sign_extend (m := 64) ((0xff000#20) +++ 0x000#12)) + sign_extend (m := 64) (0x002#12))⟩, ⟨Register.x31, (sign_extend (m := 64) (bytesT4 (m0) (v23 + sign_extend (m := 64) (0x028#12)).toNat : BitVec (8 * 4)))⟩, ⟨Register.x23, v23⟩, ⟨Register.x19, v19⟩] :=
    pins_jr hobs10 (by rfl) hp9
  obtain ⟨vmi10, hmi10⟩ := obs_jr_minstret hobs10
  have hmemE10 : σ10.mem = m0 := by
    rw [hmem10]; exact hmemE9
  have hload10 : Lua.Vm.Arms.TextLoaded σ10.mem := by
    rw [hmem10]; exact hload9
  have hsteps10 : Steps c ⟨σ10, i10, c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1⟩ :=
    (((((((((Steps.single hs1).trans (Steps.single hs2)).trans (Steps.single hs3)).trans (Steps.single hs4)).trans (Steps.single hs5)).trans (Steps.single hs6)).trans (Steps.single hs7)).trans (Steps.single hs8)).trans (Steps.single hs9)).trans (Steps.single hs10)
  exact ⟨⟨σ10, i10, c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1⟩, hsteps10,
    ⟨hG10, hpc10, hp10, ⟨vmi10, hmi10⟩, hi10, ⟨hload10, hmemE10⟩⟩⟩

end Lua.Vm.Arms
