import Lua.Vm.Arms.Sites.S55
import Lua.Vm.Arms.Sites.S56
import Lua.Vm.Arms.Text
import Vsa.Sim.SegState

/-! GENERATED by scripts/gen_lua_arms.py -- do not edit.

Segment theorems of the F1 arms of `luaV_execute`, `SegSt` to `SegSt`
(scripts/syi/gen_segment.py, `"boundary": "segst"`). -/

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail ConcurrencyInterfaceV1 Vsa
open Register
open Sail.ConcurrencyInterfaceV1.PreSail
open Vsa.Machine (MState Config Step Steps)
open Vsa.Logic
open Vsa.Sim

namespace Lua.Vm.Arms

/-- `0x8001f1ac`–`0x8001f1b4` (2 instructions), from `SegSt` to `SegSt`; side conditions are the `h*_<step>` hypotheses. -/
theorem seg_8001f1ac_8001f1b4_t
    (v14 : BitVec 64)
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    (hg_2 : (v14 == ((0#64) + sign_extend (m := 64) (0x013#12))) = true)
    : Triple (SegSt (0x8001f1ac#64) [⟨Register.x14, v14⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) (SegSt (0x8001f1b8#64) [⟨Register.x13, ((0#64) + sign_extend (m := 64) (0x013#12))⟩, ⟨Register.x14, v14⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq⟩⟩ := hPre
  -- === step 1: 0x8001f1ac `site_8001f1ac` (alu) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_8001f1ac c.σ c.tick (c.steps) (0x8001f1ac#64)
      vmi hgood hpc hmi hloaded rfl htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x8001f1b0#64 : BitVec 64) := by
    have := obs_alu_pc hobs1
    rwa [show BitVec.addInt (0x8001f1ac#64) 4 = (0x8001f1b0#64 : BitVec 64) from by decide] at this
  have hrd1 : σ1.regs.get? Register.x13 = some ((0#64) + sign_extend (m := 64) (0x013#12)) :=
    obs_alu_rd hobs1 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hp1 : PinsHold σ1 [⟨Register.x13, ((0#64) + sign_extend (m := 64) (0x013#12))⟩, ⟨Register.x14, v14⟩] :=
    ⟨hrd1, pins_alu hobs1 (by rfl) hp0⟩
  obtain ⟨vmi1, hmi1⟩ := obs_alu_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Lua.Vm.Arms.TextLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  -- === step 2: 0x8001f1b0 `site_8001f1b0_taken` (btaken) ===
  obtain ⟨σ2, i2, hs2, hi2, hG2, hmem2, hobs2⟩ :=
    site_8001f1b0_taken σ1 i1 (c.steps + 1) (0x8001f1b0#64)
      vmi1 v14 ((0#64) + sign_extend (m := 64) (0x013#12)) hG1 hpc1 hmi1 hp1.2.1 hp1.1 hload1 rfl hg_2 hi1
  have hpc2 : σ2.regs.get? Register.PC = some (0x8001f1b8#64 : BitVec 64) := by
    rw [obs_btaken_pc hobs2,
      show (0x8001f1b0#64 : BitVec 64) + sign_extend (m := 64) (0x0008#13) = (0x8001f1b8#64 : BitVec 64) from by apply BitVec.eq_of_toNat_eq; decide]
  have hp2 : PinsHold σ2 [⟨Register.x13, ((0#64) + sign_extend (m := 64) (0x013#12))⟩, ⟨Register.x14, v14⟩] :=
    pins_btaken hobs2 (by rfl) hp1
  obtain ⟨vmi2, hmi2⟩ := obs_btaken_minstret hobs2
  have hmemE2 : σ2.mem = m0 := by
    rw [hmem2]; exact hmemE1
  have hload2 : Lua.Vm.Arms.TextLoaded σ2.mem := by
    rw [hmem2]; exact hload1
  have hsteps2 : Steps c ⟨σ2, i2, c.steps + 1 + 1⟩ :=
    (Steps.single hs1).trans (Steps.single hs2)
  exact ⟨⟨σ2, i2, c.steps + 1 + 1⟩, hsteps2,
    ⟨hG2, hpc2, hp2, ⟨vmi2, hmi2⟩, hi2, ⟨hload2, hmemE2⟩⟩⟩

/-- `0x8001f1b4`–`0x8001f1b8` (1 instruction), from `SegSt` to `SegSt`; side conditions are the `h*_<step>` hypotheses. -/
theorem seg_8001f1b4_8001f1b8
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    : Triple (SegSt (0x8001f1b4#64) []
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) (SegSt (0x8001c1e4#64) []
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq⟩⟩ := hPre
  -- === step 1: 0x8001f1b4 `site_8001f1b4` (j) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_8001f1b4 c.σ c.tick (c.steps) (0x8001f1b4#64)
      vmi hgood hpc hmi hloaded rfl (by decide) htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x8001c1e4#64 : BitVec 64) := by
    rw [obs_jr_pc hobs1,
      show (0x8001f1b4#64 : BitVec 64) + sign_extend (m := 64) (0x1fd030#21) = (0x8001c1e4#64 : BitVec 64) from by apply BitVec.eq_of_toNat_eq; decide]
  have hp1 : PinsHold σ1 [] :=
    pins_jr hobs1 (by rfl) hp0
  obtain ⟨vmi1, hmi1⟩ := obs_jr_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Lua.Vm.Arms.TextLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  have hsteps1 : Steps c ⟨σ1, i1, c.steps + 1⟩ :=
    Steps.single hs1
  exact ⟨⟨σ1, i1, c.steps + 1⟩, hsteps1,
    ⟨hG1, hpc1, hp1, ⟨vmi1, hmi1⟩, hi1, ⟨hload1, hmemE1⟩⟩⟩

/-- `0x8001f1b8`–`0x8001f1c4` (3 instructions), from `SegSt` to `SegSt`; side conditions are the `h*_<step>` hypotheses. -/
theorem seg_8001f1b8_8001f1c4
    (v15 : BitVec 64)
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    (hlo_1 : 0x80000000 ≤ (v15 + sign_extend (m := 64) (0x000#12)).toNat)
    (hhi_1 : (v15 + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ 0x100000000)
    (hht_1 : (v15 + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ tohostAddr ∨ tohostAddr + 8 ≤ (v15 + sign_extend (m := 64) (0x000#12)).toNat)
    : Triple (SegSt (0x8001f1b8#64) [⟨Register.x15, v15⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) (SegSt (0x8002bb14#64) [⟨Register.x1, (0x8001f1c4#64 : BitVec 64)⟩, ⟨Register.x10, ((sign_extend (m := 64) (bytesT8 (m0) (v15 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))) + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x26, (sign_extend (m := 64) (bytesT8 (m0) (v15 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8)))⟩, ⟨Register.x15, v15⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq⟩⟩ := hPre
  -- === step 1: 0x8001f1b8 `site_8001f1b8` (alu) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_8001f1b8 c.σ c.tick (c.steps) (0x8001f1b8#64)
      vmi v15 hgood hpc hmi hp0.1 hloaded rfl hlo_1 hhi_1 hht_1 htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x8001f1bc#64 : BitVec 64) := by
    have := obs_alu_pc hobs1
    rwa [show BitVec.addInt (0x8001f1b8#64) 4 = (0x8001f1bc#64 : BitVec 64) from by decide] at this
  have hrd1 : σ1.regs.get? Register.x26 = some (sign_extend (m := 64) (bytesT8 (m0) (v15 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))) := by
    have := obs_alu_rd hobs1 (by decide) (by decide) (by decide) (by decide) (by decide)
    rwa [hmemeq] at this
  have hp1 : PinsHold σ1 [⟨Register.x26, (sign_extend (m := 64) (bytesT8 (m0) (v15 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8)))⟩, ⟨Register.x15, v15⟩] :=
    ⟨hrd1, pins_alu hobs1 (by rfl) hp0⟩
  obtain ⟨vmi1, hmi1⟩ := obs_alu_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Lua.Vm.Arms.TextLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  -- === step 2: 0x8001f1bc `site_8001f1bc` (alu) ===
  obtain ⟨σ2, i2, hs2, hi2, hG2, hmem2, hobs2⟩ :=
    site_8001f1bc σ1 i1 (c.steps + 1) (0x8001f1bc#64)
      vmi1 (sign_extend (m := 64) (bytesT8 (m0) (v15 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))) hG1 hpc1 hmi1 hp1.1 hload1 rfl hi1
  have hpc2 : σ2.regs.get? Register.PC = some (0x8001f1c0#64 : BitVec 64) := by
    have := obs_alu_pc hobs2
    rwa [show BitVec.addInt (0x8001f1bc#64) 4 = (0x8001f1c0#64 : BitVec 64) from by decide] at this
  have hrd2 : σ2.regs.get? Register.x10 = some ((sign_extend (m := 64) (bytesT8 (m0) (v15 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))) + sign_extend (m := 64) (0x000#12)) :=
    obs_alu_rd hobs2 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hp2 : PinsHold σ2 [⟨Register.x10, ((sign_extend (m := 64) (bytesT8 (m0) (v15 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))) + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x26, (sign_extend (m := 64) (bytesT8 (m0) (v15 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8)))⟩, ⟨Register.x15, v15⟩] :=
    ⟨hrd2, pins_alu hobs2 (by rfl) hp1⟩
  obtain ⟨vmi2, hmi2⟩ := obs_alu_minstret hobs2
  have hmemE2 : σ2.mem = m0 := by
    rw [hmem2]; exact hmemE1
  have hload2 : Lua.Vm.Arms.TextLoaded σ2.mem := by
    rw [hmem2]; exact hload1
  -- === step 3: 0x8001f1c0 `site_8001f1c0` (jal) ===
  obtain ⟨σ3, i3, hs3, hi3, hG3, hmem3, hobs3⟩ :=
    site_8001f1c0 σ2 i2 (c.steps + 1 + 1) (0x8001f1c0#64)
      vmi2 hG2 hpc2 hmi2 hload2 rfl hi2
  have hpc3 : σ3.regs.get? Register.PC = some (0x8002bb14#64 : BitVec 64) := by
    rw [obs_jal_pc hobs3,
      show (0x8001f1c0#64 : BitVec 64) + sign_extend (m := 64) (0x00c954#21) = (0x8002bb14#64 : BitVec 64) from by apply BitVec.eq_of_toNat_eq; decide]
  have hrd3 : σ3.regs.get? Register.x1 = some (0x8001f1c4#64 : BitVec 64) := by
    have := obs_jal_rd hobs3 (by decide) (by decide) (by decide) (by decide) (by decide)
    rwa [show BitVec.addInt (0x8001f1c0#64) 4 = (0x8001f1c4#64 : BitVec 64) from by decide] at this
  have hp3 : PinsHold σ3 [⟨Register.x1, (0x8001f1c4#64 : BitVec 64)⟩, ⟨Register.x10, ((sign_extend (m := 64) (bytesT8 (m0) (v15 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))) + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x26, (sign_extend (m := 64) (bytesT8 (m0) (v15 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8)))⟩, ⟨Register.x15, v15⟩] :=
    ⟨hrd3, pins_jal hobs3 (by rfl) hp2⟩
  obtain ⟨vmi3, hmi3⟩ := obs_jal_minstret hobs3
  have hmemE3 : σ3.mem = m0 := by
    rw [hmem3]; exact hmemE2
  have hload3 : Lua.Vm.Arms.TextLoaded σ3.mem := by
    rw [hmem3]; exact hload2
  have hsteps3 : Steps c ⟨σ3, i3, c.steps + 1 + 1 + 1⟩ :=
    ((Steps.single hs1).trans (Steps.single hs2)).trans (Steps.single hs3)
  exact ⟨⟨σ3, i3, c.steps + 1 + 1 + 1⟩, hsteps3,
    ⟨hG3, hpc3, hp3, ⟨vmi3, hmi3⟩, hi3, ⟨hload3, hmemE3⟩⟩⟩

/-- `0x8001f1c4`–`0x8001f1d4` (4 instructions), from `SegSt` to `SegSt`; side conditions are the `h*_<step>` hypotheses. -/
theorem seg_8001f1c4_8001f1d4
    (v10 v26 : BitVec 64)
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    : Triple (SegSt (0x8001f1c4#64) [⟨Register.x10, v10⟩, ⟨Register.x26, v26⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) (SegSt (0x8002e350#64) [⟨Register.x1, (0x8001f1d4#64 : BitVec 64)⟩, ⟨Register.x10, (v26 + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x11, (v10 + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x22, (v10 + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x26, v26⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq⟩⟩ := hPre
  -- === step 1: 0x8001f1c4 `site_8001f1c4` (alu) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_8001f1c4 c.σ c.tick (c.steps) (0x8001f1c4#64)
      vmi v10 hgood hpc hmi hp0.1 hloaded rfl htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x8001f1c8#64 : BitVec 64) := by
    have := obs_alu_pc hobs1
    rwa [show BitVec.addInt (0x8001f1c4#64) 4 = (0x8001f1c8#64 : BitVec 64) from by decide] at this
  have hrd1 : σ1.regs.get? Register.x22 = some (v10 + sign_extend (m := 64) (0x000#12)) :=
    obs_alu_rd hobs1 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hp1 : PinsHold σ1 [⟨Register.x22, (v10 + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x10, v10⟩, ⟨Register.x26, v26⟩] :=
    ⟨hrd1, pins_alu hobs1 (by rfl) hp0⟩
  obtain ⟨vmi1, hmi1⟩ := obs_alu_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Lua.Vm.Arms.TextLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  -- === step 2: 0x8001f1c8 `site_8001f1c8` (alu) ===
  obtain ⟨σ2, i2, hs2, hi2, hG2, hmem2, hobs2⟩ :=
    site_8001f1c8 σ1 i1 (c.steps + 1) (0x8001f1c8#64)
      vmi1 v10 hG1 hpc1 hmi1 hp1.2.1 hload1 rfl hi1
  have hpc2 : σ2.regs.get? Register.PC = some (0x8001f1cc#64 : BitVec 64) := by
    have := obs_alu_pc hobs2
    rwa [show BitVec.addInt (0x8001f1c8#64) 4 = (0x8001f1cc#64 : BitVec 64) from by decide] at this
  have hrd2 : σ2.regs.get? Register.x11 = some (v10 + sign_extend (m := 64) (0x000#12)) :=
    obs_alu_rd hobs2 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hp2 : PinsHold σ2 [⟨Register.x11, (v10 + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x22, (v10 + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x10, v10⟩, ⟨Register.x26, v26⟩] :=
    ⟨hrd2, pins_alu hobs2 (by rfl) hp1⟩
  obtain ⟨vmi2, hmi2⟩ := obs_alu_minstret hobs2
  have hmemE2 : σ2.mem = m0 := by
    rw [hmem2]; exact hmemE1
  have hload2 : Lua.Vm.Arms.TextLoaded σ2.mem := by
    rw [hmem2]; exact hload1
  -- === step 3: 0x8001f1cc `site_8001f1cc` (alu) ===
  obtain ⟨σ3, i3, hs3, hi3, hG3, hmem3, hobs3⟩ :=
    site_8001f1cc σ2 i2 (c.steps + 1 + 1) (0x8001f1cc#64)
      vmi2 v26 hG2 hpc2 hmi2 hp2.2.2.2.1 hload2 rfl hi2
  have hpc3 : σ3.regs.get? Register.PC = some (0x8001f1d0#64 : BitVec 64) := by
    have := obs_alu_pc hobs3
    rwa [show BitVec.addInt (0x8001f1cc#64) 4 = (0x8001f1d0#64 : BitVec 64) from by decide] at this
  have hrd3 : σ3.regs.get? Register.x10 = some (v26 + sign_extend (m := 64) (0x000#12)) :=
    obs_alu_rd hobs3 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hq3 : PinsHold σ2 [⟨Register.x11, (v10 + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x22, (v10 + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x26, v26⟩] :=
    ⟨hp2.1, hp2.2.1, hp2.2.2.2.1, trivial⟩
  have hp3 : PinsHold σ3 [⟨Register.x10, (v26 + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x11, (v10 + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x22, (v10 + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x26, v26⟩] :=
    ⟨hrd3, pins_alu hobs3 (by rfl) hq3⟩
  obtain ⟨vmi3, hmi3⟩ := obs_alu_minstret hobs3
  have hmemE3 : σ3.mem = m0 := by
    rw [hmem3]; exact hmemE2
  have hload3 : Lua.Vm.Arms.TextLoaded σ3.mem := by
    rw [hmem3]; exact hload2
  -- === step 4: 0x8001f1d0 `site_8001f1d0` (jal) ===
  obtain ⟨σ4, i4, hs4, hi4, hG4, hmem4, hobs4⟩ :=
    site_8001f1d0 σ3 i3 (c.steps + 1 + 1 + 1) (0x8001f1d0#64)
      vmi3 hG3 hpc3 hmi3 hload3 rfl hi3
  have hpc4 : σ4.regs.get? Register.PC = some (0x8002e350#64 : BitVec 64) := by
    rw [obs_jal_pc hobs4,
      show (0x8001f1d0#64 : BitVec 64) + sign_extend (m := 64) (0x00f180#21) = (0x8002e350#64 : BitVec 64) from by apply BitVec.eq_of_toNat_eq; decide]
  have hrd4 : σ4.regs.get? Register.x1 = some (0x8001f1d4#64 : BitVec 64) := by
    have := obs_jal_rd hobs4 (by decide) (by decide) (by decide) (by decide) (by decide)
    rwa [show BitVec.addInt (0x8001f1d0#64) 4 = (0x8001f1d4#64 : BitVec 64) from by decide] at this
  have hp4 : PinsHold σ4 [⟨Register.x1, (0x8001f1d4#64 : BitVec 64)⟩, ⟨Register.x10, (v26 + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x11, (v10 + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x22, (v10 + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x26, v26⟩] :=
    ⟨hrd4, pins_jal hobs4 (by rfl) hp3⟩
  obtain ⟨vmi4, hmi4⟩ := obs_jal_minstret hobs4
  have hmemE4 : σ4.mem = m0 := by
    rw [hmem4]; exact hmemE3
  have hload4 : Lua.Vm.Arms.TextLoaded σ4.mem := by
    rw [hmem4]; exact hload3
  have hsteps4 : Steps c ⟨σ4, i4, c.steps + 1 + 1 + 1 + 1⟩ :=
    (((Steps.single hs1).trans (Steps.single hs2)).trans (Steps.single hs3)).trans (Steps.single hs4)
  exact ⟨⟨σ4, i4, c.steps + 1 + 1 + 1 + 1⟩, hsteps4,
    ⟨hG4, hpc4, hp4, ⟨vmi4, hmi4⟩, hi4, ⟨hload4, hmemE4⟩⟩⟩

/-- `0x8001f1d4`–`0x8001f1d8` (1 instruction), from `SegSt` to `SegSt`; side conditions are the `h*_<step>` hypotheses. -/
theorem seg_8001f1d4_8001f1d8_n
    (v10 : BitVec 64)
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    (hg_1 : (v10 == (0#64)) = false)
    : Triple (SegSt (0x8001f1d4#64) [⟨Register.x10, v10⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) (SegSt (0x8001f1d8#64) [⟨Register.x10, v10⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq⟩⟩ := hPre
  -- === step 1: 0x8001f1d4 `site_8001f1d4_nottaken` (bnottaken) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_8001f1d4_nottaken c.σ c.tick (c.steps) (0x8001f1d4#64)
      vmi v10 hgood hpc hmi hp0.1 hloaded rfl hg_1 htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x8001f1d8#64 : BitVec 64) := by
    have := obs_bnottaken_pc hobs1
    rwa [show BitVec.addInt (0x8001f1d4#64) 4 = (0x8001f1d8#64 : BitVec 64) from by decide] at this
  have hp1 : PinsHold σ1 [⟨Register.x10, v10⟩] :=
    pins_bnottaken hobs1 (by rfl) hp0
  obtain ⟨vmi1, hmi1⟩ := obs_bnottaken_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Lua.Vm.Arms.TextLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  have hsteps1 : Steps c ⟨σ1, i1, c.steps + 1⟩ :=
    Steps.single hs1
  exact ⟨⟨σ1, i1, c.steps + 1⟩, hsteps1,
    ⟨hG1, hpc1, hp1, ⟨vmi1, hmi1⟩, hi1, ⟨hload1, hmemE1⟩⟩⟩

/-- `0x8001f1d4`–`0x8001f1d8` (1 instruction), from `SegSt` to `SegSt`; side conditions are the `h*_<step>` hypotheses. -/
theorem seg_8001f1d4_8001f1d8_t
    (v10 : BitVec 64)
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    (hg_1 : (v10 == (0#64)) = true)
    : Triple (SegSt (0x8001f1d4#64) [⟨Register.x10, v10⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) (SegSt (0x8001f1dc#64) [⟨Register.x10, v10⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq⟩⟩ := hPre
  -- === step 1: 0x8001f1d4 `site_8001f1d4_taken` (btaken) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_8001f1d4_taken c.σ c.tick (c.steps) (0x8001f1d4#64)
      vmi v10 hgood hpc hmi hp0.1 hloaded rfl hg_1 htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x8001f1dc#64 : BitVec 64) := by
    rw [obs_btaken_pc hobs1,
      show (0x8001f1d4#64 : BitVec 64) + sign_extend (m := 64) (0x0008#13) = (0x8001f1dc#64 : BitVec 64) from by apply BitVec.eq_of_toNat_eq; decide]
  have hp1 : PinsHold σ1 [⟨Register.x10, v10⟩] :=
    pins_btaken hobs1 (by rfl) hp0
  obtain ⟨vmi1, hmi1⟩ := obs_btaken_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Lua.Vm.Arms.TextLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  have hsteps1 : Steps c ⟨σ1, i1, c.steps + 1⟩ :=
    Steps.single hs1
  exact ⟨⟨σ1, i1, c.steps + 1⟩, hsteps1,
    ⟨hG1, hpc1, hp1, ⟨vmi1, hmi1⟩, hi1, ⟨hload1, hmemE1⟩⟩⟩

/-- `0x8001f1d8`–`0x8001f1dc` (1 instruction), from `SegSt` to `SegSt`; side conditions are the `h*_<step>` hypotheses. -/
theorem seg_8001f1d8_8001f1dc
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    : Triple (SegSt (0x8001f1d8#64) []
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) (SegSt (0x8001c1e4#64) []
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq⟩⟩ := hPre
  -- === step 1: 0x8001f1d8 `site_8001f1d8` (j) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_8001f1d8 c.σ c.tick (c.steps) (0x8001f1d8#64)
      vmi hgood hpc hmi hloaded rfl (by decide) htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x8001c1e4#64 : BitVec 64) := by
    rw [obs_jr_pc hobs1,
      show (0x8001f1d8#64 : BitVec 64) + sign_extend (m := 64) (0x1fd00c#21) = (0x8001c1e4#64 : BitVec 64) from by apply BitVec.eq_of_toNat_eq; decide]
  have hp1 : PinsHold σ1 [] :=
    pins_jr hobs1 (by rfl) hp0
  obtain ⟨vmi1, hmi1⟩ := obs_jr_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Lua.Vm.Arms.TextLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  have hsteps1 : Steps c ⟨σ1, i1, c.steps + 1⟩ :=
    Steps.single hs1
  exact ⟨⟨σ1, i1, c.steps + 1⟩, hsteps1,
    ⟨hG1, hpc1, hp1, ⟨vmi1, hmi1⟩, hi1, ⟨hload1, hmemE1⟩⟩⟩

/-- `0x8001f1dc`–`0x8001f1ec` (4 instructions), from `SegSt` to `SegSt`; side conditions are the `h*_<step>` hypotheses. -/
theorem seg_8001f1dc_8001f1ec
    (v22 : BitVec 64)
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    (hlo_2 : 0x80000000 ≤ (((0x8001f1dc#64) + sign_extend (m := 64) ((0x0003d#20) +++ 0x000#12)) + sign_extend (m := 64) (0x29c#12)).toNat)
    (hhi_2 : (((0x8001f1dc#64) + sign_extend (m := 64) ((0x0003d#20) +++ 0x000#12)) + sign_extend (m := 64) (0x29c#12)).toNat + 8 ≤ 0x100000000)
    (hht_2 : (((0x8001f1dc#64) + sign_extend (m := 64) ((0x0003d#20) +++ 0x000#12)) + sign_extend (m := 64) (0x29c#12)).toNat + 8 ≤ tohostAddr ∨ tohostAddr + 8 ≤ (((0x8001f1dc#64) + sign_extend (m := 64) ((0x0003d#20) +++ 0x000#12)) + sign_extend (m := 64) (0x29c#12)).toNat)
    : Triple (SegSt (0x8001f1dc#64) [⟨Register.x22, v22⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) (SegSt (0x8002e3c0#64) [⟨Register.x1, (0x8001f1ec#64 : BitVec 64)⟩, ⟨Register.x10, (v22 + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x11, (sign_extend (m := 64) (bytesT8 (m0) (((0x8001f1dc#64) + sign_extend (m := 64) ((0x0003d#20) +++ 0x000#12)) + sign_extend (m := 64) (0x29c#12)).toNat : BitVec (8 * 8)))⟩, ⟨Register.x22, v22⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq⟩⟩ := hPre
  -- === step 1: 0x8001f1dc `site_8001f1dc` (alu) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_8001f1dc c.σ c.tick (c.steps) (0x8001f1dc#64)
      vmi hgood hpc hmi hloaded rfl htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x8001f1e0#64 : BitVec 64) := by
    have := obs_alu_pc hobs1
    rwa [show BitVec.addInt (0x8001f1dc#64) 4 = (0x8001f1e0#64 : BitVec 64) from by decide] at this
  have hrd1 : σ1.regs.get? Register.x11 = some ((0x8001f1dc#64) + sign_extend (m := 64) ((0x0003d#20) +++ 0x000#12)) :=
    obs_alu_rd hobs1 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hp1 : PinsHold σ1 [⟨Register.x11, ((0x8001f1dc#64) + sign_extend (m := 64) ((0x0003d#20) +++ 0x000#12))⟩, ⟨Register.x22, v22⟩] :=
    ⟨hrd1, pins_alu hobs1 (by rfl) hp0⟩
  obtain ⟨vmi1, hmi1⟩ := obs_alu_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Lua.Vm.Arms.TextLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  -- === step 2: 0x8001f1e0 `site_8001f1e0` (alu) ===
  obtain ⟨σ2, i2, hs2, hi2, hG2, hmem2, hobs2⟩ :=
    site_8001f1e0 σ1 i1 (c.steps + 1) (0x8001f1e0#64)
      vmi1 ((0x8001f1dc#64) + sign_extend (m := 64) ((0x0003d#20) +++ 0x000#12)) hG1 hpc1 hmi1 hp1.1 hload1 rfl hlo_2 hhi_2 hht_2 hi1
  have hpc2 : σ2.regs.get? Register.PC = some (0x8001f1e4#64 : BitVec 64) := by
    have := obs_alu_pc hobs2
    rwa [show BitVec.addInt (0x8001f1e0#64) 4 = (0x8001f1e4#64 : BitVec 64) from by decide] at this
  have hrd2 : σ2.regs.get? Register.x11 = some (sign_extend (m := 64) (bytesT8 (m0) (((0x8001f1dc#64) + sign_extend (m := 64) ((0x0003d#20) +++ 0x000#12)) + sign_extend (m := 64) (0x29c#12)).toNat : BitVec (8 * 8))) := by
    have := obs_alu_rd hobs2 (by decide) (by decide) (by decide) (by decide) (by decide)
    rwa [hmemE1] at this
  have hq2 : PinsHold σ1 [⟨Register.x22, v22⟩] :=
    ⟨hp1.2.1, trivial⟩
  have hp2 : PinsHold σ2 [⟨Register.x11, (sign_extend (m := 64) (bytesT8 (m0) (((0x8001f1dc#64) + sign_extend (m := 64) ((0x0003d#20) +++ 0x000#12)) + sign_extend (m := 64) (0x29c#12)).toNat : BitVec (8 * 8)))⟩, ⟨Register.x22, v22⟩] :=
    ⟨hrd2, pins_alu hobs2 (by rfl) hq2⟩
  obtain ⟨vmi2, hmi2⟩ := obs_alu_minstret hobs2
  have hmemE2 : σ2.mem = m0 := by
    rw [hmem2]; exact hmemE1
  have hload2 : Lua.Vm.Arms.TextLoaded σ2.mem := by
    rw [hmem2]; exact hload1
  -- === step 3: 0x8001f1e4 `site_8001f1e4` (alu) ===
  obtain ⟨σ3, i3, hs3, hi3, hG3, hmem3, hobs3⟩ :=
    site_8001f1e4 σ2 i2 (c.steps + 1 + 1) (0x8001f1e4#64)
      vmi2 v22 hG2 hpc2 hmi2 hp2.2.1 hload2 rfl hi2
  have hpc3 : σ3.regs.get? Register.PC = some (0x8001f1e8#64 : BitVec 64) := by
    have := obs_alu_pc hobs3
    rwa [show BitVec.addInt (0x8001f1e4#64) 4 = (0x8001f1e8#64 : BitVec 64) from by decide] at this
  have hrd3 : σ3.regs.get? Register.x10 = some (v22 + sign_extend (m := 64) (0x000#12)) :=
    obs_alu_rd hobs3 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hp3 : PinsHold σ3 [⟨Register.x10, (v22 + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x11, (sign_extend (m := 64) (bytesT8 (m0) (((0x8001f1dc#64) + sign_extend (m := 64) ((0x0003d#20) +++ 0x000#12)) + sign_extend (m := 64) (0x29c#12)).toNat : BitVec (8 * 8)))⟩, ⟨Register.x22, v22⟩] :=
    ⟨hrd3, pins_alu hobs3 (by rfl) hp2⟩
  obtain ⟨vmi3, hmi3⟩ := obs_alu_minstret hobs3
  have hmemE3 : σ3.mem = m0 := by
    rw [hmem3]; exact hmemE2
  have hload3 : Lua.Vm.Arms.TextLoaded σ3.mem := by
    rw [hmem3]; exact hload2
  -- === step 4: 0x8001f1e8 `site_8001f1e8` (jal) ===
  obtain ⟨σ4, i4, hs4, hi4, hG4, hmem4, hobs4⟩ :=
    site_8001f1e8 σ3 i3 (c.steps + 1 + 1 + 1) (0x8001f1e8#64)
      vmi3 hG3 hpc3 hmi3 hload3 rfl hi3
  have hpc4 : σ4.regs.get? Register.PC = some (0x8002e3c0#64 : BitVec 64) := by
    rw [obs_jal_pc hobs4,
      show (0x8001f1e8#64 : BitVec 64) + sign_extend (m := 64) (0x00f1d8#21) = (0x8002e3c0#64 : BitVec 64) from by apply BitVec.eq_of_toNat_eq; decide]
  have hrd4 : σ4.regs.get? Register.x1 = some (0x8001f1ec#64 : BitVec 64) := by
    have := obs_jal_rd hobs4 (by decide) (by decide) (by decide) (by decide) (by decide)
    rwa [show BitVec.addInt (0x8001f1e8#64) 4 = (0x8001f1ec#64 : BitVec 64) from by decide] at this
  have hp4 : PinsHold σ4 [⟨Register.x1, (0x8001f1ec#64 : BitVec 64)⟩, ⟨Register.x10, (v22 + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x11, (sign_extend (m := 64) (bytesT8 (m0) (((0x8001f1dc#64) + sign_extend (m := 64) ((0x0003d#20) +++ 0x000#12)) + sign_extend (m := 64) (0x29c#12)).toNat : BitVec (8 * 8)))⟩, ⟨Register.x22, v22⟩] :=
    ⟨hrd4, pins_jal hobs4 (by rfl) hp3⟩
  obtain ⟨vmi4, hmi4⟩ := obs_jal_minstret hobs4
  have hmemE4 : σ4.mem = m0 := by
    rw [hmem4]; exact hmemE3
  have hload4 : Lua.Vm.Arms.TextLoaded σ4.mem := by
    rw [hmem4]; exact hload3
  have hsteps4 : Steps c ⟨σ4, i4, c.steps + 1 + 1 + 1 + 1⟩ :=
    (((Steps.single hs1).trans (Steps.single hs2)).trans (Steps.single hs3)).trans (Steps.single hs4)
  exact ⟨⟨σ4, i4, c.steps + 1 + 1 + 1 + 1⟩, hsteps4,
    ⟨hG4, hpc4, hp4, ⟨vmi4, hmi4⟩, hi4, ⟨hload4, hmemE4⟩⟩⟩

/-- `0x8001f1ec`–`0x8001f1f0` (1 instruction), from `SegSt` to `SegSt`; side conditions are the `h*_<step>` hypotheses. -/
theorem seg_8001f1ec_8001f1f0_n
    (v10 : BitVec 64)
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    (hg_1 : zopz0zKzJ_s v10 (0#64) = false)
    : Triple (SegSt (0x8001f1ec#64) [⟨Register.x10, v10⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) (SegSt (0x8001f1f0#64) [⟨Register.x10, v10⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq⟩⟩ := hPre
  -- === step 1: 0x8001f1ec `site_8001f1ec_nottaken` (bnottaken) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_8001f1ec_nottaken c.σ c.tick (c.steps) (0x8001f1ec#64)
      vmi v10 hgood hpc hmi hp0.1 hloaded rfl hg_1 htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x8001f1f0#64 : BitVec 64) := by
    have := obs_bnottaken_pc hobs1
    rwa [show BitVec.addInt (0x8001f1ec#64) 4 = (0x8001f1f0#64 : BitVec 64) from by decide] at this
  have hp1 : PinsHold σ1 [⟨Register.x10, v10⟩] :=
    pins_bnottaken hobs1 (by rfl) hp0
  obtain ⟨vmi1, hmi1⟩ := obs_bnottaken_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Lua.Vm.Arms.TextLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  have hsteps1 : Steps c ⟨σ1, i1, c.steps + 1⟩ :=
    Steps.single hs1
  exact ⟨⟨σ1, i1, c.steps + 1⟩, hsteps1,
    ⟨hG1, hpc1, hp1, ⟨vmi1, hmi1⟩, hi1, ⟨hload1, hmemE1⟩⟩⟩

/-- `0x8001f1ec`–`0x8001f1f0` (1 instruction), from `SegSt` to `SegSt`; side conditions are the `h*_<step>` hypotheses. -/
theorem seg_8001f1ec_8001f1f0_t
    (v10 : BitVec 64)
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    (hg_1 : zopz0zKzJ_s v10 (0#64) = true)
    : Triple (SegSt (0x8001f1ec#64) [⟨Register.x10, v10⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) (SegSt (0x8001f1f4#64) [⟨Register.x10, v10⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq⟩⟩ := hPre
  -- === step 1: 0x8001f1ec `site_8001f1ec_taken` (btaken) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_8001f1ec_taken c.σ c.tick (c.steps) (0x8001f1ec#64)
      vmi v10 hgood hpc hmi hp0.1 hloaded rfl hg_1 htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x8001f1f4#64 : BitVec 64) := by
    rw [obs_btaken_pc hobs1,
      show (0x8001f1ec#64 : BitVec 64) + sign_extend (m := 64) (0x0008#13) = (0x8001f1f4#64 : BitVec 64) from by apply BitVec.eq_of_toNat_eq; decide]
  have hp1 : PinsHold σ1 [⟨Register.x10, v10⟩] :=
    pins_btaken hobs1 (by rfl) hp0
  obtain ⟨vmi1, hmi1⟩ := obs_btaken_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Lua.Vm.Arms.TextLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  have hsteps1 : Steps c ⟨σ1, i1, c.steps + 1⟩ :=
    Steps.single hs1
  exact ⟨⟨σ1, i1, c.steps + 1⟩, hsteps1,
    ⟨hG1, hpc1, hp1, ⟨vmi1, hmi1⟩, hi1, ⟨hload1, hmemE1⟩⟩⟩

/-- `0x8001f1f0`–`0x8001f1f4` (1 instruction), from `SegSt` to `SegSt`; side conditions are the `h*_<step>` hypotheses. -/
theorem seg_8001f1f0_8001f1f4
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    : Triple (SegSt (0x8001f1f0#64) []
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) (SegSt (0x8001c1e4#64) []
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq⟩⟩ := hPre
  -- === step 1: 0x8001f1f0 `site_8001f1f0` (j) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_8001f1f0 c.σ c.tick (c.steps) (0x8001f1f0#64)
      vmi hgood hpc hmi hloaded rfl (by decide) htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x8001c1e4#64 : BitVec 64) := by
    rw [obs_jr_pc hobs1,
      show (0x8001f1f0#64 : BitVec 64) + sign_extend (m := 64) (0x1fcff4#21) = (0x8001c1e4#64 : BitVec 64) from by apply BitVec.eq_of_toNat_eq; decide]
  have hp1 : PinsHold σ1 [] :=
    pins_jr hobs1 (by rfl) hp0
  obtain ⟨vmi1, hmi1⟩ := obs_jr_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Lua.Vm.Arms.TextLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  have hsteps1 : Steps c ⟨σ1, i1, c.steps + 1⟩ :=
    Steps.single hs1
  exact ⟨⟨σ1, i1, c.steps + 1⟩, hsteps1,
    ⟨hG1, hpc1, hp1, ⟨vmi1, hmi1⟩, hi1, ⟨hload1, hmemE1⟩⟩⟩

/-- `0x8001f1f4`–`0x8001f204` (4 instructions), from `SegSt` to `SegSt`; side conditions are the `h*_<step>` hypotheses. -/
theorem seg_8001f1f4_8001f204
    (v22 : BitVec 64)
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    (hlo_2 : 0x80000000 ≤ (((0x8001f1f4#64) + sign_extend (m := 64) ((0x0003d#20) +++ 0x000#12)) + sign_extend (m := 64) (0x28c#12)).toNat)
    (hhi_2 : (((0x8001f1f4#64) + sign_extend (m := 64) ((0x0003d#20) +++ 0x000#12)) + sign_extend (m := 64) (0x28c#12)).toNat + 8 ≤ 0x100000000)
    (hht_2 : (((0x8001f1f4#64) + sign_extend (m := 64) ((0x0003d#20) +++ 0x000#12)) + sign_extend (m := 64) (0x28c#12)).toNat + 8 ≤ tohostAddr ∨ tohostAddr + 8 ≤ (((0x8001f1f4#64) + sign_extend (m := 64) ((0x0003d#20) +++ 0x000#12)) + sign_extend (m := 64) (0x28c#12)).toNat)
    : Triple (SegSt (0x8001f1f4#64) [⟨Register.x22, v22⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) (SegSt (0x8002e460#64) [⟨Register.x1, (0x8001f204#64 : BitVec 64)⟩, ⟨Register.x10, (v22 + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x11, (sign_extend (m := 64) (bytesT8 (m0) (((0x8001f1f4#64) + sign_extend (m := 64) ((0x0003d#20) +++ 0x000#12)) + sign_extend (m := 64) (0x28c#12)).toNat : BitVec (8 * 8)))⟩, ⟨Register.x22, v22⟩]
      (fun σ => Lua.Vm.Arms.TextLoaded σ.mem ∧ σ.mem = m0)) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq⟩⟩ := hPre
  -- === step 1: 0x8001f1f4 `site_8001f1f4` (alu) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_8001f1f4 c.σ c.tick (c.steps) (0x8001f1f4#64)
      vmi hgood hpc hmi hloaded rfl htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x8001f1f8#64 : BitVec 64) := by
    have := obs_alu_pc hobs1
    rwa [show BitVec.addInt (0x8001f1f4#64) 4 = (0x8001f1f8#64 : BitVec 64) from by decide] at this
  have hrd1 : σ1.regs.get? Register.x11 = some ((0x8001f1f4#64) + sign_extend (m := 64) ((0x0003d#20) +++ 0x000#12)) :=
    obs_alu_rd hobs1 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hp1 : PinsHold σ1 [⟨Register.x11, ((0x8001f1f4#64) + sign_extend (m := 64) ((0x0003d#20) +++ 0x000#12))⟩, ⟨Register.x22, v22⟩] :=
    ⟨hrd1, pins_alu hobs1 (by rfl) hp0⟩
  obtain ⟨vmi1, hmi1⟩ := obs_alu_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Lua.Vm.Arms.TextLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  -- === step 2: 0x8001f1f8 `site_8001f1f8` (alu) ===
  obtain ⟨σ2, i2, hs2, hi2, hG2, hmem2, hobs2⟩ :=
    site_8001f1f8 σ1 i1 (c.steps + 1) (0x8001f1f8#64)
      vmi1 ((0x8001f1f4#64) + sign_extend (m := 64) ((0x0003d#20) +++ 0x000#12)) hG1 hpc1 hmi1 hp1.1 hload1 rfl hlo_2 hhi_2 hht_2 hi1
  have hpc2 : σ2.regs.get? Register.PC = some (0x8001f1fc#64 : BitVec 64) := by
    have := obs_alu_pc hobs2
    rwa [show BitVec.addInt (0x8001f1f8#64) 4 = (0x8001f1fc#64 : BitVec 64) from by decide] at this
  have hrd2 : σ2.regs.get? Register.x11 = some (sign_extend (m := 64) (bytesT8 (m0) (((0x8001f1f4#64) + sign_extend (m := 64) ((0x0003d#20) +++ 0x000#12)) + sign_extend (m := 64) (0x28c#12)).toNat : BitVec (8 * 8))) := by
    have := obs_alu_rd hobs2 (by decide) (by decide) (by decide) (by decide) (by decide)
    rwa [hmemE1] at this
  have hq2 : PinsHold σ1 [⟨Register.x22, v22⟩] :=
    ⟨hp1.2.1, trivial⟩
  have hp2 : PinsHold σ2 [⟨Register.x11, (sign_extend (m := 64) (bytesT8 (m0) (((0x8001f1f4#64) + sign_extend (m := 64) ((0x0003d#20) +++ 0x000#12)) + sign_extend (m := 64) (0x28c#12)).toNat : BitVec (8 * 8)))⟩, ⟨Register.x22, v22⟩] :=
    ⟨hrd2, pins_alu hobs2 (by rfl) hq2⟩
  obtain ⟨vmi2, hmi2⟩ := obs_alu_minstret hobs2
  have hmemE2 : σ2.mem = m0 := by
    rw [hmem2]; exact hmemE1
  have hload2 : Lua.Vm.Arms.TextLoaded σ2.mem := by
    rw [hmem2]; exact hload1
  -- === step 3: 0x8001f1fc `site_8001f1fc` (alu) ===
  obtain ⟨σ3, i3, hs3, hi3, hG3, hmem3, hobs3⟩ :=
    site_8001f1fc σ2 i2 (c.steps + 1 + 1) (0x8001f1fc#64)
      vmi2 v22 hG2 hpc2 hmi2 hp2.2.1 hload2 rfl hi2
  have hpc3 : σ3.regs.get? Register.PC = some (0x8001f200#64 : BitVec 64) := by
    have := obs_alu_pc hobs3
    rwa [show BitVec.addInt (0x8001f1fc#64) 4 = (0x8001f200#64 : BitVec 64) from by decide] at this
  have hrd3 : σ3.regs.get? Register.x10 = some (v22 + sign_extend (m := 64) (0x000#12)) :=
    obs_alu_rd hobs3 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hp3 : PinsHold σ3 [⟨Register.x10, (v22 + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x11, (sign_extend (m := 64) (bytesT8 (m0) (((0x8001f1f4#64) + sign_extend (m := 64) ((0x0003d#20) +++ 0x000#12)) + sign_extend (m := 64) (0x28c#12)).toNat : BitVec (8 * 8)))⟩, ⟨Register.x22, v22⟩] :=
    ⟨hrd3, pins_alu hobs3 (by rfl) hp2⟩
  obtain ⟨vmi3, hmi3⟩ := obs_alu_minstret hobs3
  have hmemE3 : σ3.mem = m0 := by
    rw [hmem3]; exact hmemE2
  have hload3 : Lua.Vm.Arms.TextLoaded σ3.mem := by
    rw [hmem3]; exact hload2
  -- === step 4: 0x8001f200 `site_8001f200` (jal) ===
  obtain ⟨σ4, i4, hs4, hi4, hG4, hmem4, hobs4⟩ :=
    site_8001f200 σ3 i3 (c.steps + 1 + 1 + 1) (0x8001f200#64)
      vmi3 hG3 hpc3 hmi3 hload3 rfl hi3
  have hpc4 : σ4.regs.get? Register.PC = some (0x8002e460#64 : BitVec 64) := by
    rw [obs_jal_pc hobs4,
      show (0x8001f200#64 : BitVec 64) + sign_extend (m := 64) (0x00f260#21) = (0x8002e460#64 : BitVec 64) from by apply BitVec.eq_of_toNat_eq; decide]
  have hrd4 : σ4.regs.get? Register.x1 = some (0x8001f204#64 : BitVec 64) := by
    have := obs_jal_rd hobs4 (by decide) (by decide) (by decide) (by decide) (by decide)
    rwa [show BitVec.addInt (0x8001f200#64) 4 = (0x8001f204#64 : BitVec 64) from by decide] at this
  have hp4 : PinsHold σ4 [⟨Register.x1, (0x8001f204#64 : BitVec 64)⟩, ⟨Register.x10, (v22 + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x11, (sign_extend (m := 64) (bytesT8 (m0) (((0x8001f1f4#64) + sign_extend (m := 64) ((0x0003d#20) +++ 0x000#12)) + sign_extend (m := 64) (0x28c#12)).toNat : BitVec (8 * 8)))⟩, ⟨Register.x22, v22⟩] :=
    ⟨hrd4, pins_jal hobs4 (by rfl) hp3⟩
  obtain ⟨vmi4, hmi4⟩ := obs_jal_minstret hobs4
  have hmemE4 : σ4.mem = m0 := by
    rw [hmem4]; exact hmemE3
  have hload4 : Lua.Vm.Arms.TextLoaded σ4.mem := by
    rw [hmem4]; exact hload3
  have hsteps4 : Steps c ⟨σ4, i4, c.steps + 1 + 1 + 1 + 1⟩ :=
    (((Steps.single hs1).trans (Steps.single hs2)).trans (Steps.single hs3)).trans (Steps.single hs4)
  exact ⟨⟨σ4, i4, c.steps + 1 + 1 + 1 + 1⟩, hsteps4,
    ⟨hG4, hpc4, hp4, ⟨vmi4, hmi4⟩, hi4, ⟨hload4, hmemE4⟩⟩⟩

end Lua.Vm.Arms
