import Lua.Vm.Code.LuaH_getshortstr
import Lua.Vm.Image
import Vsa.Sim.Code.FixedImage

/-! GENERATED by scripts/gen_lua_code.py -- do not edit.

`LuaH_getshortstrLoaded` from the packed `.text` of `Lua/Vm/Image.lean`: each pinned
byte is `h offset (by decide)`, checked by the kernel against the image. -/

namespace Lua.Vm.Code

theorem textLoaded_luaH_getshortstrChunk0 {mem : Std.ExtHashMap Nat (BitVec 8)}
    (h : Vsa.Sim.Code.FixedBytesLoaded Image.textBase Image.textSize Image.textByte mem) : luaH_getshortstrChunk0 mem := by
  exact ⟨h 92964 (by decide),
    h 92965 (by decide),
    h 92966 (by decide),
    h 92967 (by decide),
    h 92968 (by decide),
    h 92969 (by decide),
    h 92970 (by decide),
    h 92971 (by decide),
    h 92972 (by decide),
    h 92973 (by decide),
    h 92974 (by decide),
    h 92975 (by decide),
    h 92976 (by decide),
    h 92977 (by decide),
    h 92978 (by decide),
    h 92979 (by decide),
    h 92980 (by decide),
    h 92981 (by decide),
    h 92982 (by decide),
    h 92983 (by decide),
    h 92984 (by decide),
    h 92985 (by decide),
    h 92986 (by decide),
    h 92987 (by decide),
    h 92988 (by decide),
    h 92989 (by decide),
    h 92990 (by decide),
    h 92991 (by decide),
    h 92992 (by decide),
    h 92993 (by decide),
    h 92994 (by decide),
    h 92995 (by decide),
    h 92996 (by decide),
    h 92997 (by decide),
    h 92998 (by decide),
    h 92999 (by decide),
    h 93000 (by decide),
    h 93001 (by decide),
    h 93002 (by decide),
    h 93003 (by decide),
    h 93004 (by decide),
    h 93005 (by decide),
    h 93006 (by decide),
    h 93007 (by decide),
    h 93008 (by decide),
    h 93009 (by decide),
    h 93010 (by decide),
    h 93011 (by decide),
    h 93012 (by decide),
    h 93013 (by decide),
    h 93014 (by decide),
    h 93015 (by decide),
    h 93016 (by decide),
    h 93017 (by decide),
    h 93018 (by decide),
    h 93019 (by decide),
    h 93020 (by decide),
    h 93021 (by decide),
    h 93022 (by decide),
    h 93023 (by decide),
    h 93024 (by decide),
    h 93025 (by decide),
    h 93026 (by decide),
    h 93027 (by decide)⟩

theorem textLoaded_luaH_getshortstrChunk1 {mem : Std.ExtHashMap Nat (BitVec 8)}
    (h : Vsa.Sim.Code.FixedBytesLoaded Image.textBase Image.textSize Image.textByte mem) : luaH_getshortstrChunk1 mem := by
  exact ⟨h 93028 (by decide),
    h 93029 (by decide),
    h 93030 (by decide),
    h 93031 (by decide),
    h 93032 (by decide),
    h 93033 (by decide),
    h 93034 (by decide),
    h 93035 (by decide),
    h 93036 (by decide),
    h 93037 (by decide),
    h 93038 (by decide),
    h 93039 (by decide),
    h 93040 (by decide),
    h 93041 (by decide),
    h 93042 (by decide),
    h 93043 (by decide),
    h 93044 (by decide),
    h 93045 (by decide),
    h 93046 (by decide),
    h 93047 (by decide),
    h 93048 (by decide),
    h 93049 (by decide),
    h 93050 (by decide),
    h 93051 (by decide),
    h 93052 (by decide),
    h 93053 (by decide),
    h 93054 (by decide),
    h 93055 (by decide),
    h 93056 (by decide),
    h 93057 (by decide),
    h 93058 (by decide),
    h 93059 (by decide),
    h 93060 (by decide),
    h 93061 (by decide),
    h 93062 (by decide),
    h 93063 (by decide),
    h 93064 (by decide),
    h 93065 (by decide),
    h 93066 (by decide),
    h 93067 (by decide),
    h 93068 (by decide),
    h 93069 (by decide),
    h 93070 (by decide),
    h 93071 (by decide)⟩

theorem textLoaded_LuaH_getshortstrLoaded {mem : Std.ExtHashMap Nat (BitVec 8)}
    (h : Vsa.Sim.Code.FixedBytesLoaded Image.textBase Image.textSize Image.textByte mem) : LuaH_getshortstrLoaded mem :=
  ⟨textLoaded_luaH_getshortstrChunk0 h, textLoaded_luaH_getshortstrChunk1 h⟩

#print axioms textLoaded_LuaH_getshortstrLoaded

end Lua.Vm.Code
