import Lua.Vm.Sim.Kit.At
import Lua.Vm.Sim.Kit.Summaries
import Lua.Vm.Sim.Kit.AtCond
import Lua.Vm.Arms

/-! GENERATED by scripts/gen_lua_at.py -- do not edit.

The at-lemmas of `OP_LT` (jump-table target `0x8001c894`): its
generated segments between location-list rows (`Lua/Vm/Sim/Kit/At.lean`),
each proved in its own declaration, for every path to the fetch head through
summarised calls, and to the entry of an error exit (`luaG_runerror`, …).
Paths not followed:

* `seg_8001c8e8_8001c8f8`: call to 0x800196c4
* `seg_8001ead8_8001eae0`: call to 0x8002f200
* `seg_8001efec_8001effc`: instruction slt a0,a0,a5
* `seg_8001f100_8001f108`: call to 0x8002f200
* `seg_8001f900_8001f908`: call to 0x8002bb14
* `seg_8001fa60_8001fa6c`: call to 0x8002e460
* `seg_8001fb00_8001fb08`: call to 0x8002bb14
-/

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail ConcurrencyInterfaceV1 Vsa
open Vsa.Sim Vsa.Logic
open Lua.Vm.Sim Lua.Vm.Sim.At Lua.Bytecode Lua.Vm.Layout
open Vsa.Machine (Config)

namespace Lua.Vm.At.LT

@[at_row] abbrev r0 (X : Cx) : List Pin :=
  [⟨Register.x2, (Loc.den X .sp)⟩,
   ⟨Register.x3, (Loc.den X (.lit (BitVec.ofNat 64 symGlobalPointer)))⟩,
   ⟨Register.x8, (Loc.den X .L)⟩,
   ⟨Register.x9, (Loc.den X (.lit (BitVec.ofNat 64 (Arms.jtEntries - 1))))⟩,
   ⟨Register.x12, (Loc.den X (.nat ⟨[(1, .base), (16, .b)], 0, 0⟩))⟩,
   ⟨Register.x14, (Loc.den X (.tag .a 0))⟩,
   ⟨Register.x15, (Loc.den X (.nat ⟨[(1, .base), (16, .a)], 0, 0⟩))⟩,
   ⟨Register.x18, (Loc.den X (.lit (BitVec.ofNat 64 vNumInt)))⟩,
   ⟨Register.x19, (Loc.den X (.pc 1))⟩,
   ⟨Register.x20, (Loc.den X .insw)⟩,
   ⟨Register.x21, (Loc.den X (.lit 0x0#64))⟩,
   ⟨Register.x23, (Loc.den X .ci)⟩,
   ⟨Register.x24, (Loc.den X (.lit (BitVec.ofNat 64 Arms.jtBase)))⟩,
   ⟨Register.x25, (Loc.den X .base)⟩,
   ⟨Register.x27, (Loc.den X (.pc 0))⟩]

@[at_row] abbrev r1 (X : Cx) : List Pin :=
  [⟨Register.x2, (Loc.den X .sp)⟩,
   ⟨Register.x3, (Loc.den X (.lit (BitVec.ofNat 64 symGlobalPointer)))⟩,
   ⟨Register.x8, (Loc.den X .L)⟩,
   ⟨Register.x9, (Loc.den X (.lit (BitVec.ofNat 64 (Arms.jtEntries - 1))))⟩,
   ⟨Register.x12, (Loc.den X (.nat ⟨[(1, .base), (16, .b)], 0, 0⟩))⟩,
   ⟨Register.x14, (Loc.den X (.lit ((Loc.den X (.tag .a 0)) &&& (Loc.den X (.lit 0xf#64)))))⟩,
   ⟨Register.x15, (Loc.den X (.nat ⟨[(1, .base), (16, .a)], 0, 0⟩))⟩,
   ⟨Register.x18, (Loc.den X (.lit (BitVec.ofNat 64 vNumInt)))⟩,
   ⟨Register.x19, (Loc.den X (.pc 1))⟩,
   ⟨Register.x20, (Loc.den X .insw)⟩,
   ⟨Register.x21, (Loc.den X (.lit 0x0#64))⟩,
   ⟨Register.x23, (Loc.den X .ci)⟩,
   ⟨Register.x24, (Loc.den X (.lit (BitVec.ofNat 64 Arms.jtBase)))⟩,
   ⟨Register.x25, (Loc.den X .base)⟩,
   ⟨Register.x27, (Loc.den X (.pc 0))⟩]

@[at_row] abbrev r2 (X : Cx) : List Pin :=
  [⟨Register.x2, (Loc.den X .sp)⟩,
   ⟨Register.x3, (Loc.den X (.lit (BitVec.ofNat 64 symGlobalPointer)))⟩,
   ⟨Register.x8, (Loc.den X .L)⟩,
   ⟨Register.x9, (Loc.den X (.lit (BitVec.ofNat 64 (Arms.jtEntries - 1))))⟩,
   ⟨Register.x11, (Loc.den X (.cell ⟨[(1, .ci)], 8, 0⟩))⟩,
   ⟨Register.x12, (Loc.den X (.nat ⟨[(1, .base), (16, .b)], 0, 0⟩))⟩,
   ⟨Register.x13, (Loc.den X (.lit 0x4#64))⟩,
   ⟨Register.x14, (Loc.den X (.lit ((Loc.den X (.tag .a 0)) &&& (Loc.den X (.lit 0xf#64)))))⟩,
   ⟨Register.x15, (Loc.den X (.nat ⟨[(1, .base), (16, .a)], 0, 0⟩))⟩,
   ⟨Register.x18, (Loc.den X (.lit (BitVec.ofNat 64 vNumInt)))⟩,
   ⟨Register.x19, (Loc.den X (.pc 1))⟩,
   ⟨Register.x20, (Loc.den X .insw)⟩,
   ⟨Register.x21, (Loc.den X (.lit 0x0#64))⟩,
   ⟨Register.x23, (Loc.den X .ci)⟩,
   ⟨Register.x24, (Loc.den X (.lit (BitVec.ofNat 64 Arms.jtBase)))⟩,
   ⟨Register.x25, (Loc.den X .base)⟩,
   ⟨Register.x27, (Loc.den X (.pc 0))⟩]

@[at_row] abbrev r3 (X : Cx) : List Pin :=
  [⟨Register.x2, (Loc.den X .sp)⟩,
   ⟨Register.x3, (Loc.den X (.lit (BitVec.ofNat 64 symGlobalPointer)))⟩,
   ⟨Register.x8, (Loc.den X .L)⟩,
   ⟨Register.x9, (Loc.den X (.lit (BitVec.ofNat 64 (Arms.jtEntries - 1))))⟩,
   ⟨Register.x12, (Loc.den X (.nat ⟨[(1, .base), (16, .b)], 0, 0⟩))⟩,
   ⟨Register.x13, (Loc.den X (.lit ((Loc.den X (.tag .b 0)) &&& (Loc.den X (.lit 0xf#64)))))⟩,
   ⟨Register.x14, (Loc.den X (.lit ((Loc.den X (.tag .a 0)) &&& (Loc.den X (.lit 0xf#64)))))⟩,
   ⟨Register.x15, (Loc.den X (.nat ⟨[(1, .base), (16, .a)], 0, 0⟩))⟩,
   ⟨Register.x18, (Loc.den X (.lit (BitVec.ofNat 64 vNumInt)))⟩,
   ⟨Register.x19, (Loc.den X (.pc 1))⟩,
   ⟨Register.x20, (Loc.den X .insw)⟩,
   ⟨Register.x21, (Loc.den X (.lit 0x0#64))⟩,
   ⟨Register.x23, (Loc.den X .ci)⟩,
   ⟨Register.x24, (Loc.den X (.lit (BitVec.ofNat 64 Arms.jtBase)))⟩,
   ⟨Register.x25, (Loc.den X .base)⟩,
   ⟨Register.x27, (Loc.den X (.pc 0))⟩]

@[at_row] abbrev r4 (X : Cx) : List Pin :=
  [⟨Register.x1, (Loc.den X (.lit 0x8001e260#64))⟩,
   ⟨Register.x2, (Loc.den X .sp)⟩,
   ⟨Register.x3, (Loc.den X (.lit (BitVec.ofNat 64 symGlobalPointer)))⟩,
   ⟨Register.x8, (Loc.den X .L)⟩,
   ⟨Register.x9, (Loc.den X (.lit (BitVec.ofNat 64 (Arms.jtEntries - 1))))⟩,
   ⟨Register.x10, (Loc.den X (.val .a 0))⟩,
   ⟨Register.x11, (Loc.den X (.val .b 0))⟩,
   ⟨Register.x12, (Loc.den X (.nat ⟨[(1, .base), (16, .b)], 0, 0⟩))⟩,
   ⟨Register.x15, (Loc.den X (.nat ⟨[(1, .base), (16, .a)], 0, 0⟩))⟩,
   ⟨Register.x18, (Loc.den X (.lit (BitVec.ofNat 64 vNumInt)))⟩,
   ⟨Register.x19, (Loc.den X (.pc 1))⟩,
   ⟨Register.x20, (Loc.den X .insw)⟩,
   ⟨Register.x21, (Loc.den X (.lit 0x0#64))⟩,
   ⟨Register.x23, (Loc.den X .ci)⟩,
   ⟨Register.x24, (Loc.den X (.lit (BitVec.ofNat 64 Arms.jtBase)))⟩,
   ⟨Register.x25, (Loc.den X .base)⟩,
   ⟨Register.x27, (Loc.den X (.pc 0))⟩]

@[at_row] abbrev r5 (X : Cx) : List Pin :=
  [⟨Register.x2, (Loc.den X .sp)⟩,
   ⟨Register.x3, (Loc.den X (.lit (BitVec.ofNat 64 symGlobalPointer)))⟩,
   ⟨Register.x8, (Loc.den X .L)⟩,
   ⟨Register.x9, (Loc.den X (.lit (BitVec.ofNat 64 (Arms.jtEntries - 1))))⟩,
   ⟨Register.x10, (Loc.den X (.lit (if lexLt (sOf X .a) (sOf X .b) then 1#64 else 0#64)))⟩,
   ⟨Register.x18, (Loc.den X (.lit (BitVec.ofNat 64 vNumInt)))⟩,
   ⟨Register.x19, (Loc.den X (.pc 1))⟩,
   ⟨Register.x20, (Loc.den X .insw)⟩,
   ⟨Register.x21, (Loc.den X (.lit 0x0#64))⟩,
   ⟨Register.x23, (Loc.den X .ci)⟩,
   ⟨Register.x24, (Loc.den X (.lit (BitVec.ofNat 64 Arms.jtBase)))⟩,
   ⟨Register.x25, (Loc.den X .base)⟩,
   ⟨Register.x27, (Loc.den X (.pc 0))⟩]

@[at_row] abbrev r6 (X : Cx) : List Pin :=
  [⟨Register.x2, (Loc.den X .sp)⟩,
   ⟨Register.x3, (Loc.den X (.lit (BitVec.ofNat 64 symGlobalPointer)))⟩,
   ⟨Register.x8, (Loc.den X .L)⟩,
   ⟨Register.x9, (Loc.den X (.lit (BitVec.ofNat 64 (Arms.jtEntries - 1))))⟩,
   ⟨Register.x10, (Loc.den X (.lit (if lexLt (sOf X .a) (sOf X .b) then 1#64 else 0#64)))⟩,
   ⟨Register.x18, (Loc.den X (.lit (BitVec.ofNat 64 vNumInt)))⟩,
   ⟨Register.x19, (Loc.den X (.pc 1))⟩,
   ⟨Register.x20, (Loc.den X .insw)⟩,
   ⟨Register.x21, (Loc.den X (.lit 0x0#64))⟩,
   ⟨Register.x23, (Loc.den X .ci)⟩,
   ⟨Register.x24, (Loc.den X (.lit (BitVec.ofNat 64 Arms.jtBase)))⟩,
   ⟨Register.x25, (Loc.den X .base)⟩,
   ⟨Register.x27, (Loc.den X (.pc 0))⟩,
   ⟨Register.x31, (Loc.den X (.lit 0x0#64))⟩]

@[at_row] abbrev r7 (X : Cx) : List Pin :=
  [⟨Register.x2, (Loc.den X .sp)⟩,
   ⟨Register.x3, (Loc.den X (.lit (BitVec.ofNat 64 symGlobalPointer)))⟩,
   ⟨Register.x8, (Loc.den X .L)⟩,
   ⟨Register.x9, (Loc.den X (.lit (BitVec.ofNat 64 (Arms.jtEntries - 1))))⟩,
   ⟨Register.x10, (Loc.den X (.lit (if lexLt (sOf X .a) (sOf X .b) then 1#64 else 0#64)))⟩,
   ⟨Register.x15, (Loc.den X (.lit (if X.ins.k then 1#64 else 0#64)))⟩,
   ⟨Register.x18, (Loc.den X (.lit (BitVec.ofNat 64 vNumInt)))⟩,
   ⟨Register.x19, (Loc.den X (.pc 1))⟩,
   ⟨Register.x20, (Loc.den X .insw)⟩,
   ⟨Register.x21, (Loc.den X (.lit 0x0#64))⟩,
   ⟨Register.x23, (Loc.den X .ci)⟩,
   ⟨Register.x24, (Loc.den X (.lit (BitVec.ofNat 64 Arms.jtBase)))⟩,
   ⟨Register.x25, (Loc.den X .base)⟩,
   ⟨Register.x27, (Loc.den X (.pc 0))⟩]

@[at_row] abbrev r8 (X : Cx) : List Pin :=
  [⟨Register.x2, (Loc.den X .sp)⟩,
   ⟨Register.x3, (Loc.den X (.lit (BitVec.ofNat 64 symGlobalPointer)))⟩,
   ⟨Register.x8, (Loc.den X .L)⟩,
   ⟨Register.x9, (Loc.den X (.lit (BitVec.ofNat 64 (Arms.jtEntries - 1))))⟩,
   ⟨Register.x18, (Loc.den X (.lit (BitVec.ofNat 64 vNumInt)))⟩,
   ⟨Register.x19, (Loc.den X (.pc 1))⟩,
   ⟨Register.x20, (Loc.den X .insw)⟩,
   ⟨Register.x21, (Loc.den X (.lit 0x0#64))⟩,
   ⟨Register.x23, (Loc.den X .ci)⟩,
   ⟨Register.x24, (Loc.den X (.lit (BitVec.ofNat 64 Arms.jtBase)))⟩,
   ⟨Register.x25, (Loc.den X .base)⟩,
   ⟨Register.x27, (Loc.den X (.pc 2))⟩]

@[at_row] abbrev r9 (X : Cx) : List Pin :=
  [⟨Register.x2, (Loc.den X .sp)⟩,
   ⟨Register.x3, (Loc.den X (.lit (BitVec.ofNat 64 symGlobalPointer)))⟩,
   ⟨Register.x8, (Loc.den X .L)⟩,
   ⟨Register.x9, (Loc.den X (.lit (BitVec.ofNat 64 (Arms.jtEntries - 1))))⟩,
   ⟨Register.x15, (Loc.den X (.lit 0xffffffffff000002#64))⟩,
   ⟨Register.x18, (Loc.den X (.lit (BitVec.ofNat 64 vNumInt)))⟩,
   ⟨Register.x19, (Loc.den X (.pc 1))⟩,
   ⟨Register.x20, (Loc.den X .insw)⟩,
   ⟨Register.x21, (Loc.den X (.lit 0x0#64))⟩,
   ⟨Register.x23, (Loc.den X .ci)⟩,
   ⟨Register.x24, (Loc.den X (.lit (BitVec.ofNat 64 Arms.jtBase)))⟩,
   ⟨Register.x25, (Loc.den X .base)⟩,
   ⟨Register.x27, (Loc.den X (.lit (BitVec.ofNat 64 (X.w.code + 4 * jmpPc X))))⟩,
   ⟨Register.x31, (Loc.den X (.lit 0x0#64))⟩]

@[at_row] abbrev m0 : List Ent :=
  [.sd ⟨[(1, .L)], 16, 0⟩ (.cell ⟨[(1, .ci)], 8, 0⟩),
   .sd ⟨[(1, .ci)], 32, 0⟩ (.pc 1)]

@[at_row] abbrev m1 : List Ent :=
  [.sd ⟨[(1, .sp)], 0, 48⟩ .insw,
   .sd ⟨[(1, .sp)], 0, 40⟩ (.pc 1),
   .sd ⟨[(1, .sp)], 0, 32⟩ (.lit (BitVec.ofNat 64 vNumInt)),
   .sd ⟨[(1, .sp)], 0, 24⟩ (.lit (BitVec.ofNat 64 (Arms.jtEntries - 1))),
   .sd ⟨[(1, .sp)], 0, 8⟩ (.lit 0x8001e260#64),
   .sd ⟨[(1, .sp)], 0, 16⟩ .L,
   .sd ⟨[(1, .L)], 16, 0⟩ (.cell ⟨[(1, .ci)], 8, 0⟩),
   .sd ⟨[(1, .ci)], 32, 0⟩ (.pc 1)]

theorem at_8001c894_8001c8bc_t (X : Cx) (hX : X.Ok) (hs_a0 : X.ins.a + 0 < X.p.maxstacksize) (hg_10 : ((Loc.den X (.tag .a 0)) != (Loc.den X (.lit (BitVec.ofNat 64 vNumInt)))) = true) :
    AtStep X 0x8001c894#64 (headRow X) [] 0x8001c8c0#64 (r0 X) [] := by
  at_seg Lua.Vm.Arms.seg_8001c894_8001c8bc_t

theorem at_8001c8c0_8001c8c8_n (X : Cx) (hX : X.Ok) (hg_2 : ((Loc.den X (.lit ((Loc.den X (.tag .a 0)) &&& (Loc.den X (.lit 0xf#64))))) == (Loc.den X (.lit (BitVec.ofNat 64 vNumInt)))) = false) :
    AtStep X 0x8001c8c0#64 (r0 X) [] 0x8001c8c8#64 (r1 X) [] := by
  at_seg Lua.Vm.Arms.seg_8001c8c0_8001c8c8_n

theorem at_8001c8c8_8001c8cc (X : Cx) (hX : X.Ok) :
    AtStep X 0x8001c8c8#64 (r1 X) [] 0x8001e22c#64 (r1 X) [] := by
  at_seg Lua.Vm.Arms.seg_8001c8c8_8001c8cc

theorem at_8001e22c_8001e240_t (X : Cx) (hX : X.Ok) (hg_5 : ((Loc.den X (.lit ((Loc.den X (.tag .a 0)) &&& (Loc.den X (.lit 0xf#64))))) == (Loc.den X (.lit 0x4#64))) = true) :
    AtStep X 0x8001e22c#64 (r1 X) [] 0x8001e244#64 (r2 X) m0 := by
  at_seg Lua.Vm.Arms.seg_8001e22c_8001e240_t

theorem at_8001e244_8001e250_t (X : Cx) (hX : X.Ok) (hs_b0 : X.ins.b + 0 < X.p.maxstacksize) (hg_3 : ((Loc.den X (.lit ((Loc.den X (.tag .b 0)) &&& (Loc.den X (.lit 0xf#64))))) == (Loc.den X (.lit ((Loc.den X (.tag .a 0)) &&& (Loc.den X (.lit 0xf#64)))))) = true) :
    AtStep X 0x8001e244#64 (r2 X) m0 0x8001e254#64 (r3 X) m0 := by
  at_seg Lua.Vm.Arms.seg_8001e244_8001e250_t

theorem at_8001e254_8001e260 (X : Cx) (hX : X.Ok) (hs_a0 : X.ins.a + 0 < X.p.maxstacksize) (hs_b0 : X.ins.b + 0 < X.p.maxstacksize) :
    AtStep X 0x8001e254#64 (r3 X) m0 0x8001a704#64 (r4 X) m0 := by
  at_seg Lua.Vm.Arms.seg_8001e254_8001e260

theorem call_8001e260 (X : Cx) (hX : X.Ok) (hs_a0 : X.ins.a + 0 < X.p.maxstacksize) (hs_b0 : X.ins.b + 0 < X.p.maxstacksize) (x y : List UInt8) (hsa : X.s.regs (X.ins.a + 0) = some (.str x)) (hsb : X.s.regs (X.ins.b + 0) = some (.str y)) :
    AtStep X 0x8001a704#64 (r4 X) m0 0x8001c8f8#64 (r5 X) m1 := by
  at_open
  at_lstr Lua.Vm.Arms.seg_8001e260_8001e268 Lua.Vm.Sim.At.obs_lt

theorem at_8001c8f8_8001c900 (X : Cx) (hX : X.Ok) :
    AtStep X 0x8001c8f8#64 (r5 X) m1 0x8001c900#64 (r6 X) m1 := by
  at_seg Lua.Vm.Arms.seg_8001c8f8_8001c900

theorem at_8001c900_8001c90c_t (X : Cx) (hX : X.Ok) (hg_3 : ((Loc.den X (.lit (if X.ins.k then 1#64 else 0#64))) != (Loc.den X (.lit (if lexLt (sOf X .a) (sOf X .b) then 1#64 else 0#64)))) = true) :
    AtStep X 0x8001c900#64 (r6 X) m1 0x8001c910#64 (r7 X) m1 := by
  at_seg Lua.Vm.Arms.seg_8001c900_8001c90c_t

theorem at_8001c910_8001c918 (X : Cx) (hX : X.Ok) :
    AtStep X 0x8001c910#64 (r7 X) m1 0x8001bfe4#64 (r8 X) m1 := by
  at_seg Lua.Vm.Arms.seg_8001c910_8001c918

theorem fin (X : Cx) (hX : X.Ok) {c : Config}
    (h : At X 0x8001bfe4#64 (r8 X) m1 c) :
    AtFin X m1 [] (X.s.pc + 2) c := by
  at_fin

theorem at_8001c900_8001c90c_n (X : Cx) (hX : X.Ok) (hg_3 : ((Loc.den X (.lit (if X.ins.k then 1#64 else 0#64))) != (Loc.den X (.lit (if lexLt (sOf X .a) (sOf X .b) then 1#64 else 0#64)))) = false) :
    AtStep X 0x8001c900#64 (r6 X) m1 0x8001c90c#64 (r7 X) m1 := by
  at_seg Lua.Vm.Arms.seg_8001c900_8001c90c_n

theorem at_8001c90c_8001c910 (X : Cx) (hX : X.Ok) :
    AtStep X 0x8001c90c#64 (r7 X) m1 0x8001eaf4#64 (headRow X) m1 := by
  at_seg Lua.Vm.Arms.seg_8001c90c_8001c910

theorem at_8001eaf4_8001eb1c (X : Cx) (hX : X.Ok) (hj : (nextJump X.p X.s.pc).isSome = true) :
    AtStep X 0x8001eaf4#64 (headRow X) m1 0x8001bfe4#64 (r9 X) m1 := by
  have := jmp_lt hj
  at_seg Lua.Vm.Arms.seg_8001eaf4_8001eb1c

theorem fin_1 (X : Cx) (hX : X.Ok) {c : Config}
    (h : At X 0x8001bfe4#64 (r9 X) m1 c) :
    AtFin X m1 [] (jmpPc X) c := by
  at_fin

end Lua.Vm.At.LT
