import Lua.Vm.Sim.Kit.AtFn
import Lua.Vm.Arms.Segs.Hmemmove

/-! GENERATED by scripts/gen_lua_at.py -- do not edit.

The at-lemmas of `memmove` (`0x8003b444`) over the callee
context (`Lua/Vm/Sim/Kit/AtFn.lean`): its generated segments between rows,
each proved in its own declaration. `memmove(dst, src, n)` on disjoint ranges (the backward copy `0x8003b450` is a stop).

Roots (a fresh context each):

* `0x8003b444` from `r0`
* `0x8003b48c` from `r10`
* `0x8003b4c8` from `r13`
* `0x8003b52c` from `r25`

Ends:

* loop 0x8003b48c: `r2`, memory `X.m`
* loop 0x8003b4c8: `r5`, memory `X.m`
* return: `r7`, memory `X.m`
* loop 0x8003b48c: `r11`, memory `(m0 X)`
* return: `r12`, memory `(m0 X)`
* loop 0x8003b4c8: `r15`, memory `(m4 X)`
* return: `r7`, memory `(m4 X)`
* loop 0x8003b48c: `r19`, memory `(m4 X)`
* loop 0x8003b52c: `r21`, memory `(m4 X)`
* loop 0x8003b52c: `r27`, memory `(m5 X)`
* return: `r12`, memory `(m5 X)`
* loop 0x8003b48c: `r31`, memory `(m5 X)`

Paths not followed:

* `seg_8003b448_8003b450_n`: stop 0x8003b450
-/

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail ConcurrencyInterfaceV1 Vsa
open Vsa.Sim Vsa.Logic
open Lua.Vm.Sim Lua.Vm.Sim.AtF Lua.Vm.Layout
open Vsa.Machine (Config)

namespace Lua.Vm.AtF.Memmove

/-- The context's facts at the root `Ok` stands for. -/
structure Ok (X : FCx) : Prop where
  d_lo : 0x8005c6d0 ≤ X.n 1
  s_lo : 0x80000000 ≤ X.n 2
  sp_hi : X.n 0 ≤ 2 ^ 32
  ra : (X.b 0).toNat % 4 = 0
  disj : X.n 1 + X.n 3 ≤ X.n 2 ∨ X.n 2 + X.n 3 ≤ X.n 1
  d_hi : X.n 1 + X.n 3 ≤ 2 ^ 32
  s_hi : X.n 2 + X.n 3 ≤ 2 ^ 32
  s_th : X.n 2 + X.n 3 ≤ 0x8005c6c0 ∨ 0x8005c6c8 ≤ X.n 2

/-- The context's facts at the root `Ok_B` stands for. -/
structure Ok_B (X : FCx) : Prop where
  d_lo : 0x8005c6d0 ≤ X.n 1
  s_lo : 0x80000000 ≤ X.n 2
  sp_hi : X.n 0 ≤ 2 ^ 32
  ra : (X.b 0).toNat % 4 = 0
  disj : X.n 1 + X.n 3 ≤ X.n 2 ∨ X.n 2 + X.n 3 ≤ X.n 1
  d_hi : X.n 1 + X.n 3 ≤ 2 ^ 32
  s_hi : X.n 2 + X.n 3 ≤ 2 ^ 32
  s_th : X.n 2 + X.n 3 ≤ 0x8005c6c0 ∨ 0x8005c6c8 ≤ X.n 2
  i_lt : X.n 4 < X.n 3

/-- The context's facts at the root `Ok_W32` stands for. -/
structure Ok_W32 (X : FCx) : Prop where
  d_lo : 0x8005c6d0 ≤ X.n 1
  s_lo : 0x80000000 ≤ X.n 2
  sp_hi : X.n 0 ≤ 2 ^ 32
  ra : (X.b 0).toNat % 4 = 0
  disj : X.n 1 + X.n 3 ≤ X.n 2 ∨ X.n 2 + X.n 3 ≤ X.n 1
  d_hi : X.n 1 + X.n 3 ≤ 2 ^ 32
  s_hi : X.n 2 + X.n 3 ≤ 2 ^ 32
  s_th : X.n 2 + X.n 3 ≤ 0x8005c6c0 ∨ 0x8005c6c8 ≤ X.n 2
  j_lt : X.n 4 < X.n 5
  q_le : 32 * X.n 5 ≤ X.n 3
  d_al : X.n 1 % 8 = 0
  s_al : X.n 2 % 8 = 0

/-- The context's facts at the root `Ok_W8` stands for. -/
structure Ok_W8 (X : FCx) : Prop where
  d_lo : 0x8005c6d0 ≤ X.n 1
  s_lo : 0x80000000 ≤ X.n 2
  sp_hi : X.n 0 ≤ 2 ^ 32
  ra : (X.b 0).toNat % 4 = 0
  disj : X.n 1 + 8 * X.n 3 ≤ X.n 2 ∨ X.n 2 + 8 * X.n 3 ≤ X.n 1
  d_hi : X.n 1 + 8 * X.n 3 ≤ 2 ^ 32
  s_hi : X.n 2 + 8 * X.n 3 ≤ 2 ^ 32
  s_th : X.n 2 + 8 * X.n 3 ≤ 0x8005c6c0 ∨ 0x8005c6c8 ≤ X.n 2
  i_lt : X.n 4 < X.n 3
  d_al : X.n 1 % 8 = 0
  s_al : X.n 2 % 8 = 0

@[at_row] abbrev m0 (X : FCx) : Mem :=
  (X.m).insert (X.n 1 + X.n 4) (stData 1 (zero_extend (m := 64) (bytesT1 X.m (X.n 2 + X.n 4) : BitVec (8 * 1))))

@[at_row] abbrev m1 (X : FCx) : Mem :=
  writeMap8 (X.m) (X.n 1 + 32 * X.n 4) (sdData_val (bytesT8 X.m (X.n 2 + 32 * X.n 4)))

@[at_row] abbrev m2 (X : FCx) : Mem :=
  writeMap8 (writeMap8 (X.m) (X.n 1 + 32 * X.n 4) (sdData_val (bytesT8 X.m (X.n 2 + 32 * X.n 4)))) (X.n 1 + 32 * X.n 4 + 8) (sdData_val (bytesT8 X.m (X.n 2 + 32 * X.n 4 + 8)))

@[at_row] abbrev m3 (X : FCx) : Mem :=
  writeMap8 (writeMap8 (writeMap8 (X.m) (X.n 1 + 32 * X.n 4) (sdData_val (bytesT8 X.m (X.n 2 + 32 * X.n 4)))) (X.n 1 + 32 * X.n 4 + 8) (sdData_val (bytesT8 X.m (X.n 2 + 32 * X.n 4 + 8)))) (X.n 1 + 32 * X.n 4 + 16) (sdData_val (bytesT8 X.m (X.n 2 + 32 * X.n 4 + 16)))

@[at_row] abbrev m4 (X : FCx) : Mem :=
  writeMap8 (writeMap8 (writeMap8 (writeMap8 (X.m) (X.n 1 + 32 * X.n 4) (sdData_val (bytesT8 X.m (X.n 2 + 32 * X.n 4)))) (X.n 1 + 32 * X.n 4 + 8) (sdData_val (bytesT8 X.m (X.n 2 + 32 * X.n 4 + 8)))) (X.n 1 + 32 * X.n 4 + 16) (sdData_val (bytesT8 X.m (X.n 2 + 32 * X.n 4 + 16)))) (X.n 1 + 32 * X.n 4 + 24) (sdData_val (bytesT8 X.m (X.n 2 + 32 * X.n 4 + 24)))

@[at_row] abbrev m5 (X : FCx) : Mem :=
  writeMap8 (X.m) (X.n 1 + 8 * X.n 4) (sdData_val (bytesT8 X.m (X.n 2 + 8 * X.n 4)))

@[at_row] abbrev r0 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2)⟩,
   ⟨Register.x12, BitVec.ofNat 64 (X.n 3)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

@[at_row] abbrev r1 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2)⟩,
   ⟨Register.x12, BitVec.ofNat 64 (X.n 3)⟩,
   ⟨Register.x13, BitVec.ofNat 64 (X.n 3 + 18446744073709551615)⟩,
   ⟨Register.x15, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

@[at_row] abbrev r2 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2)⟩,
   ⟨Register.x13, BitVec.ofNat 64 (X.n 1 + X.n 3)⟩,
   ⟨Register.x15, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

@[at_row] abbrev r3 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2)⟩,
   ⟨Register.x12, BitVec.ofNat 64 (X.n 3)⟩,
   ⟨Register.x15, (((BitVec.ofNat 64 (X.n 1)) ||| (BitVec.ofNat 64 (X.n 2))) &&& sign_extend (m := 64) (0x007#12))⟩,
   ⟨Register.x17, BitVec.ofNat 64 (X.n 2)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

@[at_row] abbrev r4 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2)⟩,
   ⟨Register.x12, BitVec.ofNat 64 (X.n 3)⟩,
   ⟨Register.x15, 0x1f#64⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

@[at_row] abbrev r5 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2)⟩,
   ⟨Register.x12, BitVec.ofNat 64 (X.n 3)⟩,
   ⟨Register.x14, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x15, ((shift_bits_right (BitVec.ofNat 64 (X.n 3)) (Sail.BitVec.extractLsb (0x05#6) 5 0)) + sign_extend (m := 64) (0xfff#12))⟩,
   ⟨Register.x16, ((BitVec.ofNat 64 (X.n 1)) + (shift_bits_left (shift_bits_right (BitVec.ofNat 64 (X.n 3)) (Sail.BitVec.extractLsb (0x05#6) 5 0)) (Sail.BitVec.extractLsb (0x05#6) 5 0)))⟩,
   ⟨Register.x17, BitVec.ofNat 64 (X.n 2)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

@[at_row] abbrev r6 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x12, BitVec.ofNat 64 (X.n 3)⟩,
   ⟨Register.x13, BitVec.ofNat 64 (X.n 3 + 18446744073709551615)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

@[at_row] abbrev r7 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

@[at_row] abbrev r8 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2)⟩,
   ⟨Register.x12, BitVec.ofNat 64 (X.n 3)⟩,
   ⟨Register.x15, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

@[at_row] abbrev r9 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2)⟩,
   ⟨Register.x12, BitVec.ofNat 64 (X.n 3)⟩,
   ⟨Register.x15, BitVec.ofNat 64 (X.n 2 + X.n 3)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

@[at_row] abbrev r10 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, X.b 13⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2 + X.n 4)⟩,
   ⟨Register.x13, BitVec.ofNat 64 (X.n 1 + X.n 3)⟩,
   ⟨Register.x15, BitVec.ofNat 64 (X.n 1 + X.n 4)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

@[at_row] abbrev r11 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, X.b 13⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2 + X.n 4 + 1)⟩,
   ⟨Register.x13, BitVec.ofNat 64 (X.n 1 + X.n 3)⟩,
   ⟨Register.x14, zero_extend (m := 64) (bytesT1 X.m (X.n 2 + X.n 4) : BitVec (8 * 1))⟩,
   ⟨Register.x15, BitVec.ofNat 64 (X.n 1 + X.n 4 + 1)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

@[at_row] abbrev r12 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, X.b 13⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

@[at_row] abbrev r13 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2 + 32 * X.n 4)⟩,
   ⟨Register.x12, BitVec.ofNat 64 (X.n 3)⟩,
   ⟨Register.x14, BitVec.ofNat 64 (X.n 1 + 32 * X.n 4)⟩,
   ⟨Register.x15, BitVec.ofNat 64 (X.n 5 + 18446744073709551615)⟩,
   ⟨Register.x16, BitVec.ofNat 64 (X.n 1 + 32 * X.n 5)⟩,
   ⟨Register.x17, BitVec.ofNat 64 (X.n 2)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

@[at_row] abbrev r14 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2 + 32 * X.n 4 + 32)⟩,
   ⟨Register.x12, BitVec.ofNat 64 (X.n 3)⟩,
   ⟨Register.x13, bytesT8 X.m (X.n 2 + 32 * X.n 4 + 16)⟩,
   ⟨Register.x14, BitVec.ofNat 64 (X.n 1 + 32 * X.n 4 + 32)⟩,
   ⟨Register.x15, BitVec.ofNat 64 (X.n 5 - 1)⟩,
   ⟨Register.x16, BitVec.ofNat 64 (X.n 1 + 32 * X.n 5)⟩,
   ⟨Register.x17, BitVec.ofNat 64 (X.n 2)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

@[at_row] abbrev r15 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2 + 32 * X.n 4 + 32)⟩,
   ⟨Register.x12, BitVec.ofNat 64 (X.n 3)⟩,
   ⟨Register.x13, bytesT8 X.m (X.n 2 + 32 * X.n 4 + 24)⟩,
   ⟨Register.x14, BitVec.ofNat 64 (X.n 1 + 32 * X.n 4 + 32)⟩,
   ⟨Register.x15, BitVec.ofNat 64 (X.n 5 - 1)⟩,
   ⟨Register.x16, BitVec.ofNat 64 (X.n 1 + 32 * X.n 5)⟩,
   ⟨Register.x17, BitVec.ofNat 64 (X.n 2)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

@[at_row] abbrev r16 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x12, ((BitVec.ofNat 64 (X.n 3)) &&& sign_extend (m := 64) (0x01f#12))⟩,
   ⟨Register.x13, ((((BitVec.ofNat 64 (X.n 3)) &&& sign_extend (m := 64) (0x01f#12))) + sign_extend (m := 64) (0xfff#12))⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

@[at_row] abbrev r17 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2 + 32 * X.n 5)⟩,
   ⟨Register.x12, ((BitVec.ofNat 64 (X.n 3)) &&& sign_extend (m := 64) (0x01f#12))⟩,
   ⟨Register.x13, ((BitVec.ofNat 64 (X.n 3)) &&& sign_extend (m := 64) (0x01f#12))⟩,
   ⟨Register.x15, BitVec.ofNat 64 (X.n 1 + 32 * X.n 5)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

@[at_row] abbrev r18 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2 + 32 * X.n 5)⟩,
   ⟨Register.x12, ((BitVec.ofNat 64 (X.n 3)) &&& sign_extend (m := 64) (0x01f#12))⟩,
   ⟨Register.x13, ((((BitVec.ofNat 64 (X.n 3)) &&& sign_extend (m := 64) (0x01f#12))) + sign_extend (m := 64) (0xfff#12))⟩,
   ⟨Register.x15, BitVec.ofNat 64 (X.n 1 + 32 * X.n 5)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

@[at_row] abbrev r19 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2 + 32 * X.n 5)⟩,
   ⟨Register.x13, ((BitVec.ofNat 64 (X.n 1 + 32 * X.n 5)) + ((((((BitVec.ofNat 64 (X.n 3)) &&& sign_extend (m := 64) (0x01f#12))) + sign_extend (m := 64) (0xfff#12))) + sign_extend (m := 64) (0x001#12)))⟩,
   ⟨Register.x15, BitVec.ofNat 64 (X.n 1 + 32 * X.n 5)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

@[at_row] abbrev r20 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2 + 32 * X.n 5)⟩,
   ⟨Register.x12, BitVec.ofNat 64 (X.n 3)⟩,
   ⟨Register.x13, ((BitVec.ofNat 64 (X.n 3)) &&& sign_extend (m := 64) (0x01f#12))⟩,
   ⟨Register.x14, BitVec.ofNat 64 (X.n 2 + 32 * X.n 5 - 32)⟩,
   ⟨Register.x15, BitVec.ofNat 64 (X.n 1 + 32 * X.n 5)⟩,
   ⟨Register.x16, ((BitVec.ofNat 64 (X.n 3)) &&& sign_extend (m := 64) (0x018#12))⟩,
   ⟨Register.x17, BitVec.ofNat 64 (X.n 2)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩,
   ⟨Register.x28, BitVec.ofNat 64 (X.n 2 + 32 * X.n 5)⟩]

@[at_row] abbrev r21 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2 + 32 * X.n 5)⟩,
   ⟨Register.x12, BitVec.ofNat 64 (X.n 3)⟩,
   ⟨Register.x13, (((((BitVec.ofNat 64 (X.n 3)) &&& sign_extend (m := 64) (0x01f#12))) + sign_extend (m := 64) (0xff8#12)) &&& sign_extend (m := 64) (0xff8#12))⟩,
   ⟨Register.x14, (((BitVec.ofNat 64 (X.n 2 + 32 * X.n 5 - 32)) + (((((BitVec.ofNat 64 (X.n 3)) &&& sign_extend (m := 64) (0x01f#12))) + sign_extend (m := 64) (0xff8#12)) &&& sign_extend (m := 64) (0xff8#12))) + sign_extend (m := 64) (0x028#12))⟩,
   ⟨Register.x15, BitVec.ofNat 64 (X.n 1 + 32 * X.n 5)⟩,
   ⟨Register.x16, BitVec.ofNat 64 (X.n 1 + (18446744073709551616 - X.n 2))⟩,
   ⟨Register.x17, BitVec.ofNat 64 (X.n 2)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩,
   ⟨Register.x28, BitVec.ofNat 64 (X.n 2 + 32 * X.n 5)⟩]

@[at_row] abbrev r22 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2 + 32 * X.n 4 + 32)⟩,
   ⟨Register.x12, BitVec.ofNat 64 (X.n 3)⟩,
   ⟨Register.x13, bytesT8 X.m (X.n 2 + 32 * X.n 4 + 8)⟩,
   ⟨Register.x14, BitVec.ofNat 64 (X.n 1 + 32 * X.n 4 + 32)⟩,
   ⟨Register.x15, BitVec.ofNat 64 (X.n 5 - 1)⟩,
   ⟨Register.x16, BitVec.ofNat 64 (X.n 1 + 32 * X.n 5)⟩,
   ⟨Register.x17, BitVec.ofNat 64 (X.n 2)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

@[at_row] abbrev r23 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2 + 32 * X.n 4 + 32)⟩,
   ⟨Register.x12, BitVec.ofNat 64 (X.n 3)⟩,
   ⟨Register.x13, bytesT8 X.m (X.n 2 + 32 * X.n 4)⟩,
   ⟨Register.x14, BitVec.ofNat 64 (X.n 1 + 32 * X.n 4 + 32)⟩,
   ⟨Register.x15, BitVec.ofNat 64 (X.n 5 - 1)⟩,
   ⟨Register.x16, BitVec.ofNat 64 (X.n 1 + 32 * X.n 5)⟩,
   ⟨Register.x17, BitVec.ofNat 64 (X.n 2)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

@[at_row] abbrev r24 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2 + 32 * X.n 4)⟩,
   ⟨Register.x12, BitVec.ofNat 64 (X.n 3)⟩,
   ⟨Register.x14, BitVec.ofNat 64 (X.n 1 + 32 * X.n 4)⟩,
   ⟨Register.x15, BitVec.ofNat 64 (X.n 5 - 1)⟩,
   ⟨Register.x16, BitVec.ofNat 64 (X.n 1 + 32 * X.n 5)⟩,
   ⟨Register.x17, BitVec.ofNat 64 (X.n 2)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

@[at_row] abbrev r25 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, X.b 13⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2 + 8 * X.n 4)⟩,
   ⟨Register.x12, BitVec.ofNat 64 (X.n 5)⟩,
   ⟨Register.x13, BitVec.ofNat 64 (8 * X.n 3 + 18446744073709551608)⟩,
   ⟨Register.x14, BitVec.ofNat 64 (X.n 2 + 8 * X.n 3)⟩,
   ⟨Register.x15, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x16, BitVec.ofNat 64 (X.n 1 + (18446744073709551616 - X.n 2))⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩,
   ⟨Register.x28, BitVec.ofNat 64 (X.n 2)⟩]

@[at_row] abbrev r26 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, X.b 13⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2 + 8 * X.n 4)⟩,
   ⟨Register.x12, BitVec.ofNat 64 (X.n 5)⟩,
   ⟨Register.x13, BitVec.ofNat 64 (8 * X.n 3 - 8)⟩,
   ⟨Register.x14, BitVec.ofNat 64 (X.n 2 + 8 * X.n 3)⟩,
   ⟨Register.x15, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x16, BitVec.ofNat 64 (X.n 1 + (18446744073709551616 - X.n 2))⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩,
   ⟨Register.x28, BitVec.ofNat 64 (X.n 2)⟩]

@[at_row] abbrev r27 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x6, bytesT8 X.m (X.n 2 + 8 * X.n 4)⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, X.b 13⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2 + 8 * X.n 4 + 8)⟩,
   ⟨Register.x12, BitVec.ofNat 64 (X.n 5)⟩,
   ⟨Register.x13, BitVec.ofNat 64 (8 * X.n 3 - 8)⟩,
   ⟨Register.x14, BitVec.ofNat 64 (X.n 2 + 8 * X.n 3)⟩,
   ⟨Register.x15, BitVec.ofNat 64 (X.n 1)⟩,
   ⟨Register.x16, BitVec.ofNat 64 (X.n 1 + (18446744073709551616 - X.n 2))⟩,
   ⟨Register.x17, BitVec.ofNat 64 (X.n 1 + 8 * X.n 4)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩,
   ⟨Register.x28, BitVec.ofNat 64 (X.n 2)⟩]

@[at_row] abbrev r28 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, X.b 13⟩,
   ⟨Register.x12, ((BitVec.ofNat 64 (X.n 5)) &&& sign_extend (m := 64) (0x007#12))⟩,
   ⟨Register.x13, ((((BitVec.ofNat 64 (X.n 5)) &&& sign_extend (m := 64) (0x007#12))) + sign_extend (m := 64) (0xfff#12))⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

@[at_row] abbrev r29 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, X.b 13⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2 + 8 * X.n 3)⟩,
   ⟨Register.x12, ((BitVec.ofNat 64 (X.n 5)) &&& sign_extend (m := 64) (0x007#12))⟩,
   ⟨Register.x13, BitVec.ofNat 64 (8 * X.n 3 - 8)⟩,
   ⟨Register.x14, BitVec.ofNat 64 (8 * X.n 3)⟩,
   ⟨Register.x15, BitVec.ofNat 64 (X.n 1 + 8 * X.n 3)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩,
   ⟨Register.x28, BitVec.ofNat 64 (X.n 2)⟩]

@[at_row] abbrev r30 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, X.b 13⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2 + 8 * X.n 3)⟩,
   ⟨Register.x12, ((BitVec.ofNat 64 (X.n 5)) &&& sign_extend (m := 64) (0x007#12))⟩,
   ⟨Register.x13, ((((BitVec.ofNat 64 (X.n 5)) &&& sign_extend (m := 64) (0x007#12))) + sign_extend (m := 64) (0xfff#12))⟩,
   ⟨Register.x15, BitVec.ofNat 64 (X.n 1 + 8 * X.n 3)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

@[at_row] abbrev r31 (X : FCx) : List Pin :=
  [⟨Register.x1, X.b 0⟩,
   ⟨Register.x2, BitVec.ofNat 64 (X.n 0)⟩,
   ⟨Register.x3, 0x8005ced0#64⟩,
   ⟨Register.x8, X.b 1⟩,
   ⟨Register.x9, X.b 2⟩,
   ⟨Register.x10, X.b 13⟩,
   ⟨Register.x11, BitVec.ofNat 64 (X.n 2 + 8 * X.n 3)⟩,
   ⟨Register.x13, ((BitVec.ofNat 64 (X.n 1 + 8 * X.n 3)) + ((((((BitVec.ofNat 64 (X.n 5)) &&& sign_extend (m := 64) (0x007#12))) + sign_extend (m := 64) (0xfff#12))) + sign_extend (m := 64) (0x001#12)))⟩,
   ⟨Register.x15, BitVec.ofNat 64 (X.n 1 + 8 * X.n 3)⟩,
   ⟨Register.x18, X.b 3⟩,
   ⟨Register.x19, X.b 4⟩,
   ⟨Register.x20, X.b 5⟩,
   ⟨Register.x21, X.b 6⟩,
   ⟨Register.x22, X.b 7⟩,
   ⟨Register.x23, X.b 8⟩,
   ⟨Register.x24, X.b 9⟩,
   ⟨Register.x25, X.b 10⟩,
   ⟨Register.x26, X.b 11⟩,
   ⟨Register.x27, X.b 12⟩]

theorem at_8003b484_8003b48c (X : FCx) (hX : Ok X) (hf0 : (X.n 1) ≤ (X.n 2)) (hf1 : 31 < (X.n 3)) :
    Triple (SegSt 0x8003b484#64 (r1 X) (ArmPay X.m X.o))
      (SegSt (0x8003b48c#64) (r2 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b484_8003b48c
  fat_close

theorem at_8003b554_8003b560 (X : FCx) (hX : Ok X) (hf0 : (X.n 1) ≤ (X.n 2)) (hf1 : 31 < (X.n 3)) :
    Triple (SegSt 0x8003b554#64 (r3 X) (ArmPay X.m X.o))
      (SegSt (0x8003b484#64) (r1 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b554_8003b560
  fat_close

theorem at_8003b4a4_8003b4b4_t (X : FCx) (hX : Ok X) (hf0 : (X.n 1) ≤ (X.n 2)) (hf1 : 31 < (X.n 3)) (hg_4 : ((((BitVec.ofNat 64 (X.n 1)) ||| (BitVec.ofNat 64 (X.n 2))) &&& sign_extend (m := 64) (0x007#12)) != (0#64)) = true) :
    Triple (SegSt 0x8003b4a4#64 (r4 X) (ArmPay X.m X.o))
      (SegSt (0x8003b554#64) (r3 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b4a4_8003b4b4_t
  fat_close

theorem at_8003b4b4_8003b4c8 (X : FCx) (hX : Ok X) (hf0 : (X.n 1) ≤ (X.n 2)) (hf1 : 31 < (X.n 3)) :
    Triple (SegSt 0x8003b4b4#64 (r3 X) (ArmPay X.m X.o))
      (SegSt (0x8003b4c8#64) (r5 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b4b4_8003b4c8
  fat_close

theorem at_8003b4a4_8003b4b4_n (X : FCx) (hX : Ok X) (hf0 : (X.n 1) ≤ (X.n 2)) (hf1 : 31 < (X.n 3)) (hg_4 : ((((BitVec.ofNat 64 (X.n 1)) ||| (BitVec.ofNat 64 (X.n 2))) &&& sign_extend (m := 64) (0x007#12)) != (0#64)) = false) :
    Triple (SegSt 0x8003b4a4#64 (r4 X) (ArmPay X.m X.o))
      (SegSt (0x8003b4b4#64) (r3 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b4a4_8003b4b4_n
  fat_close

theorem at_8003b470_8003b478_t (X : FCx) (hX : Ok X) (hf0 : (X.n 1) ≤ (X.n 2)) (hg_2 : zopz0zI_u (0x1f#64) (BitVec.ofNat 64 (X.n 3)) = true) :
    Triple (SegSt 0x8003b470#64 (r0 X) (ArmPay X.m X.o))
      (SegSt (0x8003b4a4#64) (r4 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b470_8003b478_t
  fat_close

theorem at_8003b560_8003b564 (X : FCx) (hX : Ok X) (hf0 : (X.n 1) ≤ (X.n 2)) (hf2 : (X.n 3) ≤ 31) (hf3 : (X.n 3) = 0) :
    Triple (SegSt 0x8003b560#64 (r6 X) (ArmPay X.m X.o))
      (SegSt (X.b 0) (r7 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b560_8003b564
  fat_close

theorem at_8003b47c_8003b484_t (X : FCx) (hX : Ok X) (hf0 : (X.n 1) ≤ (X.n 2)) (hf2 : (X.n 3) ≤ 31) (hg_2 : (BitVec.ofNat 64 (X.n 3) == 0x0#64) = true) :
    Triple (SegSt 0x8003b47c#64 (r8 X) (ArmPay X.m X.o))
      (SegSt (0x8003b560#64) (r6 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b47c_8003b484_t
  fat_close

theorem at_8003b484_8003b48c_1 (X : FCx) (hX : Ok X) (hf0 : (X.n 1) ≤ (X.n 2)) (hf2 : (X.n 3) ≤ 31) (hf4 : (X.n 3) ≠ 0) :
    Triple (SegSt 0x8003b484#64 (r1 X) (ArmPay X.m X.o))
      (SegSt (0x8003b48c#64) (r2 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b484_8003b48c
  fat_close

theorem at_8003b47c_8003b484_n (X : FCx) (hX : Ok X) (hf0 : (X.n 1) ≤ (X.n 2)) (hf2 : (X.n 3) ≤ 31) (hg_2 : (BitVec.ofNat 64 (X.n 3) == 0x0#64) = false) :
    Triple (SegSt 0x8003b47c#64 (r8 X) (ArmPay X.m X.o))
      (SegSt (0x8003b484#64) (r1 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b47c_8003b484_n
  fat_close

theorem at_8003b478_8003b47c (X : FCx) (hX : Ok X) (hf0 : (X.n 1) ≤ (X.n 2)) (hf2 : (X.n 3) ≤ 31) :
    Triple (SegSt 0x8003b478#64 (r4 X) (ArmPay X.m X.o))
      (SegSt (0x8003b47c#64) (r8 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b478_8003b47c
  fat_close

theorem at_8003b470_8003b478_n (X : FCx) (hX : Ok X) (hf0 : (X.n 1) ≤ (X.n 2)) (hg_2 : zopz0zI_u (0x1f#64) (BitVec.ofNat 64 (X.n 3)) = false) :
    Triple (SegSt 0x8003b470#64 (r0 X) (ArmPay X.m X.o))
      (SegSt (0x8003b478#64) (r4 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b470_8003b478_n
  fat_close

theorem at_8003b444_8003b448_t (X : FCx) (hX : Ok X) (hg_1 : zopz0zKzJ_u (BitVec.ofNat 64 (X.n 2)) (BitVec.ofNat 64 (X.n 1)) = true) :
    Triple (SegSt 0x8003b444#64 (r0 X) (ArmPay X.m X.o))
      (SegSt (0x8003b470#64) (r0 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b444_8003b448_t
  fat_close

theorem at_8003b484_8003b48c_2 (X : FCx) (hX : Ok X) (hf5 : (X.n 2) < (X.n 1)) (hf6 : (X.n 2 + X.n 3) ≤ (X.n 1)) (hf1 : 31 < (X.n 3)) :
    Triple (SegSt 0x8003b484#64 (r1 X) (ArmPay X.m X.o))
      (SegSt (0x8003b48c#64) (r2 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b484_8003b48c
  fat_close

theorem at_8003b554_8003b560_1 (X : FCx) (hX : Ok X) (hf5 : (X.n 2) < (X.n 1)) (hf6 : (X.n 2 + X.n 3) ≤ (X.n 1)) (hf1 : 31 < (X.n 3)) :
    Triple (SegSt 0x8003b554#64 (r3 X) (ArmPay X.m X.o))
      (SegSt (0x8003b484#64) (r1 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b554_8003b560
  fat_close

theorem at_8003b4a4_8003b4b4_t_1 (X : FCx) (hX : Ok X) (hf5 : (X.n 2) < (X.n 1)) (hf6 : (X.n 2 + X.n 3) ≤ (X.n 1)) (hf1 : 31 < (X.n 3)) (hg_4 : ((((BitVec.ofNat 64 (X.n 1)) ||| (BitVec.ofNat 64 (X.n 2))) &&& sign_extend (m := 64) (0x007#12)) != (0#64)) = true) :
    Triple (SegSt 0x8003b4a4#64 (r4 X) (ArmPay X.m X.o))
      (SegSt (0x8003b554#64) (r3 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b4a4_8003b4b4_t
  fat_close

theorem at_8003b4b4_8003b4c8_1 (X : FCx) (hX : Ok X) (hf5 : (X.n 2) < (X.n 1)) (hf6 : (X.n 2 + X.n 3) ≤ (X.n 1)) (hf1 : 31 < (X.n 3)) :
    Triple (SegSt 0x8003b4b4#64 (r3 X) (ArmPay X.m X.o))
      (SegSt (0x8003b4c8#64) (r5 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b4b4_8003b4c8
  fat_close

theorem at_8003b4a4_8003b4b4_n_1 (X : FCx) (hX : Ok X) (hf5 : (X.n 2) < (X.n 1)) (hf6 : (X.n 2 + X.n 3) ≤ (X.n 1)) (hf1 : 31 < (X.n 3)) (hg_4 : ((((BitVec.ofNat 64 (X.n 1)) ||| (BitVec.ofNat 64 (X.n 2))) &&& sign_extend (m := 64) (0x007#12)) != (0#64)) = false) :
    Triple (SegSt 0x8003b4a4#64 (r4 X) (ArmPay X.m X.o))
      (SegSt (0x8003b4b4#64) (r3 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b4a4_8003b4b4_n
  fat_close

theorem at_8003b470_8003b478_t_1 (X : FCx) (hX : Ok X) (hf5 : (X.n 2) < (X.n 1)) (hf6 : (X.n 2 + X.n 3) ≤ (X.n 1)) (hg_2 : zopz0zI_u (0x1f#64) (BitVec.ofNat 64 (X.n 3)) = true) :
    Triple (SegSt 0x8003b470#64 (r9 X) (ArmPay X.m X.o))
      (SegSt (0x8003b4a4#64) (r4 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b470_8003b478_t
  fat_close

theorem at_8003b560_8003b564_1 (X : FCx) (hX : Ok X) (hf5 : (X.n 2) < (X.n 1)) (hf6 : (X.n 2 + X.n 3) ≤ (X.n 1)) (hf2 : (X.n 3) ≤ 31) (hf3 : (X.n 3) = 0) :
    Triple (SegSt 0x8003b560#64 (r6 X) (ArmPay X.m X.o))
      (SegSt (X.b 0) (r7 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b560_8003b564
  fat_close

theorem at_8003b47c_8003b484_t_1 (X : FCx) (hX : Ok X) (hf5 : (X.n 2) < (X.n 1)) (hf6 : (X.n 2 + X.n 3) ≤ (X.n 1)) (hf2 : (X.n 3) ≤ 31) (hg_2 : (BitVec.ofNat 64 (X.n 3) == 0x0#64) = true) :
    Triple (SegSt 0x8003b47c#64 (r8 X) (ArmPay X.m X.o))
      (SegSt (0x8003b560#64) (r6 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b47c_8003b484_t
  fat_close

theorem at_8003b484_8003b48c_3 (X : FCx) (hX : Ok X) (hf5 : (X.n 2) < (X.n 1)) (hf6 : (X.n 2 + X.n 3) ≤ (X.n 1)) (hf2 : (X.n 3) ≤ 31) (hf4 : (X.n 3) ≠ 0) :
    Triple (SegSt 0x8003b484#64 (r1 X) (ArmPay X.m X.o))
      (SegSt (0x8003b48c#64) (r2 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b484_8003b48c
  fat_close

theorem at_8003b47c_8003b484_n_1 (X : FCx) (hX : Ok X) (hf5 : (X.n 2) < (X.n 1)) (hf6 : (X.n 2 + X.n 3) ≤ (X.n 1)) (hf2 : (X.n 3) ≤ 31) (hg_2 : (BitVec.ofNat 64 (X.n 3) == 0x0#64) = false) :
    Triple (SegSt 0x8003b47c#64 (r8 X) (ArmPay X.m X.o))
      (SegSt (0x8003b484#64) (r1 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b47c_8003b484_n
  fat_close

theorem at_8003b478_8003b47c_1 (X : FCx) (hX : Ok X) (hf5 : (X.n 2) < (X.n 1)) (hf6 : (X.n 2 + X.n 3) ≤ (X.n 1)) (hf2 : (X.n 3) ≤ 31) :
    Triple (SegSt 0x8003b478#64 (r4 X) (ArmPay X.m X.o))
      (SegSt (0x8003b47c#64) (r8 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b478_8003b47c
  fat_close

theorem at_8003b470_8003b478_n_1 (X : FCx) (hX : Ok X) (hf5 : (X.n 2) < (X.n 1)) (hf6 : (X.n 2 + X.n 3) ≤ (X.n 1)) (hg_2 : zopz0zI_u (0x1f#64) (BitVec.ofNat 64 (X.n 3)) = false) :
    Triple (SegSt 0x8003b470#64 (r9 X) (ArmPay X.m X.o))
      (SegSt (0x8003b478#64) (r4 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b470_8003b478_n
  fat_close

theorem at_8003b448_8003b450_t (X : FCx) (hX : Ok X) (hf5 : (X.n 2) < (X.n 1)) (hg_2 : zopz0zKzJ_u (BitVec.ofNat 64 (X.n 1)) (BitVec.ofNat 64 (X.n 2 + X.n 3)) = true) :
    Triple (SegSt 0x8003b448#64 (r0 X) (ArmPay X.m X.o))
      (SegSt (0x8003b470#64) (r9 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b448_8003b450_t
  fat_close

theorem at_8003b444_8003b448_n (X : FCx) (hX : Ok X) (hg_1 : zopz0zKzJ_u (BitVec.ofNat 64 (X.n 2)) (BitVec.ofNat 64 (X.n 1)) = false) :
    Triple (SegSt 0x8003b444#64 (r0 X) (ArmPay X.m X.o))
      (SegSt (0x8003b448#64) (r0 X) (ArmPay X.m X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b444_8003b448_n
  fat_close

theorem at_8003b48c_8003b4a0_t (X : FCx) (hX : Ok_B X) (hg_5 : (BitVec.ofNat 64 (X.n 1 + X.n 4 + 1) != BitVec.ofNat 64 (X.n 1 + X.n 3)) = true) :
    Triple (SegSt 0x8003b48c#64 (r10 X) (ArmPay X.m X.o))
      (SegSt (0x8003b48c#64) (r11 X) (ArmPay (m0 X) X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th, hx_i_lt⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b48c_8003b4a0_t
  fat_close

theorem at_8003b4a0_8003b4a4 (X : FCx) (hX : Ok_B X) (hf7 : (X.n 1 + X.n 4 + 1) = (X.n 1 + X.n 3)) :
    Triple (SegSt 0x8003b4a0#64 (r11 X) (ArmPay (m0 X) X.o))
      (SegSt (X.b 0) (r12 X) (ArmPay (m0 X) X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th, hx_i_lt⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b4a0_8003b4a4
  fat_close

theorem at_8003b48c_8003b4a0_n (X : FCx) (hX : Ok_B X) (hg_5 : (BitVec.ofNat 64 (X.n 1 + X.n 4 + 1) != BitVec.ofNat 64 (X.n 1 + X.n 3)) = false) :
    Triple (SegSt 0x8003b48c#64 (r10 X) (ArmPay X.m X.o))
      (SegSt (0x8003b4a0#64) (r11 X) (ArmPay (m0 X) X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th, hx_i_lt⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b48c_8003b4a0_n
  fat_close

theorem at_8003b4e8_8003b4f4_t (X : FCx) (hX : Ok_W32 X) (hg_3 : (BitVec.ofNat 64 (X.n 1 + 32 * X.n 4 + 32) != BitVec.ofNat 64 (X.n 1 + 32 * X.n 5)) = true) :
    Triple (SegSt 0x8003b4e8#64 (r14 X) (ArmPay (m3 X) X.o))
      (SegSt (0x8003b4c8#64) (r15 X) (ArmPay (m4 X) X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th, hx_j_lt, hx_q_le, hx_d_al, hx_s_al⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b4e8_8003b4f4_t
  fat_close

theorem at_8003b560_8003b564_2 (X : FCx) (hX : Ok_W32 X) (hf8 : (X.n 1 + 32 * X.n 4 + 32) = (X.n 1 + 32 * X.n 5)) :
    Triple (SegSt 0x8003b560#64 (r16 X) (ArmPay (m4 X) X.o))
      (SegSt (X.b 0) (r7 X) (ArmPay (m4 X) X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th, hx_j_lt, hx_q_le, hx_d_al, hx_s_al⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b560_8003b564
  fat_close

theorem at_8003b47c_8003b484_t_2 (X : FCx) (hX : Ok_W32 X) (hf8 : (X.n 1 + 32 * X.n 4 + 32) = (X.n 1 + 32 * X.n 5)) (hg_2 : (((BitVec.ofNat 64 (X.n 3)) &&& sign_extend (m := 64) (0x01f#12)) == 0x0#64) = true) :
    Triple (SegSt 0x8003b47c#64 (r17 X) (ArmPay (m4 X) X.o))
      (SegSt (0x8003b560#64) (r16 X) (ArmPay (m4 X) X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th, hx_j_lt, hx_q_le, hx_d_al, hx_s_al⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b47c_8003b484_t
  fat_close

theorem at_8003b484_8003b48c_4 (X : FCx) (hX : Ok_W32 X) (hf8 : (X.n 1 + 32 * X.n 4 + 32) = (X.n 1 + 32 * X.n 5)) :
    Triple (SegSt 0x8003b484#64 (r18 X) (ArmPay (m4 X) X.o))
      (SegSt (0x8003b48c#64) (r19 X) (ArmPay (m4 X) X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th, hx_j_lt, hx_q_le, hx_d_al, hx_s_al⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b484_8003b48c
  fat_close

theorem at_8003b47c_8003b484_n_2 (X : FCx) (hX : Ok_W32 X) (hf8 : (X.n 1 + 32 * X.n 4 + 32) = (X.n 1 + 32 * X.n 5)) (hg_2 : (((BitVec.ofNat 64 (X.n 3)) &&& sign_extend (m := 64) (0x01f#12)) == 0x0#64) = false) :
    Triple (SegSt 0x8003b47c#64 (r17 X) (ArmPay (m4 X) X.o))
      (SegSt (0x8003b484#64) (r18 X) (ArmPay (m4 X) X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th, hx_j_lt, hx_q_le, hx_d_al, hx_s_al⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b47c_8003b484_n
  fat_close

theorem at_8003b564_8003b56c (X : FCx) (hX : Ok_W32 X) (hf8 : (X.n 1 + 32 * X.n 4 + 32) = (X.n 1 + 32 * X.n 5)) :
    Triple (SegSt 0x8003b564#64 (r20 X) (ArmPay (m4 X) X.o))
      (SegSt (0x8003b47c#64) (r17 X) (ArmPay (m4 X) X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th, hx_j_lt, hx_q_le, hx_d_al, hx_s_al⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b564_8003b56c
  fat_close

theorem at_8003b4f4_8003b518_t (X : FCx) (hX : Ok_W32 X) (hf8 : (X.n 1 + 32 * X.n 4 + 32) = (X.n 1 + 32 * X.n 5)) (hg_9 : (((BitVec.ofNat 64 (X.n 3)) &&& sign_extend (m := 64) (0x018#12)) == (0#64)) = true) :
    Triple (SegSt 0x8003b4f4#64 (r15 X) (ArmPay (m4 X) X.o))
      (SegSt (0x8003b564#64) (r20 X) (ArmPay (m4 X) X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th, hx_j_lt, hx_q_le, hx_d_al, hx_s_al⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b4f4_8003b518_t
  fat_close

theorem at_8003b518_8003b52c (X : FCx) (hX : Ok_W32 X) (hf8 : (X.n 1 + 32 * X.n 4 + 32) = (X.n 1 + 32 * X.n 5)) :
    Triple (SegSt 0x8003b518#64 (r20 X) (ArmPay (m4 X) X.o))
      (SegSt (0x8003b52c#64) (r21 X) (ArmPay (m4 X) X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th, hx_j_lt, hx_q_le, hx_d_al, hx_s_al⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b518_8003b52c
  fat_close

theorem at_8003b4f4_8003b518_n (X : FCx) (hX : Ok_W32 X) (hf8 : (X.n 1 + 32 * X.n 4 + 32) = (X.n 1 + 32 * X.n 5)) (hg_9 : (((BitVec.ofNat 64 (X.n 3)) &&& sign_extend (m := 64) (0x018#12)) == (0#64)) = false) :
    Triple (SegSt 0x8003b4f4#64 (r15 X) (ArmPay (m4 X) X.o))
      (SegSt (0x8003b518#64) (r20 X) (ArmPay (m4 X) X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th, hx_j_lt, hx_q_le, hx_d_al, hx_s_al⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b4f4_8003b518_n
  fat_close

theorem at_8003b4e8_8003b4f4_n (X : FCx) (hX : Ok_W32 X) (hg_3 : (BitVec.ofNat 64 (X.n 1 + 32 * X.n 4 + 32) != BitVec.ofNat 64 (X.n 1 + 32 * X.n 5)) = false) :
    Triple (SegSt 0x8003b4e8#64 (r14 X) (ArmPay (m3 X) X.o))
      (SegSt (0x8003b4f4#64) (r15 X) (ArmPay (m4 X) X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th, hx_j_lt, hx_q_le, hx_d_al, hx_s_al⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b4e8_8003b4f4_n
  fat_close

theorem at_8003b4e0_8003b4e8 (X : FCx) (hX : Ok_W32 X) :
    Triple (SegSt 0x8003b4e0#64 (r22 X) (ArmPay (m2 X) X.o))
      (SegSt (0x8003b4e8#64) (r14 X) (ArmPay (m3 X) X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th, hx_j_lt, hx_q_le, hx_d_al, hx_s_al⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b4e0_8003b4e8
  fat_close

theorem at_8003b4d8_8003b4e0 (X : FCx) (hX : Ok_W32 X) :
    Triple (SegSt 0x8003b4d8#64 (r23 X) (ArmPay (m1 X) X.o))
      (SegSt (0x8003b4e0#64) (r22 X) (ArmPay (m2 X) X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th, hx_j_lt, hx_q_le, hx_d_al, hx_s_al⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b4d8_8003b4e0
  fat_close

theorem at_8003b4c8_8003b4d8 (X : FCx) (hX : Ok_W32 X) :
    Triple (SegSt 0x8003b4c8#64 (r24 X) (ArmPay X.m X.o))
      (SegSt (0x8003b4d8#64) (r23 X) (ArmPay (m1 X) X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th, hx_j_lt, hx_q_le, hx_d_al, hx_s_al⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b4c8_8003b4d8
  fat_close

theorem at_8003b52c_8003b540_t (X : FCx) (hX : Ok_W8 X) (hg_5 : (BitVec.ofNat 64 (X.n 2 + 8 * X.n 4 + 8) != BitVec.ofNat 64 (X.n 2 + 8 * X.n 3)) = true) :
    Triple (SegSt 0x8003b52c#64 (r26 X) (ArmPay X.m X.o))
      (SegSt (0x8003b52c#64) (r27 X) (ArmPay (m5 X) X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th, hx_i_lt, hx_d_al, hx_s_al⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b52c_8003b540_t
  fat_close

theorem at_8003b560_8003b564_3 (X : FCx) (hX : Ok_W8 X) (hf9 : (X.n 2 + 8 * X.n 4 + 8) = (X.n 2 + 8 * X.n 3)) :
    Triple (SegSt 0x8003b560#64 (r28 X) (ArmPay (m5 X) X.o))
      (SegSt (X.b 0) (r12 X) (ArmPay (m5 X) X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th, hx_i_lt, hx_d_al, hx_s_al⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b560_8003b564
  fat_close

theorem at_8003b47c_8003b484_t_3 (X : FCx) (hX : Ok_W8 X) (hf9 : (X.n 2 + 8 * X.n 4 + 8) = (X.n 2 + 8 * X.n 3)) (hg_2 : (((BitVec.ofNat 64 (X.n 5)) &&& sign_extend (m := 64) (0x007#12)) == 0x0#64) = true) :
    Triple (SegSt 0x8003b47c#64 (r29 X) (ArmPay (m5 X) X.o))
      (SegSt (0x8003b560#64) (r28 X) (ArmPay (m5 X) X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th, hx_i_lt, hx_d_al, hx_s_al⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b47c_8003b484_t
  fat_close

theorem at_8003b484_8003b48c_5 (X : FCx) (hX : Ok_W8 X) (hf9 : (X.n 2 + 8 * X.n 4 + 8) = (X.n 2 + 8 * X.n 3)) :
    Triple (SegSt 0x8003b484#64 (r30 X) (ArmPay (m5 X) X.o))
      (SegSt (0x8003b48c#64) (r31 X) (ArmPay (m5 X) X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th, hx_i_lt, hx_d_al, hx_s_al⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b484_8003b48c
  fat_close

theorem at_8003b47c_8003b484_n_3 (X : FCx) (hX : Ok_W8 X) (hf9 : (X.n 2 + 8 * X.n 4 + 8) = (X.n 2 + 8 * X.n 3)) (hg_2 : (((BitVec.ofNat 64 (X.n 5)) &&& sign_extend (m := 64) (0x007#12)) == 0x0#64) = false) :
    Triple (SegSt 0x8003b47c#64 (r29 X) (ArmPay (m5 X) X.o))
      (SegSt (0x8003b484#64) (r30 X) (ArmPay (m5 X) X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th, hx_i_lt, hx_d_al, hx_s_al⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b47c_8003b484_n
  fat_close

theorem at_8003b540_8003b554 (X : FCx) (hX : Ok_W8 X) (hf9 : (X.n 2 + 8 * X.n 4 + 8) = (X.n 2 + 8 * X.n 3)) :
    Triple (SegSt 0x8003b540#64 (r27 X) (ArmPay (m5 X) X.o))
      (SegSt (0x8003b47c#64) (r29 X) (ArmPay (m5 X) X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th, hx_i_lt, hx_d_al, hx_s_al⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b540_8003b554
  fat_close

theorem at_8003b52c_8003b540_n (X : FCx) (hX : Ok_W8 X) (hg_5 : (BitVec.ofNat 64 (X.n 2 + 8 * X.n 4 + 8) != BitVec.ofNat 64 (X.n 2 + 8 * X.n 3)) = false) :
    Triple (SegSt 0x8003b52c#64 (r26 X) (ArmPay X.m X.o))
      (SegSt (0x8003b540#64) (r27 X) (ArmPay (m5 X) X.o)) := by
  intro c h
  obtain ⟨hx_d_lo, hx_s_lo, hx_sp_hi, hx_ra, hx_disj, hx_d_hi, hx_s_hi, hx_s_th, hx_i_lt, hx_d_al, hx_s_al⟩ := hX
  have hTH : tohostAddr = 0x8005c6c0 := rfl
  fat_seg Lua.Vm.Arms.seg_8003b52c_8003b540_n
  fat_close

end Lua.Vm.AtF.Memmove
