#!/usr/bin/env python3
"""Emit the site batteries and SegSt segment theorems of every F1 arm of
luaV_execute.

The arms and their segments are scripts/draft_f1_arms.py's (reach from the
jump-table target up to the fetch head, cut at branch targets and after
every control transfer), with one more cut: after every `jal`, so that a
segment ends at a call and the callee is composed at the arm level. A
segment that ends in a conditional branch is emitted once per polarity
(`_t` taken, `_n` not taken).

For each segment scripts/syi/disasm_to_segment.py's `complete` builds a
gen_segment.py spec with `"boundary": "segst"` and no hole: the pre/post
states are `SegSt` over the read-before-written registers and the memory
`m0`, and the address side conditions, branch guards and `jr` alignments
are named hypotheses `h*_<step>` of the theorem. The instructions are
proved by gen_sites.py site lemmas (loads through the TOTAL classes),
decoded by `Vsa.Sim.decodeW`, fetched from `.text` through the generated
code pins (`Lua.Vm.Code.luaV_execute_at_<addr>`), with `.text` carried
across stores by `Lua.Vm.Arms.TextLoaded.{writeMap8,writeMap4,insert}`.

Output (GENERATED, check.sh stage 1 checks drift):
    Lua/Vm/Arms/Sites/S<nn>.lean   site batteries (unique addresses)
    Lua/Vm/Arms/Segs/G<nn>.lean    segment theorems `seg_<lo>_<hi>[_t|_n]`
    Lua/Vm/Arms.lean               index
    Lua/Vm/Arms/arms.tsv           arm -> its segment theorems

    python3 scripts/gen_lua_arms.py [--check] [--only OP_MOVE,OP_JMP]
"""
import argparse
import csv
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
sys.path.insert(0, str(ROOT / "scripts/syi"))
import draft_f1_arms as dfa          # noqa: E402
import disasm_to_sites as d2s        # noqa: E402
import disasm_to_segment as d2seg    # noqa: E402
import gen_sites                     # noqa: E402
import gen_segment                   # noqa: E402

OUT = ROOT / "Lua/Vm/Arms"
NS = "Lua.Vm.Arms"
PRED = "Lua.Vm.Arms.TextLoaded"
TEMPLATE = ("Lua.Vm.Code.luaV_execute_at_{addr} "
            "(Lua.Vm.Code.textLoaded_LuaV_execute_p{part}Loaded hmem)")
CODE_IMPORTS = ["Lua.Vm.Code.FixedImage_LuaV_execute", "Lua.Vm.Arms.Text"]
SURVIVAL = {"sd": "Lua.Vm.Arms.TextLoaded.writeMap8 $prev _ {hwin}",
            "sw": "Lua.Vm.Arms.TextLoaded.writeMap4 $prev _ {hwin}",
            "sh": "Lua.Vm.Arms.TextLoaded.writeMap2 $prev _ {hwin}",
            "sb": "Lua.Vm.Arms.TextLoaded.insert $prev _ {hwin}"}
JT = json.load(open(dfa.ARMS_JSON))["summary"]["jump_table"]
# The arms with an A1 simulation proof (Lua/Vm/Sim/Arms, scripts/gen_lua_arm.py).
# Their segments carry the registers `luaV_execute` holds at the fetch head
# (`KEEP`: sp, gp, s0 = L, s1 = 81, s2 = 3, s3 = pc + 1, s4 = the instruction,
# s5 = trap, s7 = ci, s8 = the jump table, s9 = base, s11 = pc) and the console
# output, the frame `Lua.Vm.Sim.VmRel` needs; the other arms' segments do not
# pay for it until their simulation lands.
SIM_OPS = {"OP_MOVE", "OP_LOADI", "OP_JMP", "OP_ADD", "OP_EQI", "OP_FORLOOP", "OP_SUB",
           "OP_ADDI", "OP_ADDK", "OP_SUBK",
           "OP_BAND", "OP_BOR", "OP_BXOR", "OP_LTI", "OP_GTI", "OP_LEI", "OP_GEI",
           "OP_LOADTRUE", "OP_LOADFALSE", "OP_LFALSESKIP", "OP_LOADK", "OP_BNOT",
           "OP_NOT", "OP_TEST", "OP_TESTSET",
           # round-3 bake-off (KIT): the held-out arms
           "OP_MUL", "OP_MOD", "OP_EQ",
           # kit lane 1: the arithmetic and bitwise family
           "OP_MULK", "OP_MODK", "OP_IDIV", "OP_IDIVK", "OP_UNM", "OP_SHL", "OP_SHR",
           "OP_SHLI", "OP_SHRI", "OP_BANDK", "OP_BORK", "OP_BXORK"}
# lane KIT-2: the control and compare family
SIM_OPS |= {"OP_FORPREP", "OP_LOADNIL", "OP_EQK", "OP_LT", "OP_LE"}
# lane F1-3: `OP_VARARGPREP` at the entry (`luaT_adjustvarargs` a summarised call)
SIM_OPS |= {"OP_VARARGPREP"}
# Arms with a kernel outside the census summary's F1 list (the strings slice
# of `Lua/Fragment.lean`: `LEN` on a string). Their segments and sites are
# emitted in modules of their own (`Segs/X<op>`, `Sites/SX<op>`), so the
# address-chunked modules of the F1 arms stay as they are.
EXTRA_ARMS = ["OP_LEN"]
SIM_OPS |= set(EXTRA_ARMS)
KEEP = [2, 3, 8, 9, 18, 19, 20, 21, 23, 24, 25, 27]
# The register invariant a `sim` segment threads (every GPR present, the HTIF
# mailbox idle: `VmRel`'s `Core.ok`), one step lemma per step class.
OK = {"pred": "Lua.Vm.RegsOk", "ns": "Lua.Vm.RegsOk"}
OK_IMPORT = "Lua.Vm.Arms.RegsOk"
SITES_PER_MODULE = 40
SEGS_PER_MODULE = 12
HEADER = "GENERATED by scripts/gen_lua_arms.py -- do not edit."


# The helpers the held-out arms call (M5 call nodes), as `[lo, hi)` code
# ranges: their segments are cut like an arm's (branch targets, after every
# control transfer and `jal`) and carry the caller's fetch-head registers
# (`KEEP`), the caller's temporaries live across the call (`s6` = `R[A]`,
# `s10`; `t0`, `__moddi3`'s return address across `__udivdi3`) and, by a
# liveness fixpoint over all helper segments, every register a later segment
# reads, so a helper summary composes with the arm's segments by pin lookup.
# (name, code-pin name, lo, hi, caller temporaries, extra roots, stops): the
# extra roots are computed-jump targets (`luaV_equalobj`'s `ttypetag` jump
# table: nil/booleans, then integer, short string and light C function); the
# stops are where a path leaves the F1 values (number variants that differ,
# a long string's `luaS_eqlngstr`).
SUMMARISED = {"__muldi3", "__moddi3", "luaV_equalobj", "__divdi3"}
# lane KIT-2: FORPREP's `forlimit` (`luaV_tointeger` on an integer limit) and
# its count division
SUMMARISED |= {"luaV_tointeger", "__hidden___udivdi3"}
HELPERS = [("__muldi3", "__muldi3", 0x8002f6c8, 0x8002f6ec, [22, 26], [], []),
           ("__hidden___udivdi3", "__hidden___udivdi3", 0x8002f734, 0x8002f77c, [5, 22, 26],
            [], []),
           ("__moddi3", "__moddi3", 0x8002f7b0, 0x8002f7e0, [22, 26], [], []),
           ("luaV_equalobj", "LuaV_equalobj", 0x8001b780, 0x8001bad0, [],
            [0x8001b84c, 0x8001b7f4, 0x8001b8f8], [0x8001b810]),
           # `__divdi3` (`0x8002f72c`): its sign tests, then either falls through
           # into `__hidden___udivdi3` (`0x8002f734`, its own helper) or branches
           # into the sign fix-ups that objdump labels `__umoddi3+0x10`/`+0x20`
           # (a second range, pinned as `__umoddi3`)
           ("__divdi3", "__divdi3", 0x8002f72c, 0x8002f734, [22, 26], [], []),
           ("__umoddi3", "__umoddi3", 0x8002f78c, 0x8002f7b0, [22, 26], [0x8002f79c], [])]
# lane KIT-2: `luaV_tointeger` on a non-string, non-float value (the string
# and float paths `0x8001ae4c`, `0x8001ae98` are stops: F1's limits are
# integers, `forprepK`)
HELPERS += [("luaV_tointeger", "LuaV_tointeger", 0x8001ade8, 0x8001af50, [22, 26], [],
             [0x8001ae4c, 0x8001ae98])]
# axis S (S-SCAN): the string callees. `luaV_equalobj`'s long-string arm
# (`0x8001b8f8`, now a root of its jump table) tail-calls `luaS_eqlngstr` ->
# `memcmp`; `OP_LT`/`OP_LE` on two strings call `l_strcmp` -> `strcoll`
# (`j strcmp`) and `strlen`.
SUMMARISED |= {"l_strcmp"}
HELPERS += [("luaS_eqlngstr", "LuaS_eqlngstr", 0x80017184, 0x800171d4, [], [], []),
            ("memcmp", "Memcmp", 0x80036198, 0x80036204, [], [], []),
            ("l_strcmp", "L_strcmp", 0x8001a704, 0x8001a7e0, [], [], []),
            ("strcoll", "Strcoll", 0x80036374, 0x80036378, [], [], []),
            ("strcmp", "Strcmp", 0x8003b920, 0x8003ba4c, [], [], []),
            ("strlen", "Strlen", 0x8003b770, 0x8003b844, [], [], [])]
# lane F1-3: `luaT_adjustvarargs(L, 0, ci, p)` at the entry: no fixed
# parameters (the copy loop `0x80019858` is a stop: `A = 0`, `blez` taken) and
# room on the stack (the `luaD_growstack` call `0x800198bc` is a stop)
SUMMARISED |= {"luaT_adjustvarargs"}
HELPERS += [("luaT_adjustvarargs", "LuaT_adjustvarargs", 0x800197f0, 0x800198f0, [], [],
             [0x80019858, 0x800198bc])]
# lane F1-2: `OP_LEN`'s `luaV_objlen` on a string (variants 4 and 20); the table
# path (`luaH_getn`, `0x8001bb78`) and the metamethod path (`0x8001bb14`) are
# stops: `δ .len` has no other F1 value
HELPERS += [("luaV_objlen", "LuaV_objlen", 0x8001bae0, 0x8001bc28, [], [], [0x8001bb14, 0x8001bb78])]
SUMMARISED |= {"luaV_objlen"}
# lane F1-4: the `OP_RETURN*` family (`FinalSim`: the return out of
# `luaV_execute`, `CIST_FRESH`), its callees with nothing open
# (`luaF_close`: `L->openupval = NULL`, the `bnez` to `0x8000c11c` a stop;
# `L->tbclist < base`, the `bltu` not taken at `0x8000c264` a stop) and
# `luaD_poscall` with no hooks and `wanted = 0` (`0x8000a3bc`, `0x8000a4d8`
# stops), and the C return chain after `luaV_execute`'s `ret`: `ccall`'s tail,
# `luaD_rawrunprotected`'s, `luaD_pcall`'s and `lua_pcallk`'s (status 0),
# `main`'s, `_start`'s `j exit`, `exit` (`__call_exitprocs` with `__atexit =
# NULL`, the `0x8003bb3c` loop a stop; no `__stdio_exit_handler`, its `jalr` a
# stop), and `_exit` up to its `tohost` store
SIM_OPS |= {"OP_RETURN", "OP_RETURN0", "OP_RETURN1"}
SUMMARISED |= {"luaF_close", "luaF_closeupval", "luaD_poscall"}
HELPERS += [("luaF_close", "LuaF_close", 0x8000c224, 0x8000c380, [22, 26], [], [0x8000c264]),
            ("luaF_closeupval", "LuaF_closeupval", 0x8000c114, 0x8000c224, [22, 26], [],
             [0x8000c11c]),
            ("luaD_poscall", "LuaD_poscall", 0x8000a39c, 0x8000a5e8, [22, 26], [],
             [0x8000a3bc, 0x8000a4d8]),
            ("luaD_callnoyield", "LuaD_callnoyield", 0x8000b0bc, 0x8000b0e0, [22, 26], [], []),
            ("luaD_rawrunprotected", "LuaD_rawrunprotected", 0x80009c38, 0x80009c60, [22, 26],
             [], []),
            ("luaD_pcall", "LuaD_pcall", 0x8000b4c0, 0x8000b4f0, [22, 26], [], []),
            ("lua_pcallk", "Lua_pcallk", 0x8000413c, 0x80004154, [22, 26], [], []),
            ("main", "Main", 0x80001808, 0x80001820, [22, 26], [], []),
            ("_start", "_start", 0x80000038, 0x8000003c, [22, 26], [], []),
            ("exit", "Exit", 0x8002f85c, 0x8002f888, [22, 26], [], [0x8002f87c]),
            ("__call_exitprocs", "__call_exitprocs", 0x8003bb00, 0x8003bc70, [22, 26], [],
             [0x8003bb3c]),
            ("__retarget_lock_acquire_recursive", "__retarget_lock_acquire_recursive",
             0x8003b428, 0x8003b42c, [22, 26], [], []),
            ("__retarget_lock_release_recursive", "__retarget_lock_release_recursive",
             0x8003b440, 0x8003b444, [22, 26], [], []),
            ("_exit", "_exit", 0x8000063c, 0x8000064c, [22, 26], [], [])]
# helper modules whose `H<name>` would collide (`exit`, `_exit`)
HMOD = {"_exit": "HUexit"}
# lane F1-6: htif.c's `_write` on a console descriptor (`getfd`, the
# `htif_putc` loop). The `tohost` store `0x80000d3c` is MMIO, not a memory
# store: it is a stop, and the loop resumes at the root `0x80000d40` after the
# console step (`Kit/Console.lean`). The lazy `fs_init` (`0x80000b04`: on
# `print`'s path `__smakebuf_r`'s `_fstat` ran it first), the file path
# (`0x80000b5c`, `kind == FD_FILE`) and the `EBADF` exit (`0x80000d58`) are
# stops: a console descriptor of an initialised table reaches none of them.
HELPERS += [("_write", "_write", 0x80000ae8, 0x80000d80, [22, 26], [0x80000d40],
             [0x80000b04, 0x80000d3c, 0x80000b5c, 0x80000d58])]
# lane F1-6: newlib's write path above it: `__swrite` (the `FILE`'s write
# hook: clear `__SOFF`, tail-call `_write_r`; the `__SAPP` seek `0x80034f68` is a
# stop: stdout is not opened for append) and `_write_r` (`errno = 0`, `_write`;
# the `-1` path `0x8003b3f0` is a stop: the console write returns `n`).
HELPERS += [("__swrite", "__swrite", 0x80034f18, 0x80034fa0, [22, 26], [], [0x80034f68]),
            ("_write_r", "_write_r", 0x8003b3b0, 0x8003b40c, [22, 26], [], [0x8003b3f0])]
# lane F1-6: `__sflush_r` on a write stream (`__SWR`): `_p := _bf._base`,
# `_w := 0` (line-buffered) and the write loop through the `FILE`'s hook (`jalr
# a5`, `0x80032890`; its return `0x80032894` is a root). The read path
# (`0x8003271c`) and the short-write error exit (`0x8003289c`) are stops: the
# console hook writes everything (`swrite_sum`).
HELPERS += [("__sflush_r", "__sflush_r", 0x800326f8, 0x80032954, [22, 26], [0x80032894],
             [0x8003271c, 0x8003289c])]
# lane F1-7: `OP_GETTABUP _ENV "print"`'s `luaH_getshortstr` (the chain walk;
# the `absentkey` return `0x800180ec` is a stop: the walk finds `print`,
# `EnvMem.found`), and the arm itself on the route (its segments in their
# chunked modules, with the fetch-head registers)
HELPERS += [("luaH_getshortstr", "LuaH_getshortstr", 0x8001808c, 0x800180f8, [22, 26], [],
             [0x800180ec])]
SUMMARISED |= {"luaH_getshortstr"}
SIM_OPS |= {"OP_GETTABUP"}
# lane F1-8: `print`'s stdio calls on the callee-context route
# (`scripts/gen_lua_at.py --fn`): `fflush(stdout)` (the `__sinit` call
# `0x80032a98` and the `fflush(NULL)` walk `0x80032ae4` are stops: `stdout` is
# set up, `StdioUp`)
HELPERS += [("fflush", "Fflush", 0x80032a1c, 0x80032af8, [22, 26], [],
             [0x80032a98, 0x80032ae4])]
# lane F1-8: `memmove` (`__sfvwrite_r` copying into the `stdout` buffer): every
# path but the backward copy (`0x8003b450`, a stop: the buffer and the source
# are disjoint, so `dst < src + n` with `src < dst` is infeasible); the
# 32-byte block body is cut after each of its stores (roots `0x8003b4d8`, …):
# a segment's post-state holds every load through the segment's earlier
# stores, so four stores in one segment state their data exponentially
HELPERS += [("memmove", "Memmove", 0x8003b444, 0x8003b56c, [22, 26],
             [0x8003b4d8, 0x8003b4e0, 0x8003b4e8], [0x8003b450])]
# lane F1-8: `_fflush_r(ptr, stdout)` (`__sfvwrite_r`'s flushes; the `__sinit`
# call `0x80032a04` is a stop: `StdioUp`)
HELPERS += [("_fflush_r", "_fflush_r", 0x80032954, 0x80032a1c, [22, 26], [], [0x80032a04])]
# `tohost` seams: a stop that is a console store (`sd rs2, imm(rs1)` to
# `tohost`, run by `Kit/Console.lean`'s step) and the registers it reads; the
# liveness flows through it to the root after it.
TOHOST_SEAMS = {0x80000d3c: {"x12", "x15"}}
# the registers a helper returns (live at its `ret`)
RESULTS = {"luaS_eqlngstr": {"x10"}, "memcmp": {"x10"}, "l_strcmp": {"x10"},
           "strcoll": {"x10"}, "strcmp": {"x10"}, "strlen": {"x10"},"__muldi3": {"x10"}, "__hidden___udivdi3": {"x10", "x11"}, "__moddi3": {"x10"},
           "__divdi3": {"x10"}, "__umoddi3": {"x10"},
           "luaV_equalobj": {"x10"}, "luaV_tointeger": {"x10"}, "luaT_adjustvarargs": set(), "luaV_objlen": set(),
           "luaF_close": set(), "luaF_closeupval": set(), "luaD_poscall": set(),
           "luaD_callnoyield": set(), "luaD_rawrunprotected": {"x10"}, "luaD_pcall": {"x10"},
           "lua_pcallk": {"x10"}, "main": {"x10"}, "_start": set(), "exit": set(),
           "__call_exitprocs": set(), "__retarget_lock_acquire_recursive": set(),
           "__retarget_lock_release_recursive": set(), "_exit": set(),
           "_write": {"x10"}, "__swrite": {"x10"}, "_write_r": {"x10"},
           "__sflush_r": {"x10"}, "luaH_getshortstr": {"x10"}, "fflush": {"x10"}, "memmove": {"x10"}, "_fflush_r": {"x10"}}


def helper_cfg(lo, hi):
    """{addr: (row, successors, ends_segment)} over one helper's range."""
    out = {}
    for addr, word, raw in d2s.disassemble(d2s.DEFAULT_OBJDUMP, d2s.DEFAULT_ELF, lo, hi):
        row = d2s.classify(addr, word, raw, {addr: "taken"})[-1]
        c, o, nxt = row.cls, row.ops, addr + 4
        if c is None:
            raise SystemExit(f"unsupported instruction at 0x{addr:x}: {raw}")
        if c.startswith("branch_"):
            tgt = (addr + d2s.sext(int(o[3], 16), 13)) % 2**64
            succ, end = [x for x in (tgt, nxt) if lo <= x < hi], True
        elif c == "j":
            tgt = (addr + d2s.sext(int(o[0], 16), 21)) % 2**64
            succ, end = ([tgt] if lo <= tgt < hi else []), True
        elif c in ("jr", "jalr"):
            succ, end = [], True
        else:
            succ, end = [nxt], False
        out[addr] = (raw, succ, end)
    return out


def helper_segments(lo, hi, roots=(), stops=()):
    """The helper's code reachable from `lo` and the `roots` (not through the
    `stops`), cut into segments (each root a leader)."""
    g = helper_cfg(lo, hi)
    reach, work = set(), [lo, *roots]
    while work:
        a = work.pop()
        if a in reach or a not in g or a in stops:
            continue
        reach.add(a)
        work.extend(g[a][1])
    segs = []
    for a, b in dfa.segments(g, reach, lo):
        cuts = [x for x in roots if a < x < b]
        for x in cuts:
            segs.append((a, x))
            a = x
        segs.append((a, b))
    return g, split_at_calls(g, segs)


def d2s_last_is_ret(hi):
    """Whether the instruction before `hi` is a `ret` (or `jr t0`, the soft-int
helpers' return through the saved `ra`)."""
    raw = next(iter(d2s.disassemble(d2s.DEFAULT_OBJDUMP, d2s.DEFAULT_ELF, hi - 4, hi)))[2]
    return raw.split()[0] == "ret" or raw.split()[:2] == ["jr", "t0"]


def helper_live(cuts, owner):
    """Per helper segment, the registers a later helper segment reads that
    it neither reads nor writes (liveness fixpoint over the pool of helper
    segments; a `jal`'s successor is its callee's entry)."""
    info = {}
    for n, (lo, hi, path, keep) in cuts.items():
        spec, _ = seg_spec(lo, hi, path, n, True, keep=keep)
        em = gen_segment.SegmentEmitter(spec)
        em.emit()
        m = re.match(r"\(?(0x[0-9a-f]+)#64", em.end_pc)
        end = int(m.group(1), 16) if m else None     # a return: no static successor
        info[n] = ({p["reg"] for p in spec["pins"]}, {r for r, _ in em.pins}, end)
    live = {n: set(info[n][0]) for n in cuts}

    roots = {fn: rs for fn, _, _, _, _, rs, _ in HELPERS}

    def live_out(n):
        if info[n][2] is None:
            hi = cuts[n][1]
            if d2s_last_is_ret(hi):     # a return: the helper's results
                return RESULTS[owner[n]]
            # a computed jump (a jump table): its targets are the helper's roots
            return set().union(*[live[m] for m in cuts
                                 if owner[m] == owner[n] and cuts[m][0] in roots[owner[n]]])
        end = info[n][2]
        if end in TOHOST_SEAMS:     # the console store, then the code after it
            return TOHOST_SEAMS[end] | set().union(*[live[m] for m in cuts if cuts[m][0] == end + 4])
        return set().union(*[live[m] for m in cuts if cuts[m][0] == end])
    changed = True
    while changed:
        changed = False
        for n in cuts:
            new = info[n][0] | (live_out(n) - info[n][1])
            if not new <= live[n]:
                live[n] |= new
                changed = True
    return {n: live_out(n) - info[n][1] for n in cuts}


def helper_all():
    """[(module, battery, segment module)] for every helper."""
    cuts, owner = {}, {}
    for fn, cap, lo, hi, temps, roots, stops in HELPERS:
        g, segs = helper_segments(lo, hi, roots, stops)
        for a, b in segs:
            for suf, path in variants(g, a, b):
                name = f"seg_{a:08x}_{b:08x}{suf}"
                cuts[name] = (a, b, path, KEEP + temps)
                owner[name] = fn
    extra = helper_live(cuts, owner)
    out = []
    for fn, cap, lo, hi, temps, roots, stops in HELPERS:
        specs, sites = [], {}
        for name, (a, b, path, keep) in cuts.items():
            if owner[name] != fn:
                continue
            keep = sorted(set(keep) | {int(r[1:]) for r in extra[name]})
            spec, rows = seg_spec(a, b, path, name, True, keep=keep)
            specs.append((name, spec))
            for row in rows:
                p = row.split("\t")
                sites.setdefault((int(p[0], 16), p[2]), row)
        out.append(helper_emit(fn, cap, lo, hi, specs, sites))
    return out


def helper_emit(fn, cap, lo, hi, specs, sites):
    """The site battery and segment module of one helper."""
    objs = []
    for n, key in enumerate(sorted(sites), 1):
        p = sites[key].split("\t")
        objs.append(gen_sites.Site(int(p[0], 16), int(p[1], 16), p[2], p[3:], n))
    mod = HMOD.get(fn, "H" + fn.lstrip("_"))
    battery = gen_sites.emit_battery(
        objs, PRED, "", [f"Lua.Vm.Code.FixedImage_{cap}", "Lua.Vm.Arms.Text"], "", NS,
        f"Lua.Vm.Code.{fn}_at_{{addr}} (Lua.Vm.Code.textLoaded_{cap}Loaded hmem)",
        {a: 0 for a in range(lo, hi, 4)},
        f"the helper {fn} (driver: scripts/gen_lua_arms.py)")
    bodies = []
    for name, spec in specs:
        em = gen_segment.SegmentEmitter(spec)
        em.emit()
        bodies.append(em.body_text)
    jalr = any(st["class"] == "jalr" for _, spec in specs for st in spec["steps"])
    half = any(st["class"] == "sh" for _, spec in specs for st in spec["steps"])
    ok_imports = OK_IMPORT + ("\nimport Lua.Vm.Arms.RegsOkJalr" if jalr else "") + \
        ("\nimport Lua.Vm.Arms.TextHalf" if half else "")
    text = f"""import {NS}.Sites.{mod}
import {ok_imports}
import Lua.Vm.Arms.Text
import Vsa.Sim.SegState

/-! {HEADER}

Segment theorems of the helper `{fn}` (`[0x{lo:08x}, 0x{hi:08x})`), `SegSt` to
`SegSt`, carrying the caller's fetch-head registers (scripts/syi/gen_segment.py,
`"boundary": "segst"`). -/

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail ConcurrencyInterfaceV1 Vsa
open Register
open Sail.ConcurrencyInterfaceV1.PreSail
open Vsa.Machine (MState Config Step Steps)
open Vsa.Logic
open Vsa.Sim

namespace {NS}

""" + "\n\n".join(bodies) + f"\n\nend {NS}\n"
    return mod, battery, text


def split_at_calls(g, segs):
    out = []
    for lo, hi in segs:
        start = lo
        for a in range(lo, hi, 4):
            if g[a][0].split()[0] == "jal" and a + 4 < hi:
                out.append((start, a + 4))
                start = a + 4
        out.append((start, hi))
    return out


def variants(g, lo, hi):
    """[(suffix, path)] for the segment: one per polarity of a final branch."""
    last = hi - 4
    base = {a: "nottaken" for a in range(lo, hi, 4)}
    word = next(iter(d2s.disassemble(d2s.DEFAULT_OBJDUMP, d2s.DEFAULT_ELF,
                                     last, hi)))[1]
    if (word & 0x7f) == 0b1100011:
        return [("_t", {**base, last: "taken"}), ("_n", base)]
    return [("", base)]


def seg_spec(lo, hi, path, name, sim, keep=KEEP):
    """The segst spec of [lo, hi) along `path`; a `sim` segment carries the
    fetch-head registers (`keep`) and the console output."""
    lines = []
    for addr, word, raw in d2s.disassemble(d2s.DEFAULT_OBJDUMP, d2s.DEFAULT_ELF,
                                           lo, hi):
        lines += [x.tsv() for x in d2s.classify(addr, word, raw, path)]
    spec, rows = d2seg.complete(lo, hi, lines, "<elf>", name, PRED, NS, [], SURVIVAL,
                                keep=keep if sim else None, output=sim)
    if sim:
        spec["ok"] = OK
    return spec, rows


def collect(only):
    g = dfa.cfg()
    f1 = set(json.load(open(dfa.ARMS_JSON))["summary"]["F1_ops"]) | dfa.F1_EXTRA_OPS | set(EXTRA_ARMS)
    arms, cuts = [], {}
    for r in csv.DictReader(open(dfa.ARMS_TSV), delimiter="\t"):
        if r["op"] not in f1 or (only and r["op"] not in only):
            continue
        t = int(r["target"], 16)
        reach = dfa.arm(g, t)
        segs = split_at_calls(g, dfa.segments(g, reach, t))
        names = []
        for lo, hi in segs:
            for suf, path in variants(g, lo, hi):
                name = f"seg_{lo:08x}_{hi:08x}{suf}"
                names.append(name)
                cuts[name] = (lo, hi, path)
        arms.append((r["op"], names))
    sim = {n for op, ns in arms if op in SIM_OPS for n in ns}
    specs, sites = {}, {}
    for name, (lo, hi, path) in cuts.items():
        spec, rows = seg_spec(lo, hi, path, name, name in sim)
        specs[name] = (lo, spec, rows)
    # calls to a summarised helper continue at the return address (call nodes)
    jal_end = {n for n, (lo, hi, path) in cuts.items()
               if g[hi - 4][0].split()[0] == "jal"
               and re.search(r"<([^>+]+)>", g[hi - 4][0]).group(1) in SUMMARISED}
    for name, regs in live_keep(arms, specs, sim, jal_end).items():
        if regs:
            lo, hi, path = cuts[name]
            spec, rows = seg_spec(lo, hi, path, name, True,
                                  keep=KEEP + sorted(int(r[1:]) for r in regs))
            specs[name] = (lo, spec, rows)
    for name, (lo, spec, rows) in specs.items():
        for row in rows:
            parts = row.split("\t")
            key = (int(parts[0], 16), parts[2])
            sites.setdefault(key, row)
    return arms, specs, sites


def live_keep(arms, specs, sim, jal_end=frozenset()):
    """Per SIM segment, the registers a later segment of its arm reads that
    the segment neither reads nor writes (a temporary such as `ADD`'s slot
    of `R[A]`, computed before a branch and stored after it): they are
    carried through (`keep`), by a liveness fixpoint over the arm's
    segments. A segment ending in a `jal` continues at the return address
    (the callee is a summarised call node)."""
    info = {}
    for n in sim:
        em = gen_segment.SegmentEmitter(specs[n][1])
        em.emit()
        m = re.match(r"\(?(0x[0-9a-f]+)#64", em.end_pc)
        end = int(m.group(1), 16) if m else None    # a return (`OP_RETURN*`'s `ret`)
        if n in jal_end:
            end = int(n.split("_")[2], 16)
        info[n] = ({p["reg"] for p in specs[n][1]["pins"]}, {r for r, _ in em.pins}, end)
    extra = {n: set() for n in sim}
    for op, names in arms:
        if op not in SIM_OPS:
            continue
        live = {n: set(info[n][0]) for n in names}

        def live_out(n):
            return set().union(*[live[m] for m in names if specs[m][0] == info[n][2]])
        changed = True
        while changed:
            changed = False
            for n in names:
                new = info[n][0] | (live_out(n) - info[n][1])
                if not new <= live[n]:
                    live[n] |= new
                    changed = True
        for n in names:
            extra[n] |= live_out(n) - info[n][1]
    return extra


def head_spec():
    """The fetch head `[fetch_head, dispatch_jr + 4)` with both bound checks
    not taken (`trap = 0`, opcode ≤ 81): one segment ending in the `jr`
    through the jump table."""
    lo, hi = dfa.FETCH, int(JT["dispatch_jr"], 16) + 4
    path = {a: "nottaken" for a in range(lo, hi, 4)}
    name = f"seg_{lo:08x}_{hi:08x}"
    # s3 and s4 are the fetch's own outputs: not carried in
    spec, rows = seg_spec(lo, hi, path, name, True,
                          keep=[r for r in KEEP if r not in (19, 20)])
    return name, spec, rows


def prologue_specs(sites):
    """`luaV_execute`'s prologue `[entry, fetch_head)` (the C code before the
    loop), with the `trap` check `bnez s5` not taken (no hooks), as two
    segments cut where the arms' code joins it (`startfunc`, the first
    prologue address with an arm site: `OP_CALL`/`OP_TAILCALL` `goto
    startfunc`):

    * `[entry, startfunc)`: the frame (`addi sp,sp,-176`, the saves of `ra`,
      `s0 … s11`), `L`/`ci` into s0/s7, the jump table into s8;
    * `[startfunc, fetch_head)`: the loads of `ci->func`, `L->hookmask`,
      `ci->u.l.savedpc`, the closure and its `k`; s1 = 81, s2 = 3; `base`.

    The cut keeps the second segment's loads over its own entry memory, not
    over the first segment's store chain. Both thread the console
    output, and carry `gp` and the jump table (s8) through, the frame
    `Lua.Vm.Sim.vmRel_entry` needs."""
    lo, hi = Layout_symLuaVExecute(), dfa.FETCH
    joined = {a for a, _ in sites}
    cut = next(a for a in range(lo + 4, hi, 4) if a in joined)
    out = []
    for a, b in ((lo, cut), (cut, hi)):
        path = {x: "nottaken" for x in range(a, b, 4)}
        name = f"seg_{a:08x}_{b:08x}"
        spec, rows = seg_spec(a, b, path, name, True, keep=[3, 24])
        out.append((name, spec, rows))
    return out


def Layout_symLuaVExecute():
    """`luaV_execute`'s entry, as `Lua/Vm/Layout.lean` has it."""
    import re
    txt = (ROOT / "Lua/Vm/Layout.lean").read_text()
    return int(re.search(r"def symLuaVExecute : Nat := (0x[0-9a-f]+)", txt).group(1), 16)


def site_name_of(key):
    addr, cls = key
    arm = {"branch_taken": "_taken", "branch_nottaken": "_nottaken"}.get(cls, "")
    return f"site_{addr:08x}{arm}"


def render(only=None) -> dict[Path, str]:
    arms, specs, sites = collect(only)
    parts = gen_sites.load_parts(ROOT / "Lua/Vm/Code/LuaV_execute")
    dump = gen_sites.load_ast_dump(ROOT / "Lua/Vm/DecodeCheck/ast_dump.txt")
    files: dict[Path, str] = {}
    # the extra arms' own segments and sites (`EXTRA_ARMS`)
    base = {n for op, ns in arms if op not in EXTRA_ARMS for n in ns}
    xsegs = {op: [n for n in ns if n not in base] for op, ns in arms if op in EXTRA_ARMS}
    base_sites = set()
    for n in base:
        for row in specs[n][2]:
            p = row.split("\t")
            base_sites.add((int(p[0], 16), p[2]))
    xsites = {}
    for op, ns in xsegs.items():
        for n in ns:
            for row in specs[n][2]:
                p = row.split("\t")
                key = (int(p[0], 16), p[2])
                if key not in base_sites:
                    xsites.setdefault(op, {}).setdefault(key, row)
    xall = {k for d in xsites.values() for k in d}
    # site batteries
    keys = sorted(k for k in sites if k not in xall)
    site_mod = {}
    for i in range(0, len(keys), SITES_PER_MODULE):
        chunk = keys[i:i + SITES_PER_MODULE]
        mod = f"S{i // SITES_PER_MODULE:02d}"
        objs = []
        for n, key in enumerate(chunk, 1):
            p = sites[key].split("\t")
            objs.append(gen_sites.Site(int(p[0], 16), int(p[1], 16), p[2], p[3:], n))
            site_mod[site_name_of(key)] = f"{NS}.Sites.{mod}"
        text = gen_sites.emit_battery(
            objs, PRED, "", CODE_IMPORTS, "", NS, TEMPLATE, parts,
            "the F1 arms of luaV_execute (driver: scripts/gen_lua_arms.py)",
            ast_dump=dump)
        files[OUT / "Sites" / f"{mod}.lean"] = text
    for op, d in xsites.items():
        mod = "SX" + op[3:]
        objs = []
        for n, key in enumerate(sorted(d), 1):
            p = d[key].split("\t")
            objs.append(gen_sites.Site(int(p[0], 16), int(p[1], 16), p[2], p[3:], n))
            site_mod[site_name_of(key)] = f"{NS}.Sites.{mod}"
        files[OUT / "Sites" / f"{mod}.lean"] = gen_sites.emit_battery(
            objs, PRED, "", CODE_IMPORTS, "", NS, TEMPLATE, parts,
            f"the arm {op} of luaV_execute (driver: scripts/gen_lua_arms.py)",
            ast_dump=dump)
    # segment theorems
    xnames = {n for ns in xsegs.values() for n in ns}
    names = sorted((n for n in specs if n not in xnames), key=lambda n: (specs[n][0], n))
    groups = [(f"G{i // SEGS_PER_MODULE:02d}", names[i:i + SEGS_PER_MODULE])
              for i in range(0, len(names), SEGS_PER_MODULE)]
    groups += [("X" + op[3:], sorted(ns, key=lambda n: (specs[n][0], n))) for op, ns in xsegs.items()]
    seg_mods = []
    for mod, chunk in groups:
        seg_mods.append(mod)
        imports = {"Lua.Vm.Arms.Text", "Vsa.Sim.SegState"}
        bodies = []
        for name in chunk:
            spec = specs[name][1]
            for st in spec["steps"]:
                imports.add(site_mod[st["site"]])
            if spec.get("ok"):
                imports.add(OK_IMPORT)
            em = gen_segment.SegmentEmitter(spec)
            em.emit()
            bodies.append(em.body_text)
        text = "\n".join(f"import {m}" for m in sorted(imports))
        text += f"""

/-! {HEADER}

Segment theorems of the F1 arms of `luaV_execute`, `SegSt` to `SegSt`
(scripts/syi/gen_segment.py, `"boundary": "segst"`). -/

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail ConcurrencyInterfaceV1 Vsa
open Register
open Sail.ConcurrencyInterfaceV1.PreSail
open Vsa.Machine (MState Config Step Steps)
open Vsa.Logic
open Vsa.Sim

namespace {NS}

""" + "\n\n".join(bodies) + f"\n\nend {NS}\n"
        files[OUT / "Segs" / f"{mod}.lean"] = text
    # the helpers: one battery and one segment module each
    for mod, battery, text in helper_all():
        files[OUT / "Sites" / f"{mod}.lean"] = battery
        files[OUT / "Segs" / f"{mod}.lean"] = text
        seg_mods.append(mod)
    # the fetch head: its own battery and segment (not shared with any arm)
    hname, hspec, hrows = head_spec()
    objs = []
    for n, row in enumerate(hrows, 1):
        p = row.split("\t")
        if (int(p[0], 16), p[2]) in sites:
            raise SystemExit(f"fetch-head site {p[0]} is also an arm site")
        objs.append(gen_sites.Site(int(p[0], 16), int(p[1], 16), p[2], p[3:], n))
    files[OUT / "HeadSites.lean"] = gen_sites.emit_battery(
        objs, PRED, "", CODE_IMPORTS, "", NS, TEMPLATE, parts,
        "the fetch head of luaV_execute (driver: scripts/gen_lua_arms.py)",
        ast_dump=dump)
    em = gen_segment.SegmentEmitter(hspec)
    em.emit()
    jt, fetch = int(JT["addr"], 16), dfa.FETCH
    files[OUT / "Head.lean"] = f"""import {NS}.HeadSites
import {NS}.RegsOk
import {NS}.Text
import Vsa.Sim.SegState

/-! {HEADER}

The fetch head of `luaV_execute` (`vmfetch` and `vmdispatch`, `lvm.c`), from
`experiments/census/luaV_execute_arms.json`: at `headPc` the loop tests
`trap` (s5), loads the instruction at `pc` (s11) into s4, sets s3 = pc + 4,
bounds the opcode by 81 (s1) and jumps through the {JT['entries']}-entry table
of {JT['entry_bytes']}-byte offsets at `jtBase` (s8, in `.rodata`): target =
`jtBase + sext(entry)`. `{hname}` is that run with both bound checks not taken,
ending at the `jr` (`dispatchPc`). -/

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail ConcurrencyInterfaceV1 Vsa
open Register
open Sail.ConcurrencyInterfaceV1.PreSail
open Vsa.Machine (MState Config Step Steps)
open Vsa.Logic
open Vsa.Sim

namespace {NS}

/-- The fetch head: every arm jumps back here. -/
def headPc : BitVec 64 := 0x{fetch:08x}#64
/-- The dispatch `jr`. -/
def dispatchPc : BitVec 64 := 0x{int(JT['dispatch_jr'], 16):08x}#64
/-- The jump table's base (the `auipc`/`addi` of `luaV_execute`'s prologue). -/
def jtBase : Nat := 0x{jt:08x}
/-- The number of table entries (opcodes `0 … jtEntries - 1`). -/
def jtEntries : Nat := {JT['entries']}

{em.body_text}

end {NS}
"""
    # the prologue: its own battery and segments
    # `startfunc` is shared with the arms that `goto startfunc` (OP_CALL,
    # OP_TAILCALL): those sites come from the arm batteries
    psegs = prologue_specs(sites)
    pnames = [n for n, _, _ in psegs]
    objs, shared, seen = [], set(), set()
    for _, _, prows in psegs:
        for row in prows:
            p = row.split("\t")
            key = (int(p[0], 16), p[2])
            if key in sites:
                if sites[key] != row:
                    raise SystemExit(f"prologue site {p[0]} differs from the arm site")
                shared.add(site_mod[site_name_of(key)])
                continue
            if key in seen:
                continue
            seen.add(key)
            objs.append(gen_sites.Site(key[0], int(p[1], 16), p[2], p[3:], len(objs) + 1))
    files[OUT / "PrologueSites.lean"] = gen_sites.emit_battery(
        objs, PRED, "", CODE_IMPORTS, "", NS, TEMPLATE, parts,
        "the prologue of luaV_execute (driver: scripts/gen_lua_arms.py)",
        ast_dump=dump)
    pbodies = []
    for _, pspec, _ in psegs:
        em = gen_segment.SegmentEmitter(pspec)
        em.emit()
        pbodies.append(em.body_text)
    pname = " ".join(pnames)
    pbody = "\n\n".join(pbodies)
    pimports = "".join(f"import {m}\n" for m in sorted(shared))
    files[OUT / "Prologue.lean"] = f"""import {NS}.PrologueSites
{pimports}import {NS}.RegsOk
import {NS}.Text
import Vsa.Sim.SegState

/-! {HEADER}

The prologue of `luaV_execute` (`lvm.c`, up to `startfunc`'s `vmfetch`):
`addi sp,sp,-176` and the saves of `ra`, `s0 … s11`; `L` (a0) and `ci` (a1)
into s0 and s7; the jump table into s8; `startfunc`'s loads of `ci->func`
(t1), `trap = L->hookmask` (s5), `pc = ci->u.l.savedpc` (s11), the closure
(stored at `8(sp)`) and its `k` (stored at `0(sp)`); s1 = 81, s2 = 3; the
`trap` check `bnez s5` not taken; `base = ci->func + 1` (s9). The segments
`{pnames[0]}` (to `startfunc`) and `{pnames[1]}` (to the fetch head `headPc`). -/

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail ConcurrencyInterfaceV1 Vsa
open Register
open Sail.ConcurrencyInterfaceV1.PreSail
open Vsa.Machine (MState Config Step Steps)
open Vsa.Logic
open Vsa.Sim

namespace {NS}

{pbody}

end {NS}
"""
    files[ROOT / "Lua/Vm/Arms.lean"] = (
        "\n".join(f"import {NS}.Segs.{m}" for m in seg_mods)
        + f"\nimport {NS}.Head\nimport {NS}.Prologue"
        + f"\n\n/-! {HEADER}\n\nThe segment theorems of the F1 arms of `luaV_execute`: "
        f"{len(specs)} segments ({len(sites)} site lemmas) over {len(arms)} arms, "
        f"the fetch head `{hname}` (`Lua/Vm/Arms/Head.lean`) and the prologue `{pname}` "
        "(`Lua/Vm/Arms/Prologue.lean`); "
        "`Lua/Vm/Arms/arms.tsv` lists each arm's segments. -/\n")
    files[OUT / "arms.tsv"] = ("# " + HEADER + "\nop\tsegments\n" + "".join(
        f"{op}\t{' '.join(ns)}\n" for op, ns in arms) + f"HEAD\t{hname}\nPROLOGUE\t{pname}\n")
    return files


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="fail if a generated file differs from the committed one")
    ap.add_argument("--only", default=None,
                    help="comma-separated opcodes (for experiments; not with --check)")
    args = ap.parse_args()
    only = set(args.only.split(",")) if args.only else None
    files = render(only)
    if args.check:
        bad = [p for p, t in files.items() if not p.exists() or p.read_text() != t]
        stale = [p for d in ("Sites", "Segs") for p in (OUT / d).glob("*.lean")
                 if p not in files]
        for p in bad + stale:
            print(f"drift: {p.relative_to(ROOT)}", file=sys.stderr)
        return 1 if bad or stale else 0
    for d in ("Sites", "Segs"):
        (OUT / d).mkdir(parents=True, exist_ok=True)
        for p in (OUT / d).glob("*.lean"):
            if p not in files:
                p.unlink()
    for p, t in files.items():
        p.write_text(t)
    print(f"wrote {len(files)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
