import Lua.Ast.Syntax

/-! GENERATED by scripts/gen_ast.py from `c/tests/stuck/s_forstr.lua` -- do not edit.

```lua
for i = 1, "2" do print(i) end
```
-/

namespace Lua.Programs

open Lua.Ast

/-- The AST of `c/tests/stuck/s_forstr.lua`. -/
def escForstrAst : Chunk := (.mk [
  .fornum "i" (.numeral (.int 1)) (.string [50]) none (.mk [
    .functioncall (.call (.var (.name "print")) (.explist [(.prefixexp (.var (.name "i")))]))] none)] none)

end Lua.Programs
